### ISSUE TITLE
NGP/NGPC English + Japanese games

### ISSUE THREAD

**Issue by AngelofMe** [libretro/FBNeo#1000]
King of Fighters R-1 - Pocket Fighting Series (Japan, Europe) (En,Ja).ngp
two languages: English and Japanese
you can't change it while you're playing this game
![King of Fighters R-1 - Pocket Fighting Series (Japan, Europe) (En,Ja)-220709-182552](https://user-images.githubusercontent.com/26894447/178101848-1d0a55fb-8761-4c7a-b9db-170ed10c0106.png)
![King of Fighters R-1 - Pocket Fighting Series (Japan, Europe) (En,Ja)-220709-182614](https://user-images.githubusercontent.com/26894447/178101849-ac90b42f-eaa1-423a-8870-d2b4acd2c6f8.png)
![King of Fighters R-1 - Pocket Fighting Series (Japan, Europe) (En,Ja)-220709-182631](https://user-images.githubusercontent.com/26894447/178101850-4a8e1c05-9295-461d-b9b2-07b6af67e364.png)

**Comment by AngelofMe** [comment]
a Language option or anything else

**Comment by AngelofMe** [comment]
all nvp/ngpc En,Ja games
![Screenshot_20220709-184122_Trebuchet](https://user-images.githubusercontent.com/26894447/178102348-3a7a5339-0900-4d91-afe7-5871637369c7.png)
![Screenshot_20220709-184244_Trebuchet](https://user-images.githubusercontent.com/26894447/178102397-43783727-f5a2-45da-9ebf-59577488c275.png)
![Screenshot_20220709-184257_Trebuchet](https://user-images.githubusercontent.com/26894447/178102399-aa2f4575-7125-44a9-8c30-d2beb8ea118e.png)
![Screenshot_20220709-184306_Trebuchet](https://user-images.githubusercontent.com/26894447/178102403-fbdae58f-1898-47d2-957e-c97971fac971.png)

**Comment by barbudreadmon** [comment]
That will be my last warning, **stop with the walls of images**.

>you can't change it while you're playing this game

Yes you can't.
