### ISSUE TITLE
It's definitely a bug, All Buttons Are Disabled

### ISSUE THREAD

**Issue by AngelofMe** [libretro/FBNeo#1001]
You told me
See the dats for supported games.
https://github.com/libretro/FBNeo/issues/998
but you lied to me
you didn't read carefully
I found a game it doesn't support
MSX 1
Magical Stones (HB)
https://youtu.be/EysfcckhBOw
Joypad: UP DOWN LEFT RIGHT 1 2
(tank you homebrew games also need F1 and Stop)

arm64-v8a
Android 12 (LineageOS 19.1 20220523 build)
RA (AArch64) 1.10.3
FBN 1.0.0.03 ff5f099

**Comment by AngelofMe** [comment]
https://github.com/libretro/FBNeo/issues/998
Many games are in dats, but I can't find the corresponding controllers
It makes me very unhappy

**Comment by AngelofMe** [comment]
https://github.com/libretro/FBNeo/issues/998
Many games are in dats, but I can't find the corresponding controllers
It makes me very unhappy

**Comment by barbudreadmon** [comment]
I'll close and lock all your issues from now on, don't post here anymore.
