### ISSUE TITLE
Speed hacks for sfiii3

### ISSUE THREAD

**Issue by palmerj** [libretro/FBNeo#1005]
> I implemented a speedhack for those a few months ago, so they should run a fair bit faster than they did.

@barbudreadmon I saw this above comment in https://github.com/libretro/FBNeo/issues/711#issuecomment-939240145. Are there anymore CPS3 speedhack that you are considering that can help speed up sfiii3? I'm running Retroarch using this core on my low spec AndriodTV and I'm so close to getting 60FPS! The FinalburnAlpha 2012 almost seems to provide a more stable 60FPS, but it still does dip from time to time when super combos are performed or some other odd times. I would much rather be using this modern core that is better supported. Not I'm running the 32bit Android build.

**Comment by barbudreadmon** [comment]
it took me 3 years to find this one, so no i don't intend to look further into this
