### ISSUE TITLE
Windows Builds are currently failing

### ISSUE THREAD

**Issue by GABO1423** [libretro/FBNeo#1006]
After the latest resync with upstream, Windows builds are failing with this following error:

![image](https://user-images.githubusercontent.com/35014183/185663528-d50761c6-1943-4f38-9943-51c0cab270f0.png)

Same error is occurring over at GitLab with both the i686 and x64 builds.

**Comment by MistyDreams** [comment]
I can confirm this issue its a one line fix so they should patch it soon.

**Comment by GABO1423** [comment]
Issue was resolved by commit https://github.com/libretro/FBNeo/commit/b4bda190b6b1cbc57677c1bb12a1e562ba1f3dd1
