### ISSUE TITLE
sample rate odd settin for 57fps games

### ISSUE THREAD

**Issue by MistyDreams** [libretro/FBNeo#1008]
I dont know if you are aware games like tapper are setting the sample rate to 30000 and 57fps games are setting and odd sample rate as well. The 30000 is an old ra bug thats since been fixed. 

I dont understand why the 57 fps games are changing the sample rate though because you need to change the audio timing settings to play these games at proper speed.

**Comment by barbudreadmon** [comment]
>The 30000 is an old ra bug thats since been fixed.

Thanks for the heads-up, i didn't know that, but if i remove that workaround, the bug will come back for people using older versions of retroarch, and maybe other libretro frontends are also affected, so i'll leave it as-is.

>you need to change the audio timing settings to play these games at proper speed. 

I don't.
