### ISSUE TITLE
Hello,Geekers！I really can't find a place to help

### ISSUE THREAD

**Issue by zouplus** [libretro/FBNeo#1011]
want to add a revised game packaged by myself, which is based on oldsplus, so edit d_pgm,cpp the contents such as BurnInfo are added to the cpp. After being compiled by Mingw, it can be directly run under Windows without error reports such as crc and too large. But when I migrate to retroarch, the prompt "romset is unknown" appears. So I added the following content to "dats/FinalBurn Neo (ClrMame Pro XML, Arcade only). dat":(to next floor)

After compiling, an error is finally reported: "romset is unknown". I tried to find the answer in Google and prompted that the clrmamepro reconstruction needs to be built. But I tried to name oldsplus211.zip oldsplus, which can run (crc can be modified through winips)

**Comment by zouplus** [comment]
`<game name="oldsplus211" cloneof="oldsplus" romof="oldsplus">
                    <comment>hack</comment>
                    <description>Xi You Shi e Zhuang,Xin Qun Mo Luan Wu (World, China, Japan, Hong Kong, Taiwan) (V211)</description>
                    <year>2022</year>
                    <manufacturer>IGS</manufacturer>
                    <rom name="v-203cn.u10" size="4194304" crc="296a8c3a"/>
                    <rom name="igs_t05301w064.u2" merge="igs_t05301w064.u2" size="4194304" crc="9019665b"/>
                    <rom name="igs_a05301w064.u3" merge="igs_a05301w064.u3" size="8388608" crc="5291d22c"/>
                    <rom name="igs_a05302w064.u4" merge="igs_a05302w064.u4" size="8388608" crc="4ed9028c"/>
                    <rom name="igs_a05303w064.u6" merge="igs_a05303w064.u6" size="8388608" crc="5f75eca2"/>
                    <rom name="igs_a05304w064.u8" merge="igs_a05304w064.u8" size="8388608" crc="365015f9"/>
                    <rom name="igs_b05301w064.u9" merge="igs_b05301w064.u9" size="8388608" crc="5286686"/>
                    <rom name="igs_b05302w064.u11" merge="igs_b05302w064.u11" size="8388608" crc="383a24e2"/>
                    <rom name="igs_w05301b032.u5" merge="igs_w05301b032.u5" size="4194304" crc="6adb13ed"/>
                    <rom name="oldsplus_igs027a.bin" merge="oldsplus_igs027a.bin" size="65000" status="nodump"/>
                    <rom name="pgm_t01s.rom" merge="pgm_t01s.rom" size="2097152" crc="1a7123a0"/>
                    <rom name="pgm_m01s.rom" merge="pgm_m01s.rom" size="2097152" crc="45ae7159"/>
                    <rom name="pgm_p01s.u20" merge="pgm_p01s.u20" size="131072" crc="e42b166e"/>
                    <rom name="pgm_p02s.u20" merge="pgm_p02s.u20" size="131072" crc="78c15fa2"/>
                    <rom name="ddp3_bios.u37" merge="ddp3_bios.u37" size="524288" crc="b3cc5c8f"/>
                    <rom name="bios.u42" merge="bios.u42" size="131072" crc="517cf7a2"/>
                    <video type="raster" orientation="horizontal" width="448" height="224" aspectx="4" aspecty="3"/>
                    <driver status="good"/>
            </game>`

**Comment by zouplus** [comment]
`<game name="oldsplus211" cloneof="oldsplus" romof="oldsplus">
	<comment>hack</comment>
	<description>Xi You Shi e Zhuang,Xin Qun Mo Luan Wu (World, China, Japan, Hong Kong, Taiwan) (V211)</description>
	<year>2022</year>
	<manufacturer>IGS</manufacturer>
	<rom name="v-203cn.u10" size="4194304" crc="296a8c3a"/>
	<rom name="igs_t05301w064.u2" merge="igs_t05301w064.u2" size="4194304" crc="9019665b"/>
	<rom name="igs_a05301w064.u3" merge="igs_a05301w064.u3" size="8388608" crc="5291d22c"/>
	<rom name="igs_a05302w064.u4" merge="igs_a05302w064.u4" size="8388608" crc="4ed9028c"/>
	<rom name="igs_a05303w064.u6" merge="igs_a05303w064.u6" size="8388608" crc="5f75eca2"/>
	<rom name="igs_a05304w064.u8" merge="igs_a05304w064.u8" size="8388608" crc="365015f9"/>
	<rom name="igs_b05301w064.u9" merge="igs_b05301w064.u9" size="8388608" crc="5286686"/>
	<rom name="igs_b05302w064.u11" merge="igs_b05302w064.u11" size="8388608" crc="383a24e2"/>
	<rom name="igs_w05301b032.u5" merge="igs_w05301b032.u5" size="4194304" crc="6adb13ed"/>
	<rom name="oldsplus_igs027a.bin" merge="oldsplus_igs027a.bin" size="65000" status="nodump"/>
	<rom name="pgm_t01s.rom" merge="pgm_t01s.rom" size="2097152" crc="1a7123a0"/>
	<rom name="pgm_m01s.rom" merge="pgm_m01s.rom" size="2097152" crc="45ae7159"/>
	<rom name="pgm_p01s.u20" merge="pgm_p01s.u20" size="131072" crc="e42b166e"/>
	<rom name="pgm_p02s.u20" merge="pgm_p02s.u20" size="131072" crc="78c15fa2"/>
	<rom name="ddp3_bios.u37" merge="ddp3_bios.u37" size="524288" crc="b3cc5c8f"/>
	<rom name="bios.u42" merge="bios.u42" size="131072" crc="517cf7a2"/>
	<video type="raster" orientation="horizontal" width="448" height="224" aspectx="4" aspecty="3"/>
	<driver status="good"/>
</game>`

**Comment by zouplus** [comment]
<game name="oldsplus211" cloneof="oldsplus" romof="oldsplus">
	<comment>hack</comment>
	<description>Xi You Shi e Zhuang,Xin Qun Mo Luan Wu (World, China, Japan, Hong Kong, Taiwan) (V211)</description>
	<year>2022</year>
	<manufacturer>IGS</manufacturer>
	<rom name="v-203cn.u10" size="4194304" crc="296a8c3a"/>
	<rom name="igs_t05301w064.u2" merge="igs_t05301w064.u2" size="4194304" crc="9019665b"/>
	<rom name="igs_a05301w064.u3" merge="igs_a05301w064.u3" size="8388608" crc="5291d22c"/>
	<rom name="igs_a05302w064.u4" merge="igs_a05302w064.u4" size="8388608" crc="4ed9028c"/>
	<rom name="igs_a05303w064.u6" merge="igs_a05303w064.u6" size="8388608" crc="5f75eca2"/>
	<rom name="igs_a05304w064.u8" merge="igs_a05304w064.u8" size="8388608" crc="365015f9"/>
	<rom name="igs_b05301w064.u9" merge="igs_b05301w064.u9" size="8388608" crc="5286686"/>
	<rom name="igs_b05302w064.u11" merge="igs_b05302w064.u11" size="8388608" crc="383a24e2"/>
	<rom name="igs_w05301b032.u5" merge="igs_w05301b032.u5" size="4194304" crc="6adb13ed"/>
	<rom name="oldsplus_igs027a.bin" merge="oldsplus_igs027a.bin" size="65000" status="nodump"/>
	<rom name="pgm_t01s.rom" merge="pgm_t01s.rom" size="2097152" crc="1a7123a0"/>
	<rom name="pgm_m01s.rom" merge="pgm_m01s.rom" size="2097152" crc="45ae7159"/>
	<rom name="pgm_p01s.u20" merge="pgm_p01s.u20" size="131072" crc="e42b166e"/>
	<rom name="pgm_p02s.u20" merge="pgm_p02s.u20" size="131072" crc="78c15fa2"/>
	<rom name="ddp3_bios.u37" merge="ddp3_bios.u37" size="524288" crc="b3cc5c8f"/>
	<rom name="bios.u42" merge="bios.u42" size="131072" crc="517cf7a2"/>
	<video type="raster" orientation="horizontal" width="448" height="224" aspectx="4" aspecty="3"/>
	<driver status="good"/>
</game>

**Comment by zouplus** [comment]
<img width="573" alt="t1" src="https://user-images.githubusercontent.com/100817707/190887694-9f7d546c-08fe-4dce-b4dd-5aeed726c12e.png">

**Comment by zouplus** [comment]
<img width="858" alt="2" src="https://user-images.githubusercontent.com/100817707/190887723-32ba3702-07e3-45e1-83f5-fb7da839513d.png">

**Comment by barbudreadmon** [comment]
That cpp code looks correct, make sure you are running all commands from https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#how-to-build

**Comment by zouplus** [comment]
我编译通过Emuelec下面的脚本进行构建，构建的sh如截图

**Comment by zouplus** [comment]
![d](https://user-images.githubusercontent.com/100817707/190888384-d57006a2-e3d4-4e1d-83dd-1c05db9c2dcd.jpg)
这看起来也没有任何问题，毕竟：https://archive.org/download/fbnarcade-fullnonmerged/arcade/ 的rom 游戏是可以运行的

**Comment by barbudreadmon** [comment]
>There seems to be no problem

There is though, i'm no expert with emuelec build scripts, but it's obviously not running all commands i linked

**Comment by zouplus** [comment]
Need to add a command? “generate-files”？

**Comment by zouplus** [comment]
<img width="500" alt="ok" src="https://user-images.githubusercontent.com/100817707/190888953-1bfc27e7-7a6a-455c-ac65-0ad99d90f8b9.png">
 It is the log for build info

**Comment by barbudreadmon** [comment]
Yes, running `make -j5 -C src/burner/libretro generate-files` **is required in your case because you added new romsets**, it's optional otherwise which is why emuelec isn't running it.

This is an emuelec problem, and i'm not an emuelec developper.

**Comment by zouplus** [comment]
OK, thank you. I really found many places. After all, there are few popular developers in my country. Thanks again for the geek's efforts for the simulation project.

**Comment by zouplus** [comment]
<img width="367" alt="err" src="https://user-images.githubusercontent.com/100817707/190889589-856f0d4c-4636-4447-ae29-f8054c62b923.png">
I try cmd "make -j5 -C src/burner/libretro generate-files" get error but "make -j5 -C src/burner/libretro generate-files" is okay。

**Comment by zouplus** [comment]
those command run at ubuntu

**Comment by zouplus** [comment]
supplement：2 shell command on ubuntu ，run failed。

**Comment by barbudreadmon** [comment]
>I try cmd "make -j5 -C src/burner/libretro generate-files" get error but "make -j5 -C src/burner/libretro generate-files" is okay

Do you mean : I try cmd "make -j5 -C src/burner/libretro" get error but "make -j5 -C src/burner/libretro generate-files" is okay ?
You probably did a mistake by running `make -j5 -C src/burner/libretro` **before** adding your code, **DON'T**.
To fix this, you can **additionaly** run `make -j5 -C src/burner/libretro clean` before running `make -j5 -C src/burner/libretro`

**Comment by zouplus** [comment]
No，I think the envirment is clean，because I download master branch to compile…
