### ISSUE TITLE
add the same ips startup as the standalone  version for the libretro port

### ISSUE THREAD

**Issue by crashGG** [libretro/FBNeo#1014]
The existing method must put the patched version of the romset into SYSTEM_DIRECTORY/fbneo/patched ,it is very inconvenient to manage, and not conducive to start in any front-ends.Hope to add the same ips startup as the standalone  version for the libretro port.

for example:
retroarch -c retroarch.cfg -L fbneo_libretro.dll GAME.ZIP -ips=IPS.ZIP
Of course the IPS file need to be pre-edited to match the GAME

**Comment by barbudreadmon** [comment]
I won't work on this but you are welcome if you want to provide a PR for it.

**Comment by zcf19960503** [comment]
Come on, I support you！

**Comment by barbudreadmon** [comment]
@crashGG so will you implement it or should i close this ?
