### ISSUE TITLE
[FR] add per-game configurable autofire/turbo buttons

### ISSUE THREAD

**Issue by eadmaster** [libretro/FBNeo#1015]
As alternative to the turbo feature in the frontend, allow setting per-game autofire buttons in the Controls menu, like in Nestopia:
![img](https://user-images.githubusercontent.com/925171/193425275-22cbbc4e-08d7-4abb-86c3-aecfab5f6ea0.png)

Prolly some code from this PR can be reused :
https://github.com/libretro/gambatte-libretro/issues/165

Related issues:

https://github.com/libretro/FBNeo/issues/355

**Comment by barbudreadmon** [comment]
See https://github.com/libretro/RetroArch/issues/11273, the current retropad model is limited to 16 actions, which are already all in use by this core.
If you are talking about a specific machine which happens to have free buttons, **be precise**.

**Comment by eadmaster** [comment]
Most machines i've seen use less than 3 fire buttons, so there should be enough free to have 2/3 extra autofire buttons.

In the Neogeo machines i've seen you've added combo macros, which are useful especially for fighting games.
Shmup and beatemup games would benefit more from autofire/turbo buttons instead.

So i guess this should be done on a per-game basis.

**Comment by barbudreadmon** [comment]
I'll close and won't accept requests regarding this as long as the feature request from https://github.com/libretro/RetroArch/issues/11273 is not available
