### ISSUE TITLE
[ghouls] Add "4-way" Input Option

### ISSUE THREAD

**Issue by Awakened0** [libretro/FBNeo#1018]
Ghouls 'n Ghosts has a frustrating limitation in that if you press a diagonal direction, like Up+Right, Arthur stops moving. If it's possible to add an option to only input cardinal directions, it should fix this.

**Comment by barbudreadmon** [comment]
>it should fix this

It doesn't seem like a solution, libretro-mame still has this behavior even after enabling its "4-way simulation" core option.

@dinkc64 any thoughts about this ?

**Comment by dinkc64** [comment]
Ghouls is set up as a 4-way game, the test mode proves it.  (I even checked the code to make sure test mode wasn't lieing).

So, I spent several minutes moving Arthur in fbneo and mame, and they appear (to me) to behave the same way.  If I'm missing something, please test/compare in mame to be sure, and explain in more detail how I can create the problem on my side.  Once I see/experience the problem I can fix it.

best regards,
- dink

**Comment by barbudreadmon** [comment]
My findings : 
- if you press up-left in mame and fbneo, first direction pressed will always be discarded (none in case of a tie)
- if you press up-left in mame2003+, second direction pressed will always be discarded (both in case of a tie)

So basicallly we got 2 totally opposite behaviors here, and i'm not convinced one is better than the other so i'd rather leave things as they are.

On a sidenote, i noticed a certain behavior on all 3 emulators : i wasn't able to enter input test by pressing start on my gamepad, but keyboard worked, maybe some hold button logic could get around this.

**Comment by dinkc64** [comment]
I'll see what I can come up with, and do some tests - keeping in mind I'm quite a fan of the gng series :)

does your start button only pulse the button real quick or something?  even if you hold it down?

**Comment by Awakened0** [comment]
I played around with 2003 Plus's 4-Way mode and definitely prefer playing with it on. It's not a perfect solution, but just playing normally I didn't find myself coming to a dead stop accidentally like I do with it off.

I'm surprised someone hasn't made a "Yuji Naka Edition" romhack of arcade Ghouls with 8-Way movement like the Genesis version. But arcade romhacks are more rare than console and handheld ones.

**Comment by dinkc64** [comment]
barbudreadmon, thanks, please test the latest commit :)

**Comment by dinkc64** [comment]
ghouls/gng being my absolute favorite games ever, I usually try to get in a 2-all every couple months.
Using this alternate 4-way input method really wrecks my game, maybe I've implemented it wrong? (hint: please test)

I'll make it a dip option, to use the alternate 4-way style.  Once we have verification that things are working how they should in ghouls, I'll add to gng if needed/wanted.

best regards,
- dink

**Comment by Awakened0** [comment]
Thanks, looking forward to trying it out!

**Comment by Awakened0** [comment]
Tested out Alternate 4-Way in FB Neo Win64 nightly and it's blocking jump and attack inputs when holding a diagonal. MAME 2003 Plus's 4-Way option doesn't have that problem.

**Comment by dinkc64** [comment]
Awakened0, thanks for testing & feedback!  Please test again with the latest code.

best regards,
- dink

**Comment by Awakened0** [comment]
Looks to be working great now!

**Comment by dinkc64** [comment]
Awakened0, do you think this option should be available on gng as well?

**Comment by Awakened0** [comment]
Probably, since you can accidentally "ladder warp" while holding up+right/left or duck with down+right/left.

**Comment by dinkc64** [comment]
dip options have been added for gng :)
p.s.
The ladder warp is helpful in a few situations, and happens on the original machine with 4-way joy too :)

**Comment by Awakened0** [comment]
gng's 4-way alternate mode amusingly can cause Arthur to run in place sometimes when throwing a weapon while holding Up+Right/Left. Also, after dying I can't move until dying again. That doesn't happen in the 8-way or normal 4-way modes.

**Comment by dinkc64** [comment]
Lately I'm really good at making bugs, it's like an insurance policy so I have something to do later in the day... :)
Jokes aside, thanks for letting me know about the issue,

best regards,
- dink

**Comment by Awakened0** [comment]
Heh, no probs :)

**Comment by dinkc64** [comment]
I think it's OK now, please give it a try :)

best regards,
- dink

**Comment by Awakened0** [comment]
Yep, looks all good now. Think it's time to close this one ; D

Great series and always fun to play around Halloween! Voidu even has a BUY30 code you can use on GnG Resurrection for Steam, but I haven't decided if I want to grab it yet.

Thanks everyone!

**Comment by dinkc64** [comment]
Halloween is a great time for some gng (or gng) - the spooky sound of those burrito-ghosts get me every time, even after hundreds of plays :)

best regards,
- dink
