### ISSUE TITLE
lr-fbneo disables / ignores keyboard and hotkeys when it detects game with missing files in romset.

### ISSUE THREAD

**Issue by Barr-find** [libretro/FBNeo#1019]
I just tested few dumped roms in Retroarch with lr-fbneo and when fbneo failed to load a game it blocked access to keyboard and gamepad hotkeys. Basicaly I got stuck on FBNeo Error info ( screen attached ) without any ability to return to menu close or change game. Only way to exit this situation was to Kill Retroarch process from process manager.

![FBNeo](https://user-images.githubusercontent.com/10328382/200112950-14823964-a35f-485a-b751-c1608ed57968.png)

**Comment by barbudreadmon** [comment]
This is not the first time i hear about such an issue but i'm unable to reproduce it :/
It seems to be setup-related.

**Comment by Barr-find** [comment]
Same thing on My Raspberry Pie 4 using Retropie and on My Windows machine. It's not related to version or distro. To reproduce it You need a badly dumped roms. I might provide couple but I think it might be called illegal distribution of copyright material. ;(

**Comment by barbudreadmon** [comment]
>To reproduce it You need a badly dumped roms

I know how to trigger errors, what i can't reproduce is the inability to leave using keyboard.

**Comment by Barr-find** [comment]
Hmmm... May be it's because I use Hotkey enable setting set as shown on screenshot. ( 7, NA ) is ID of select/menu button on my 8BitDo Bluetooth controller. 

![Retroarch](https://user-images.githubusercontent.com/10328382/200118733-5193424b-e64a-4a49-a4a0-38b1ef9d26cd.png)

In that case It must be something with retroarch itself.

**Comment by barbudreadmon** [comment]
I can't reproduce your settings exactly (the 7 N/A part), and using the other settings i'm still able to quit by pressing shift+escape.
While i think the core is handling all of this properly, i'll try to implement some kind of "press start to exit" workaround.

**Comment by barbudreadmon** [comment]
It should be ok with https://github.com/libretro/FBNeo/commit/ea3040f720ca841a4c7409b1b5d09fc5bab0f6b2
