### ISSUE TITLE
please add mp3 or ogg support for neocd audio tracks

### ISSUE THREAD

**Issue by filevans** [libretro/FBNeo#1020]
thank you

**Comment by filevans** [comment]
I have tried libretro neocd core and mp3s don't work on that either, so what are you talking about "You can use the neocd libretro core if you need support for other formats." !? 

What other formats does it support? As MP3 iso cue does NOT work on it

**Comment by barbudreadmon** [comment]
>What other formats does it support?

I know it supports format we don't, like chd, i thought mp3 was also included in that list.
If no emulator supports your dumps, i can only recommend converting them, i linked a tutorial for that.
