### ISSUE TITLE
Rewinding causes core reboot with Cave CV1k games

### ISSUE THREAD

**Issue by eadmaster** [libretro/FBNeo#1025]
I am running the [latest core build from the buildbot](https://buildbot.libretro.com/nightly/linux/x86_64/latest/fbneo_libretro.so.zip) on Ubuntu 22.04 x64 (also verified on Android with the same results).
As soon as i press the Rewind hotkey the core reboots itself, and i don't see any error in the logs.
Same behavior on all the Cave CV1000 games i've tested: `mmpork, pinkswts, deathsml`.

**Comment by barbudreadmon** [comment]
cv1k savestates are 160MB so you are probably hitting some kind of memory limitation

**Comment by eadmaster** [comment]
ok, i guess it is a RA frontend bug, since with these settings it is working:

Rewind Frames = 10
Rewind Buffer Size = 630MB
Rewind Buffer Size Step = 10MB
