### ISSUE TITLE
Default value for '[Dipswitch] Difficulty' not found.

### ISSUE THREAD

**Issue by royfokk** [libretro/FBNeo#1027]
**Rules and recommendations**
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- make sure it happens with our latest official build from https://github.com/finalburnneo/FBNeo/releases/tag/latest
- any issue on derivated projects that doesn't happen with our latest official build must be reported to that derivated project's maintainers instead

Name: cultures
tested Commit: 11a68c64f1525a1c4c75981ba2a25394325c8eec

After opening the game, there is a signal ask me to report this bug.

![public](https://user-images.githubusercontent.com/117565300/212523862-82915f56-9522-4b1b-96cf-f161852188f8.jpeg)

**Comment by barbudreadmon** [comment]
Thanks for the report, fixed with https://github.com/finalburnneo/FBNeo/commit/61f4cf310a3126dbf5ae58f7b2228fc75b31dd03, it will be available to the libretro soon

**Comment by royfokk** [comment]
The bug was fixed. 
But if you hit "H" key, the game will be reset.

**Comment by royfokk** [comment]
This bug is fixed, thank you very much
