### ISSUE TITLE
 can't control arcade mahjong game hypreact

### ISSUE THREAD

**Issue by royfokk** [libretro/FBNeo#1029]
**Rules and recommendations**
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- make sure it happens with our latest official build from https://github.com/finalburnneo/FBNeo/releases/tag/latest
- any issue on derivated projects that doesn't happen with our latest official build must be reported to that derivated project's maintainers instead

tested commit: 11a68c64f1525a1c4c75981ba2a25394325c8eec
Neither keyboard nor gamepad can control this game. You can't discard a tile with gamepad. keyboard doesn't work.

**Comment by barbudreadmon** [comment]
I found some input typos and tried to fix them in https://github.com/finalburnneo/FBNeo/commit/f85806f0d1f0145d6ba741c1958dd0cb0e4a8f4a

I don't understand a thing about mahjong games ("discarding a tile" ?), so i've no idea if fixing those typos improved the situation, all i can tell is that it looks "programmatically correct", meaning the input bits are now correctly computed and the game is apparently reading them.

Every fixes were sent to the libretro port, let us know if this issue persists.

**Comment by royfokk** [comment]
I think there are two input methods in this game, which can be selected by the DIP switch.

When keyboard mode is selected, it should be controlled by the keyboard. But the keyboard doesn't work at all.

When joystick mode is selected, it should be controlled by a D-pad and 2 buttons. The D-pad works fine, but none of the buttons work.
FYI http://mahjonginmame.com/control.htm

So the game got completely out of hand.

In hypreac2,  joystick mode works fine.

**Comment by barbudreadmon** [comment]
Ok, now i have a better understanding of the problem, the game has some duplicate inputs and only one of them is enabled at a time depending on the dips, it should be ok with https://github.com/finalburnneo/FBNeo/commit/c4d9f1888936cd72aa8ef782853435b89845b48f

**Comment by royfokk** [comment]
I'm afraid this bug has not been fixed yet.
Keyboard mode is still dead.
Joystick mode doesn't have enough bottons.

**Comment by barbudreadmon** [comment]
It seems likely that you were still using an older version of the core when you did those tests, although i don't understand a thing about mahjong, i'm 100% sure all buttons are mapped and doing something whatever mode you are using.

**Comment by royfokk** [comment]
The version I tested is b7c0c93e85377acc9303ac7c3a05c3d4ded9d134.
Compare to the previous version, it add 2 buttons in joystick mode.
L button draw/discard tile.
X button Declares Reach.
I can't explain mahjong rules in detail here. but these two buttons are not enough for the game.

**Comment by barbudreadmon** [comment]
![hypreac1](https://user-images.githubusercontent.com/10391265/212843005-26978ebc-da56-45d7-8d53-67076245aaea.png)
![hypreac2](https://user-images.githubusercontent.com/10391265/212843012-00bb3fac-88c5-4f50-bb7e-82b31b274e20.png)

There are only 12 inputs available in joystick mode and all of them are mapped. The girl in the middle reacts when i press any of those inputs so i can only suppose they are working properly.
I can't understand the problem here, and i won't be able to do anything more.

**Comment by dinkc64** [comment]
Huh? I don't know

**Comment by royfokk** [comment]
My fault.
This bug has been fixed.  Thank you very much.
