### ISSUE TITLE
Some key does not work in some mahjong game.

### ISSUE THREAD

**Issue by royfokk** [libretro/FBNeo#1030]
ejsakura: key "B" "C" "F" does not work.

janjans1 janjans2: key "B" "C"

srmp7: key "C"

srmp4: key "B" "C"

ttmahjng: key "K"

**Comment by barbudreadmon** [comment]
Should be ok with https://github.com/finalburnneo/FBNeo/commit/4901c398f37590b95413d2cec14ba740f5b0c61c, https://github.com/finalburnneo/FBNeo/commit/d34ce5435e56b7f47e9858d7279aafb6a7d6b543 and https://github.com/finalburnneo/FBNeo/commit/cb2c96b0413b41111b350bbd29a07a140ad51a28

**Comment by royfokk** [comment]
This has been fixed, thank you.
