### ISSUE TITLE
keyboard doesn't work in mahjong game ejanhs

### ISSUE THREAD

**Issue by royfokk** [libretro/FBNeo#1031]
The keyboard is completely dead in this game.

**Comment by barbudreadmon** [comment]
This game had quite a few missing inputs, your issue might or might not have been fixed by https://github.com/finalburnneo/FBNeo/commit/4901c398f37590b95413d2cec14ba740f5b0c61c

**Comment by royfokk** [comment]
The keyboard does work, but not in the correct way.
Press “A” discard tile “N”
E -> I
I -> E
M -> A
Other keys don't work.

**Comment by barbudreadmon** [comment]
It should finally be ok

**Comment by royfokk** [comment]
I have tested the latest commit.
D -> K
C G H K L don't work.

**Comment by royfokk** [comment]
Other keys works well.

**Comment by barbudreadmon** [comment]
Oops, we forgot the 1st part of the fix while working on the 2nd part, it should be ok now.

**Comment by royfokk** [comment]
It works well now. thank you very much.
