### ISSUE TITLE
Key error in hypreact

### ISSUE THREAD

**Issue by royfokk** [libretro/FBNeo#1032]
In keyboard mode,  
press “C” key discard tile G,
press “G” key discard tile K,
"K" key doesn't work.

**Comment by barbudreadmon** [comment]
My bad, i made an offset typo in input bits, it will be ok after syncing https://github.com/finalburnneo/FBNeo/commit/d5266b513feb5e026a658b58712e5dd6a0244911 (sometime after i figure out the ejanhs issue)

>"K" key doesn't work.

Actually it is activating something called "chi", and that "chi" key (space?) is the one that doesn't work.

**Comment by royfokk** [comment]
Thank you, this has been fixed.
