### ISSUE TITLE
Can‘t insert coin in the arcade game spiero

### ISSUE THREAD

**Issue by royfokk** [libretro/FBNeo#1034]
**Rules and recommendations**
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- make sure it happens with our latest official build from https://github.com/finalburnneo/FBNeo/releases/tag/latest
- any issue on derivated projects that doesn't happen with our latest official build must be reported to that derivated project's maintainers instead

**Comment by barbudreadmon** [comment]
Thanks for the report, some games won't add credits if the coin input is hold for too long, and that's what was happening here.
It'll be ok with https://github.com/finalburnneo/FBNeo/commit/05357096276cf1fae4d914a96030f65212c628d7

**Comment by royfokk** [comment]
Thank you for your elaboration.

**Comment by royfokk** [comment]
It works well now
