### ISSUE TITLE
Problem with shaders in vertically scrolling games

### ISSUE THREAD

**Issue by KamiLordus** [libretro/FBNeo#1036]
I tested many games where the image is scrolled vertically. Some of them have a problem with the correct display of shaders
For example:
1942
Commando
Strikers 1945 II
Strikers 1945 III
DonPachi
GunBird
Mercs

I will add that I checked on mame git core and there is no problem there.

crt-lottes.slang:

incorrect shader
![1](https://user-images.githubusercontent.com/123302593/216395249-66cbb4cd-866f-45e9-a725-bd249b833920.png)

correct shader using vertical mode
![2](https://user-images.githubusercontent.com/123302593/216395299-799a1c55-490a-4a9c-a242-104a79068558.png)

crt-geom.slang:

incorrect shader

![3](https://user-images.githubusercontent.com/123302593/216395808-97459de5-eb3a-42e7-9dad-7930a9c3b5ff.png)

correct shader using vertical mode

![4](https://user-images.githubusercontent.com/123302593/216396007-6cddb3df-8c19-415e-9928-6843f9226e00.png)

**Comment by barbudreadmon** [comment]
What is incorrect ?

**Comment by barbudreadmon** [comment]
> I checked on mame git core and there is no problem there.

It seems to me like you are misunderstanding something, read https://github.com/libretro/mame/issues/261

**Comment by KamiLordus** [comment]
This is exactly what I mean - scanlines rotation.
If I understand correctly, such a function is not available in FB neo?

**Comment by barbudreadmon** [comment]
>If I understand correctly, such a function is not available in FB neo?

For vertical games, FBNeo is displaying the scanlines vertically, which is the correct direction. MAME has broken shaders on vertical games.

**Comment by barbudreadmon** [comment]
Since this is the correct behavior and not a bug, i'll be closing soon, except if you have other questions.
Note that the aspect ratio is incorrect in your screenshots, maybe you'll want to check [the FAQ about this](https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#vertical-games-dont-work-properly-why-)

**Comment by KamiLordus** [comment]
I've read a lot of posts on the RA forum about this and there's no point in digging :)
I think you can close the topic.

**Comment by barbudreadmon** [comment]
>I've read a lot of posts on the RA forum about this

Be careful about what you read on RA forum, i remember someone was trolling about this, actually that's why i decided to clarify the situation by opening https://github.com/libretro/mame/issues/261
