### ISSUE TITLE
ga2: missing Test button

### ISSUE THREAD

**Issue by eadmaster** [libretro/FBNeo#1037]
Golden Axe 2 seems missing the Test button.
I am able to enter the service menu by holding the Start key, select the entries with the Service button, but there is no way to confirm a selection since the Test button is missing.

![ga2-230205-070200](https://user-images.githubusercontent.com/925171/216804552-471c2799-a1bc-46ec-add4-67a6deb9f4bf.png)

Also for some reason the nvram created with MAME is not compatible with Fbneo: I've enabled freeplay in Mame but it is not effective in Fbneo after this:
````
cp ~/mame/nvram/ga2/mainpcb_eeprom ~/.config/retroarch/saves/fbneo/ga2.nv
````

**Comment by barbudreadmon** [comment]
You enter that menu by "pressing" the Test button, meaning Test = hold start

**Comment by eadmaster** [comment]
> meaning Test = hold start for you

ok, it works fine. I assumed there was a separate Service button like in MAME:

![Screenshot_20230206_015912-1](https://user-images.githubusercontent.com/925171/216858639-e94c6801-6f08-4162-88ae-5a590fabfc66.png)


> Yes, nvrams aren't compatible between emulators.

Wasn't the purpose of [this commit](https://github.com/libretro/FBNeo/commit/44fabff39fea401297246fe8ad9f0c9aec2658fb)?

([linked issue](https://github.com/finalburnneo/FBNeo/issues/759))

**Comment by barbudreadmon** [comment]
>Wasn't the purpose of [this commit](https://github.com/libretro/FBNeo/commit/44fabff39fea401297246fe8ad9f0c9aec2658fb)?
>
>(https://github.com/finalburnneo/FBNeo/issues/759)

No, this was told multiple times in that linked issue : even after removing the compression, nvrams won't necessarily be compatible. 
Furthermore, only the .fs files were concerned by this commit.
