### ISSUE TITLE
Can't jump forward in drgnbstr 

### ISSUE THREAD

**Issue by royfokk** [libretro/FBNeo#1038]
It does not jump, when you press up + left/right buttons simultaneously.

**Comment by barbudreadmon** [comment]
It seems left/right must be pressed prior to up if you want to jump forward, i'm getting the same behavior in MAME so i don't think it's an emulation bug.

**Comment by royfokk** [comment]
You are right，thank you for your elaboration.
FYI, https://strategywiki.org/wiki/Dragon_Buster/Gameplay
