### ISSUE TITLE
Error compiling with mingw64 in windows

### ISSUE THREAD

**Issue by crashGG** [libretro/FBNeo#1041]
OS: win10 x64

build tools:
MinGW GCC 11.2.0
MinGW GNU binutils 2.37
MinGW lld 13.0.0
MinGW Python 3.9.7
MinGW CMake 3.22.1
MSYS2 GNU make 4.3

Issue:

When I compile with mingw64 in windows, I get an error at this step

![20230313165335](https://user-images.githubusercontent.com/80488411/224722333-a039ea56-f74b-49eb-bfe0-c8e7180909a0.png)
How can I go on?

**Comment by barbudreadmon** [comment]
No idea, i am not a windows user, all i can tell is that building this core on windows works, otherwise it wouldn't be available from the [buildbot](http://buildbot.libretro.com/nightly/).
I suppose your environment isn't set properly, hard to say more with so few information, you aren't even mentioning the command you are using to build this.

**Comment by crashGG** [comment]
> No idea, i am not a windows user, all i can tell is that building this core on windows works, otherwise it wouldn't be available from the [buildbot](http://buildbot.libretro.com/nightly/). I suppose your environment isn't set properly, hard to say more with so few information, you aren't even mentioning the command you are using to build this. You should be using something like this :
> 
> ```
> make -j4 -C src/burner/libretro/ platform=win CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++
> ```

I used the parameters you provided to compile, after a long wait, the prompt now is this:
fatal: not a git repository (or any of the parent directories): .git
cut: the delimiter must be a single character
Try 'cut --help' for more information.
expr: syntax error: unexpected argument '-dumpversion'
# Use a temporary file to hold the list of objects, as it can exceed windows shell command limits
process_begin: CreateProcess(NULL, # Use a temporary file to hold the list of objects, as it can exceed windows shell command limits, ...) failed.
make (e=2): The system can not find the file specified.
makefile:745: recipe for target 'fbneo_libretro.dll' failed
make: *** [fbneo_libretro.dll] Error 2

**Comment by barbudreadmon** [comment]
Your environment seems uterly broken, i can't help you.

**Comment by crashGG** [comment]
https://stackoverflow.com/questions/33674973/makefile-error-make-e-2-the-system-cannot-find-the-file-specified
Through this document, I added the running path to make.exe. Now the problem is solved.
