### ISSUE TITLE
wbml: if hiscore is enabled, the file wbml.hi causes the game to launch with "ROM 1 ERROR"

### ISSUE THREAD

**Issue by estefan3112** [libretro/FBNeo#1045]
wbml (Wonder Boy In Monster Land Japan) launches and writes a file wbml.hi, if hiscores are enabled in the Core Options. Upon next start, the game stops with "ROM 1 ERROR". Deleting the file wbml.hi lets the game launch again.

**Comment by estefan3112** [comment]
PS: The obvious workaround to disable Highscore support in game-specific core options works fine.

**Comment by barbudreadmon** [comment]
Oops, sorry for the late answer, i didn't notice your report.
I'll take a look at this soon.

Btw, i recommend using [upstream repo](https://github.com/finalburnneo/FBNeo) whenever you report an issue, it's easier to have everything centralized there, and more devs check it.

**Comment by barbudreadmon** [comment]
I think this might be some kind of typo in hiscore.dat, the following line seems suspicious as `0x072f` is a rom address and not a ram address (rom being read-only, it can't contain hiscores) : 
https://github.com/libretro/FBNeo/blob/6d220068a229a75077d5ca106de85c1e7667776b/metadata/hiscore.dat#L15474

Could you check if hiscores for this game persist properly after removing that line and deleting wbml.hi again ?

**Comment by estefan3112** [comment]
Confirmed! ROM error gone after deleting this single line. Still need to check whether hiscores work now...

**Comment by estefan3112** [comment]
Add-on: I am not firm enough in Github to create a pull request, otherwise I would do so, apologies :).

**Comment by barbudreadmon** [comment]
>because hiscore.dat is provided in this repo

This is just a file the retropie people asked me to mirror from https://highscore.mameworld.info/ for the sake of convenience. You'd be using exactly the same file if you were running our standalone emulator.

**Comment by barbudreadmon** [comment]
I'll reopen as a reminder that i need to report this to hiscore.dat's author

**Comment by estefan3112** [comment]
I wrote an e-Mail as offered on the website, and I pointed to this issue here with a direct link.
