### ISSUE TITLE
What's the purpose of turning off large-file support in Makefile?

### ISSUE THREAD

**Issue by wn2000** [libretro/FBNeo#1047]
The following line seems to turn off LFS:

https://github.com/libretro/FBNeo/blob/e7a6ea32228ce34eb116137bfcf0ff1472d33d52/src/burner/libretro/Makefile#L523

What's the purpose of doing that?
It seems to still work fine with LFS on (which I think is the default nowadays).
Tested on arm32 build using a RK3328 sbc.

**Comment by barbudreadmon** [comment]
What's the purpose of turning on LFS ? FBNeo doesn't support any romset larger than ~100MB.

>Tested on arm32 build using a RK3328 sbc.

Did you also test on apple devices, android devices, consoles, ... ? I think it used to be turned off due to compatibility issues.

**Comment by wn2000** [comment]
> What's the purpose of turning on LFS ? FBNeo doesn't support any romset larger than ~100MB.
Well just think it's odd that it was explicitly turned off.
I was building using batocera's buildroot environment, and it throws tons off warnings of `_LARGEFILE64_SOURCE redefined` as the default env set it to on.

> Did you also test on apple devices, android devices, consoles, ... ? I think it used to be turned off due to compatibility issues.
Obviously no. I guess no biggie just want to know the reason in case anyone actually knows.
Looks like that was put in 4 years ago and the reason may be lost.
I'll just make a local patch to silent the warnings.

**Comment by wn2000** [comment]
> FBNeo doesn't support any romset larger than ~100MB.

Just curious, why is that?

**Comment by barbudreadmon** [comment]
>why is that?

This is just how romsets are ? I'm not sure i understand the meaning of your question.

**Comment by wn2000** [comment]
Ahhh I thought you mean there's a hard limit of 100MB somewhere.

So basically there's no such romset that is larger than 100MB.

**Comment by barbudreadmon** [comment]
>So basically there's no such romset that is larger than 100MB.

Indeed, and i don't think enabling LFS makes much sense in emulation: even in the case of larger games, it would most likely be dvd dumps that you wouldn't want to zip anyway.
