### ISSUE TITLE
warriorb stuck on loading tilt screen

### ISSUE THREAD

**Issue by RickDangerousPi** [libretro/FBNeo#1049]
**Rules and recommendations**
- don't request support for currently unsupported hardware (arcade boards, consoles and computers)
- try to provide as much information as possible (screenshot, savestate, platform, settings, ...)
- make sure it happens with our latest official build from https://github.com/finalburnneo/FBNeo/releases/tag/latest
- any issue on derivated projects that doesn't happen with our latest official build must be reported to that derivated project's maintainers instead

raspberry pi4
retropie 4.8
fbneo commit 1bb6297c63d32c83045be0e0dd6f04ded9e13c71
game warriorb.zip
when loading game it shows the tilt loading screen but does not get any further.

**Comment by barbudreadmon** [comment]
fixed with https://github.com/finalburnneo/FBNeo/commit/a614b5a420c71e9715fbef59118d8a513d5711e1
