### ISSUE TITLE
joyfulr - control issue

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/FBNeo#105]
The game somehow has some kind of issue regarding the control scheme used. Currently in the FBNeo core, the left/right movement and the hand control used for grabbing foodstuffs are unified, making this game impossible to score points in.

**Comment by barbudreadmon** [comment]
Fixed, however i still can't grab food with the hand, is it a bug or am i misunderstanding something about this game ?

**Comment by arnoldsecret** [comment]
game's flagged as using two joysticks on MAME2003+.

**Comment by barbudreadmon** [comment]
as i said, it's fixed, it's just that the hand isn't grabbing anything, just passing through food and other stuff

**Comment by dinkc64** [comment]
It's a weird and nice game from Japan :)
Let me explain:
first, you move the hand out to get the food, but you must move it back towards the car to "grab" food.
now you must put the garbage into the waste basket.  
Ok, have fun - its hard as **** :)
