### ISSUE TITLE
Input remapping does not work.

### ISSUE THREAD

**Issue by jason-oliveira** [libretro/FBNeo#1050]
In FBNeo, when using default controls, everything works fine. When you decide to remap buttons is when things start going horribly, horribly wrong. Buttons stop working completely until the remap file is cleared.

OS Tested: Linux (Gentoo)
Device used 8BitDo SN30 Pro (Xinput mode)
Controller Drivers used: udev, sdl2
Build tested: latest from buildbot

**Comment by barbudreadmon** [comment]
Whatever issue you may have, it's not a core issue, remapping is not handled internally by cores.

Note that i'm using Gentoo Linux myself and i'm not experiencing any problem when remapping.

**Comment by barbudreadmon** [comment]
I'll be closing since there hasn't been activity for a while. I hope you figured out your problem.
