### ISSUE TITLE
Translucent explosions and various other graphics being translucent in progear and prehistoric ilse 2 for the current version of final burn neo retroarch

### ISSUE THREAD

**Issue by Ejucio** [libretro/FBNeo#1056]
The game is prehistoric ilse 2, the os is windows 10, it's the version of retroarch I downloaded yesterday (whatever that version number may-be).
 And the issue is that even after creating a brand new non merged rom set, this game and progear keep having the issues where explosions look translucent that building you saw in the screenshot with the dinosaur next to it is also translucent 
![RDT_20230924_1456063597776943864476077](https://github.com/libretro/FBNeo/assets/145719552/fac7234f-2129-4e23-83e2-8655535fb8ac)
and there's basically nothing but a literal ghost of the  player ship. 
I've had this problem pretty much every time is it cuz I'm downloading individual roms?

Is it cuz I'm using the nightly ROMSET? Am I better off updating the roms of the version 1.0.0.2 version of fbneo?

**Comment by barbudreadmon** [comment]
It looks like you installed the .bld files in `SYSTEM_DIRECTORY/fbneo/blend`
Don't, those files add translucent effects that don't exist on real hardware, and they break stuff more often than they are useful.

**Comment by Ejucio** [comment]
> It looks like you installed the .bld files in `SYSTEM_DIRECTORY/fbneo/blend` Don't, those files add translucent effects that don't exist on real hardware, and they break stuff more often than they are useful.

My brother I've not even the slightest fucking clue what a bld is but so what then? 
I think that might be something in the bios right the bios that I have to add to the system folder is that a part of the problem? 
Help me understand what  you just said

**Comment by barbudreadmon** [comment]
Language !!!

There is a folder at `SYSTEM_DIRECTORY/fbneo/blend/` ([see how to locate your `SYSTEM_DIRECTORY`](https://docs.libretro.com/library/fbneo/#where-is-system_directory)).

You copied a bunch of .bld files to that folder, **DON'T**.

I can't provide a better explanation, so i'll close.
