### ISSUE TITLE
hotgm4ev （TAISEN HOT GIMMICK 4 EVER [JAPAN]）cant be controlled!

### ISSUE THREAD

**Issue by wings110** [libretro/FBNeo#1057]
build [FBNeo] core for lakka to switch but hotgm4ev （TAISEN HOT GIMMICK 4 EVER [JAPAN]）Out of control，Pressing the left stick will not bring up the control menu，Opening the mahjong mask is still uncontrollable，I try
 to use the core mame2013-plus Pressing the left stick will show the control menu,but only run hotgm3,not work for hotgm4.
It may be that there is a problem with some control code.

**Comment by barbudreadmon** [comment]
mahjong games require a keyboard, we use the same keys as MAME, which are listed at https://docs.mamedev.org/usingmame/defaultkeys.html#default-mahjong-and-hanafuda-keys

**Comment by wings110** [comment]
> 您似乎正在尝试使用游戏手柄玩麻将游戏。
> 
> 它们需要键盘，我们使用与 MAME 相同的键，这些键列在https://docs.mamedev.org/usingmame/defaultkeys.html#default-mahjong-and-hanafuda-keys
> 
> 我认为 Retroarch 允许将键盘按键重新映射到游戏手柄，但我不是这方面的专家，如果您需要信息，您应该在他们的论坛上询问。请注意，这可能是浪费时间，因为无论如何您都无法将 2 个按钮（硬币 + 开始）+ 19 个键盘键映射到游戏手柄。
> 
> 编辑：另请注意，在核心中使用键盘时，您可能需要启用 Retroarch 的“游戏焦点”，否则 Retroarch 的快捷键将会妨碍



> 您似乎正在尝试使用游戏手柄玩麻将游戏。
> 
> 它们需要键盘，我们使用与 MAME 相同的键，这些键列在https://docs.mamedev.org/usingmame/defaultkeys.html#default-mahjong-and-hanafuda-keys
> 
> 我认为 Retroarch 允许将键盘按键重新映射到游戏手柄，但我不是这方面的专家，如果您需要信息，您应该在他们的论坛上询问。请注意，这可能是浪费时间，因为无论如何您都无法将 2 个按钮（硬币 + 开始）+ 19 个键盘键映射到游戏手柄。
> 
> 编辑：另请注意，在核心中使用键盘时，您可能需要启用 Retroarch 的“游戏焦点”，否则 Retroarch 的快捷键将会妨碍



> It looks like you are trying to play mahjong games with a gamepad.
> 
> They require a keyboard, we use the same keys as MAME, which are listed at https://docs.mamedev.org/usingmame/defaultkeys.html#default-mahjong-and-hanafuda-keys
> 
> I think retroarch allows to remap keyboard keys to gamepad, but i'm not an expert on this, you should ask on their forum if you need information. Note that it's probably a waste of time since you can't map 2 buttons (coin + start) + 19 keyboard keys to a gamepad anyway.
> 
> Edit: also note that you might need to enable retroarch's "game focus" when using a keyboard in cores, otherwise retroarch's shortcuts will get in the way

I don't want to play mahjong games with a controller. I want to map virtual buttons to touch the game through a mask, but virtual mahjong button touch doesn't work. The mame2013 plus core can run hotgm3 through a mask virtual button, but it cannot run hotgm4ev. The FNEO core can run hotgm4ev, but it cannot be controlled through a mask virtual button The difference between mame2013 plus and FNEO is whether it can be controlled. I think the difference lies in whether it can pop up the control menu by pressing the left joystick

**Comment by barbudreadmon** [comment]
>I think the difference lies in whether it can pop up the control menu by pressing the left joystick

That "control menu" is called the MAME OSD, if you want the MAME OSD, use a MAME core.

I'll be closing, you already got your answer : mahjong games are mapped to keyboard.

**Comment by barbudreadmon** [comment]
You might be interested in following https://github.com/libretro/RetroArch/issues/15772

**Comment by wings110** [comment]
> You might be interested in following [libretro/RetroArch#15772](https://github.com/libretro/RetroArch/issues/15772)
[
](https://neo-source.com/index.php?topic=3834.0)  The same problem with this ,how to fix ?

**Comment by barbudreadmon** [comment]
Locking as you already got your answer.
