### ISSUE TITLE
Spinner functionality in Puzzloop not working

### ISSUE THREAD

**Issue by riggles1** [libretro/FBNeo#1058]
Puzzloop has spinner/dial support, the way spinners work with emulation is through the mouse device (physical hardware spinners map as mouse devices in windows etc). To confirm I tried it in the mame core with working spinner input there. FBN emulates this game more accurately however.

FBNeo has mouse support ("ball only" and "full" mode), however it doesn't work for this game.

**Comment by barbudreadmon** [comment]
It should be ok with https://github.com/finalburnneo/FBNeo/commit/72504fe3769f67649314f4847bc9010cfd664817. As a general rule, i recommend reporting issues directly upstream.

**Comment by riggles1** [comment]
Appreciate it! You're right, for some reason I was thinking it was something particular with this fork. Thanks! : D
