### ISSUE TITLE
Analog to digital binds button 3 instead of mapping analog to digital

### ISSUE THREAD

**Issue by vgambit** [libretro/FBNeo#106]
Not sure how to elaborate on this. I'm using RetroArch 1.7.7 on Switch, and the latest version of the FinalBurn Neo core. If I disable Analog to Digital, I can manually assign the directions, and I suppose that works fine as a workaround. But if I enable it, either on the left or right analog, trying to use it at all simply presses button 3 instead. This issue does not happen with FB Alpha.

**Comment by barbudreadmon** [comment]
"Analog to Digital" is a frontend feature, the core can't interact with it, furthermore it's an ugly workaround which existed when remapping analog to digital wasn't implemented yet.
As far as i'm concerned, that's not a core issue and this feature should be removed from the RA frontend, so i'll close. If you really want the issue to be investigated, open it in its rightful place : https://github.com/libretro/RetroArch/issues
