### ISSUE TITLE
Mouse movement not recorded in Major Havoc, only mouse buttons with "Mouse Full" option selected

### ISSUE THREAD

**Issue by tempt187** [libretro/FBNeo#1060]
Running on Windows 11, it appears that major havoc will only respond to mouse buttons for fire/shield, not movement (any side to side action of the mouse/spinner is expected behavior) and only the joystick left/right movement will move the character.

Tested on c7498a3

**Comment by barbudreadmon** [comment]
This is not a bug with the libretro port, please post this upstream (https://github.com/finalburnneo/FBNeo)
Tbh, even the libretro-only bugs should be reported upstream.

**Comment by tempt187** [comment]
Will do, thank you for the clarification.

**Comment by barbudreadmon** [comment]
Support for mhavoc's analog controls was added upstream with https://github.com/finalburnneo/FBNeo/commit/5604bf6aab8e1561f5b1f4e66f253e639b751278
