### ISSUE TITLE
On esd games (multi champ deluxe,tang tang,head panic,deluxe 5) cant find the select button inside the service menu

### ISSUE THREAD

**Issue by kounabi22** [libretro/FBNeo#1066]
On esd games (multi champ deluxe,tang tang,head panic,deluxe 5) cant find the select button inside the service menu.
try many compination nothing.
on mame its working but on fbneo on batocera rpi5 nothing.

**Comment by barbudreadmon** [comment]
Fixed with https://github.com/libretro/FBNeo/commit/484962863ab84189dca218b02197575cd266a537
There was no need to open a separate issue from https://github.com/finalburnneo/FBNeo/issues/1680
