### ISSUE TITLE
I encountered a problem when I added romset

### ISSUE THREAD

**Issue by 2494654220** [libretro/FBNeo#1067]
I tried to add a "KOVSH" HACK version "KOVDF" by myself. I first wrote RomSet in "D_PGM.CPP", which could not run after testing. Later, I imitated other romsets and added to "DriverList.h"
"Drv Burndrvkovdf;" "& Burndrvkovdf," "{" kovdf "," pgm/d_pgm.cpp "},"
![QQ1](https://github.com/libretro/FBNeo/assets/129390910/d76cdcbf-163c-4216-8466-3b5e553930ed)
![QQ2](https://github.com/libretro/FBNeo/assets/129390910/22ff44f2-61d9-4cdd-9e37-61eaff61884c)
![QQ3](https://github.com/libretro/FBNeo/assets/129390910/0b3df3ab-cda9-4872-8b03-cb8b55124e16)

When I compiled, I encountered a problem, and lacking a reference to "Burndrvkovdd", how should I quote?
![QQ图片20240224003224](https://github.com/libretro/FBNeo/assets/129390910/47f05265-9ff3-49c8-88a8-887536053d13)

**Comment by barbudreadmon** [comment]
https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#building-this-core-manually

**Comment by 2494654220** [comment]
thanks for the reply! I build fbneo_librtre, the command used by Emuelec is:
Project = amlogic-CE Device = amlogic-ng Arch = AARCH64 Distro = Emuelec ./scripts/build FBNEOOO
In addition, can "Make -J5 -C SRC/Burner/Libretro Clean" be cleaned up?

**Comment by 2494654220** [comment]
thanks for the reply! I build fbneo_librtre, the command used by Emuelec is:
Project = amlogic-CE Device = amlogic-ng Arch = AARCH64 Distro = Emuelec ./scripts/build fbneo
In addition, can "Make -J5 -C SRC/Burner/Libretro Clean" be cleaned up?

**Comment by 2494654220** [comment]
![QQ图片20240224082559](https://github.com/libretro/FBNeo/assets/129390910/a7ab2b30-952c-4297-beb3-9211cbf02e8e)

**Comment by barbudreadmon** [comment]
Linux is case-sensitive.
make is case-sensitive.
makefiles are case-sensitives.

You can't add caps everywhere.

You got the correct instructions, whether you follow them properly or not is beyond my capabilities.
Closing.
