### ISSUE TITLE
Adding a new button macro to Neo Geo games

### ISSUE THREAD

**Issue by jhpgcj** [libretro/FBNeo#1068]
Based on a similar issue posted in the Geolith repository (https://github.com/libretro/geolith-libretro/issues/1), could a new button macro be added to Neo Geo games? I'd like to suggest the inclusion of **buttons B+C**.

Similar reasoning as posted in Geolith's repo, but here's a recap in favor of B+C:
- Widely used in the whole Fatal Fury series;
- Considerably used in the whole Art of Fighting series;
- Considerably used in the whole Samurai Shodown series;
- Used in stray games from bigger series (like King of Fighters 2002);
- Used even in less popular games, like Savage Reign and Ninja Master's.
- Can be pressed along the D button to become B+C+D, but the inverse isn't possible: B+C+D macro won't work if only B+C is required.

Thank you for your time and attention.

**Comment by barbudreadmon** [comment]
https://docs.libretro.com/library/fbneo/#why-is-my-favorite-combo-button-not-available

**Comment by barbudreadmon** [comment]
>Just be mindful that there are rationale over any choice, and setting things in stone because of a single event of the past in which few people participated is one reason there might be still people suggesting changes.

To answer your other post, this is exactly why i regret implementing macros considering the current limitation of libretro. Any arbitrary choice will cause some people to be in disagreement, and yours is not better than others. 

This is not being childish, i'm just not interested in dealing with complaints about things i can't do anything about, so removing the root cause of the complaints is probably the most logical move.

**Comment by barbudreadmon** [comment]
@carmiker additionally, i know someone on libretro's discord was talking about removing that limitation a few months ago, i don't know if it led to any further development though.

**Comment by jhpgcj** [comment]
> > Bro, take it easy. Don't need to get so worked up over my suggestion, to the point of coming over to a different repo to complain, I didn't mean to offend or anything. If you didn't like it, just say "nah, I won't do it", but don't try to make drama by saying in the FAQ "no more discussion or I'll remove them". That's a very childish thing to do. If it's bothering you that much, just remove the macros all together, not that it will do your emulator any good. Just be mindful that there are rationale over any choice, and setting things in stone because of a single event of the past in which few people participated is one reason there might be still people suggesting changes.
> 
> To answer your other post, this is exactly why i regret implementing macros considering the current limitation of libretro. Any arbitrary choice will cause some people to be in disagreement, and yours is not better than others. Even the 3xPunch & 3xKick in street fighter ended up causing disagreements.
> 
> This is not being childish, i'm just not interested in dealing with complaints about things i can't do anything about, so removing the root cause of the complaints is probably the most logical move.
> 
> And i was not "complaining" in the other post, i was simply stating that not all people are actually happy with the current combos, since you linked that issue to me and there seemed to be a misunderstanding about that.

That's completely fine, really. No ill feelings. After all, it's your emulator; your time, effort and code into it. No matter what you do, no matter your reasoning, you're free to do whatever you want. I'm not complaining and even understand your point. I posted a suggestion, not a demand.

However, it wasn't in good taste going over to a third party to cause annoyance. Glad the conversation continued here. The issue I linked was already closed and resolved, used solely to illustrate my rationale, not as a proof of righteousness, no need to be so on the edge. You weren't required to comment there, and it gave away the impression that you were disgruntled because a dev chose to do things differently than you.

Anyway, if some issues bother you, I advise linking the FAQ whenever a new issue is about to be created, or just a quick "do and don't" when posting something. Better communication might spare you from some annoyance.

Best regards.

**Comment by barbudreadmon** [comment]
>You weren't required to comment there, and it gave away the impression that you were disgruntled because a dev chose to do things differently than you.

There was a misunderstanding about FBNeo in that issue you linked. I don't need your permission to comment about it. The only thing unrequired in that issue was your extremely rude behavior.

>Anyway, if some issues bother you, I advise linking the FAQ whenever a new issue is about to be created, or just a quick "do and don't" when posting something. Better communication might spare you from some annoyance.

You mean that same message telling you any issue should be opened in our upstream repo instead of this one ? Yes, i'm sure it would have made a huge difference with you.
