### ISSUE TITLE
Request to join the PGM combination button

### ISSUE THREAD

**Issue by 2494654220** [libretro/FBNeo#1069]
I noticed that NEOGEO has supported the combination key, but PGM has not yet, requests to add AB, ABC combination key for PGM, or tell me where to modify.

**Comment by barbudreadmon** [comment]
Sorry, i won't make the mistake of adding more macros as long as [the limitation mentioned in this core's documentation](https://docs.libretro.com/library/fbneo/#why-is-my-favorite-combo-button-not-available) exists.

**Comment by 2494654220** [comment]
Can you tell me how to achieve it? Where to add? I believe it is just a few lines of code for you

**Comment by barbudreadmon** [comment]
You can find an example of how it was done for neogeo at https://github.com/libretro/FBNeo/commit/97bd70507bac08743736de4d591eb596279781c0

**Comment by 2494654220** [comment]
Thank you so much
