### ISSUE TITLE
asterix - stuck at diagnostic

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/FBNeo#107]
![asterix-190719-174127](https://user-images.githubusercontent.com/41223243/61526201-8bba7580-aa4c-11e9-819e-240dc4954e04.png)

ROMs confirmed to be the latest.

EDIT: G.I. Joe also has the same issue.

**Comment by barbudreadmon** [comment]
Those 2 games are working properly, maybe something about your settings ? Are you using specific core options, or maybe rewind/readahead ? It might be a good idea to try deleting eeproms for those games too.

Also, what's your platform ?

**Comment by arnoldsecret** [comment]
even after deleting the eeprom it seems that it fails to detect that 17b's ok.

**Comment by barbudreadmon** [comment]
please answer all my questions, or i won't be able to help.

**Comment by arnoldsecret** [comment]
Windows 8.1 x64.

**Comment by barbudreadmon** [comment]
I can't reproduce this issue on any of the platforms i tried, including windows, i don't have a windows 8.1 though. Maybe we are overlooking something, could you please post your logs ?

**Comment by dinkc64** [comment]
arnoldsecret,
The error means something is wrong with the eeprom.
check your romsets and make sure asterix.nv / gijoe's er5911.7d exists in them.  Each file should be 128 bytes in size and asterix with a crc32 of 490085c8 and gijoe's with crc32 of a0d50a79 - if you have made corrections to your romset(s), delete the eeprom/nvram file(s) for the games.
best regards,
- dink

**Comment by arnoldsecret** [comment]
fixed now.
