### ISSUE TITLE
I encountered a strange problem

### ISSUE THREAD

**Issue by 2494654220** [libretro/FBNeo#1070]
![20240229192455](https://github.com/libretro/FBNeo/assets/129390910/87eb3718-e04c-417d-bc9d-554ea89eddce)
When this interface appears, all keys are prohibited from using
Unable to exit
Can only disconnect the power supply

**Comment by barbudreadmon** [comment]
I don't know, i can't reproduce this, it looks like a setup issue.

**Comment by 2494654220** [comment]
> 我不知道，我无法重现这个，它看起来像是一个设置问题。

I turned over the menu option, but I didn't find the relevant settings

**Comment by MrFriedRice** [comment]
The menu cannot be accessed whenever there is an issue with the ROM, such as a mismatched ROM CRC or inconsistent size, triggering this page.

**Comment by barbudreadmon** [comment]
>The menu cannot be accessed whenever there is an issue with the ROM, such as a mismatched ROM CRC or inconsistent size, triggering this page

As i said, i can't reproduce this, meaning i can access the menu.
Furthermore pressing any button when this white screen occurs will trigger the libretro `RETRO_ENVIRONMENT_SHUTDOWN` api call, which as its name suggest, asks retroarch to shutdown the core.

In the first place, retroarch hotkeys are a frontend feature, meaning backends (cores) are totally unaware of them, meaning it's a setup issue at best and a retroarch issue at worst.
