### ISSUE TITLE
Is it possible to add some features from the FBNEO WINGUI version to libretro?

### ISSUE THREAD

**Issue by wolflink2021** [libretro/FBNeo#1071]
For example, the DIP Code select feature in the pgm driver, some unofficial games require this option to run.
There's also IPS patching and ROMDATA, both great features.

**Comment by barbudreadmon** [comment]
No

**Comment by 2494654220** [comment]
> 不需要

The current use of IPS is too complex, and we hope to optimize it

**Comment by barbudreadmon** [comment]
Long story short, this stuff is not only too complex but also tightly integrated with UI elements which aren't exacty something that could be easily ported to a libretro environment. 
Hence why the only method available to launch hacks is [this one](https://docs.libretro.com/library/fbneo/#how-can-i-run-that-romhack-i-found).
