### ISSUE TITLE
Switching games with the FBNEO core crashes the system

### ISSUE THREAD

**Issue by MrFriedRice** [libretro/FBNeo#1072]
When using the fbneo core on Nintendo Switch, switching games results in a crash (Open a game, access the menu, switch to another game, and the program crashes, returning to the Switch desktop).

In RetroArch, there's an advanced option to enable it. Then, in the core settings, there's an additional option "Restart RetroArch when loading a game". With this option enabled, the program no longer crashes when switching games.

However, it doesn't retain the game list. For example, if I'm playing the 100th game in the game list and then access the menu, the focus is no longer on the game currently being played.

I've tried many versions, including nightly, 1.17, and 1.16, but the issue persists. This problem doesn't exist in version 1.9.0. I don't want to use an older version because the older core supports only a limited number of games.

**Comment by zcf19960503** [comment]
I've tried many versions, including nightly, 1.17, and 1.16, but the issue persists. This problem doesn't exist in version 1.9.0. I don't want to use an older version because the older core supports only a limited number of games.

**Comment by MrFriedRice** [comment]
After testing, switching the game starting from version 1.16 causes errors. Versions 1.15 and earlier work fine.

**Comment by barbudreadmon** [comment]
1.17, 1.16, 1.15, 1.9, ... are retroarch versions, not FBNeo versions.
If your issue is directly related to the retroarch version you are using, then in all likeliness it's not a FBNeo bug.
In the first place all that stuff you are talking about with advanced settings and such are retroarch settings.

**Comment by barbudreadmon** [comment]
To summarize, i recommend opening an issue in the correct repo : https://github.com/libretro/RetroArch
