### ISSUE TITLE
Wrong files sizes for Galactic Storm (Japan) [folder: galastrm - size: 12mb]

### ISSUE THREAD

**Issue by CaptainHIT** [libretro/FBNeo#1074]
Galactic Storm (Japan) [folder: galastrm - size: 12mb]
missing rom: c99-17.bin [size: 260] [CRC32: 81d55be5]
missing rom: c99-18.bin [size: 260] [CRC32: eca1501d]
missing rom: c99-20.bin [size: 260] [CRC32: 5d527b8b]
missing rom: c99-24.bin [size: 260] [CRC32: a0ec9b49]
missing rom: c99-25.bin [size: 260] [CRC32: d7cbb8be]
missing rom: c99-26.bin [size: 260] [CRC32: d65cbcb9]

These are wrong sizes of the files. Must be corrected to:
rom name="c99-17.bin" size="324" crc="81d55be5"/
rom name="c99-18.bin" size="329" crc="eca1501d"/
rom name="c99-20.bin" size="324" crc="5d527b8b"/
rom name="c99-24.bin" size="324" crc="a0ec9b49"/
rom name="c99-25.bin" size="324" crc="d7cbb8be"/
rom name="c99-26.bin" size="324" crc="d65cbcb9"/

**Comment by CaptainHIT** [comment]
Sorry, content got lost because of formatting, here are the real sizes of the files.
rom name="c99-17.bin" size="324" crc="81d55be5"/
rom name="c99-18.bin" size="329" crc="eca1501d"/
rom name="c99-20.bin" size="324" crc="5d527b8b"/
rom name="c99-24.bin" size="324" crc="a0ec9b49"/
rom name="c99-25.bin" size="324" crc="d7cbb8be"/
rom name="c99-26.bin" size="324" crc="d65cbcb9"/

**Comment by barbudreadmon** [comment]
This was already fixed upstream yesterday but i haven't synced the libretro port yet.

On a sidenote : 
- those files are unused and won't prevent galastrm from loading, they are only referenced for the sake of being in sync with MAME's romset.
- as told in the message when opening an issue, you shouldn't report issues in this repo.

**Comment by barbudreadmon** [comment]
>This was already fixed upstream yesterday but i haven't synced the libretro port yet.

Done now.
