### ISSUE TITLE
Good afternoon, I have a question

### ISSUE THREAD

**Issue by 2494654220** [libretro/FBNeo#1077]
I want to know how to open the core menu during the game, what code is used, and in which file?
![2557](https://github.com/libretro/FBNeo/assets/129390910/55b87daf-d4af-4ab4-83eb-d7eed19423db)

**Comment by barbudreadmon** [comment]
I don't understand your question, the only "core menu" i can think of is the one you have already opened in that screenshot.

**Comment by 2494654220** [comment]
> I don't understand your question, the only "core menu" i can think of is the one you have already opened in that screenshot, and opening it is entirely handled by retroarch. If you have questions about retroarch, i recommend you ask on their forum/github, core repos are the wrong place.
thank you
