### ISSUE TITLE
Dat information incorrect?

### ISSUE THREAD

**Issue by MageMaster69** [libretro/FBNeo#1078]
Dat located at https://github.com/libretro/FBNeo/blob/master/dats/FinalBurn%20Neo%20(ClrMame%20Pro%20XML%2C%20Neogeo%20only).dat

Does not match output of EXE for 
 mslug5bs.zip (268-p1bs.p1)
Dat:
Name : 268-p1bs.p1
Size : 6,291,456
CRC32: 6ec9bb7e

Exe:
Name : 268-p1bs.p1
Size : 6,291,456
CRC32: 8bb8c097
SHA1 : 66b5d84367ff564a02e9cfe1ef003cc4bad30f5d
MD5  : a95d9463194c3dbd3a3944e3378171ef

**Comment by barbudreadmon** [comment]
The dat file on this repo is **always** correct for the libretro core.
The libretro core is not always in sync with upstream.
