### ISSUE TITLE
FinalBurn Neo (ClrMame Pro XML, Arcade only).dat in clrmamepro

### ISSUE THREAD

**Issue by GohanSenior** [libretro/FBNeo#1079]
The last "FinalBurn Neo (ClrMame Pro XML, Arcade only).dat" is not functional with rom managers. tested with clrmamepro 4.048d and romulus.
![Capture d'écran 2024-05-07 161613](https://github.com/libretro/FBNeo/assets/42714795/7e148609-ea1f-4f79-bb59-0515745dfb48)

**Comment by barbudreadmon** [comment]
The dat file is working perfectly well with clrmamepro 4.048d. 
Whatever issue you might have is undoubtedly an issue on your side, make sure what you downloaded is the complete raw dat file.
