### ISSUE TITLE
FBNeo with graphical glitch in PGM games on libretro wii u

### ISSUE THREAD

**Issue by Zeox-Gamer** [libretro/FBNeo#1080]
All PGM games work well on the Wii U in terms of native FPS 60, but all PGM games have graphical flaws in the background of the scenes, a spectral example VG Generation has glitches in the background of the scenes, all the games are like this or worse, just the characters and their special life bars, among others, are perfect, otherwise all the games have flaws in the background scenes

for platform games they become unplayable when you don't know where to jump, as is the case with demon front

**Comment by barbudreadmon** [comment]
Any issue should be directly reported upstream at https://github.com/finalburnneo/FBNeo
