### ISSUE TITLE
Function request: Add ignore CRC detection

### ISSUE THREAD

**Issue by 2494654220** [libretro/FBNeo#1089]
Request to add the option to ignore CRC detection core and not verify CRC32 when enabled, for hack games; for IPS patches, this is a very practical feature thank you

**Comment by barbudreadmon** [comment]
https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#how-can-i-run-that-romhack-i-found-

**Comment by 2494654220** [comment]
> https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#how-can-i-run-that-romhack-i-found-
> 
> https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#how-can-i-run-that-romhack-i-found-



I know this, but it's not convenient or fast enough. Thank you

**Comment by 2494654220** [comment]
> https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#how-can-i-run-that-romhack-i-found-

I know this, but it's not convenient or fast enough. Thank you

**Comment by barbudreadmon** [comment]
>it's not convenient

That's the point. I'm not stupid enough to not understand what would happen if there was a core option making super easy to ignore crc.

**Comment by 2494654220** [comment]
ok,打扰了

> > it's not convenient
> 
> That's the point. I'd need to be seriously dumb to not understand what's gonna happen if i add a core option making super easy to ignore crc checks and load bad dumps.

Okay, sorry to bother you

**Comment by 2494654220** [comment]
> > it's not convenient
> 
> That's the point. I'd need to be seriously dumb to not understand what's gonna happen if i add a core option making super easy to ignore crc checks and load bad dumps.

Okay, sorry to bother you

**Comment by MrFriedRice** [comment]
Add an option to ignore CRC validation, which is turned off by default. Users who enable this option should be aware that errors may occur.

**Comment by barbudreadmon** [comment]
My previous answer was pretty clear, i guess i'll lock to avoid more spam about this.
