### ISSUE TITLE
Different folders for similar system files.... Why?

### ISSUE THREAD

**Issue by fastpop72** [libretro/FBNeo#109]
I have only a question... Why use two different folder names for storing .fs and .nv files and .rmp in another different folder?

All these files i think could be stored in the same folder, they have different extension.

<img width="200" alt="Immagine" src="https://user-images.githubusercontent.com/32760152/61591839-a36c3800-abcb-11e9-8feb-3625a7a4ee10.png">

**Comment by barbudreadmon** [comment]
rmp files are retroarch's business, i've no control about this. Furthermore i don't think storing your savefiles in the same place as your remap files is a good idea.

**Comment by fastpop72** [comment]
I think it's a great idea instead, so we could have all the "additional" files like remaps & nvrams together with roms in order to backup only one folder. Anyway i understand that "FinalBurn Neo" foldername  is not from the core.
