### ISSUE TITLE
bool retro_load_game always return true

### ISSUE THREAD

**Issue by Turro75** [libretro/FBNeo#1091]
I'm working on a libretro frontend and it turned out that retro_load_game always returns true even if loading failed (i.e. missing rom).

Assuming there is a reason for that, how can I understand (I mean in the code) that loading was not successful?

**Comment by barbudreadmon** [comment]
It's returning true so that an error message is displayed instead of silently closing.

>how can I understand (I mean in the code) that loading was not successful?

Through the libretro api ? I suppose you can't.

**Comment by Turro75** [comment]
ok, I'll reboot the device.
