### ISSUE TITLE
Game option overrides, dipswitches will revert to default now

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/FBNeo#113]
[With that PR](https://github.com/libretro/RetroArch/pull/9188) you can't save dipswitches as a game option override now.

How to check what's happening:
-Launch a game
-go into core options, change some dipswitches
-save a game option override and close the game
-open the config/FinalBurn Neo/game.opt into a text editor
-launch the game again: you'll see the dipswitches getting erased from your opt file
-close the game: default dipswitches are written in the opt file

So is there anyway to load the dipswitches earlier if that's the problem?

**Comment by barbudreadmon** [comment]
No, dipswitch initialization is already happening as soon as possible (i.e in `retro_load_game` since we need to know the game to initialize the dips).

**Comment by barbudreadmon** [comment]
Should be fixed with https://github.com/libretro/FBNeo/commit/bfc362f5ae9af54f89127133c50d483141b1dd8d
