### ISSUE TITLE
Highscore won't saving

### ISSUE THREAD

**Issue by 0100101000101** [libretro/FBNeo#114]
I have the latest stable version of Reteoarch (1.7.7).
I have the hiscore.dat file in system / fbneo and the hiscores option active in the Retroarch options.
I tried Ghost'n'Goblins, but hiscores are not saved.
However, in the saves folder there is the file with the extension .hi.

**Comment by barbudreadmon** [comment]
Fixed a few weeks ago, update to latest version.

**Comment by 0100101000101** [comment]
It's already updated

**Comment by barbudreadmon** [comment]
I checked, it's working, maybe you are using readahead ? readahead isn't compatible with hiscores (maybe i should mention it in the core option).

**Comment by estefan3112** [comment]
Uh oh, this is it! I struggled now so long with Highscores because I had Runahead activated. Deactivating Runahead, and Highscores save. It would be very important to mention this! Thank you - what an enlightenment after so many tries...
