### ISSUE TITLE
Midway W/T Unit frame skipping issue (all Mortal Kombat and Rampage world tour)

### ISSUE THREAD

**Issue by movisman** [libretro/FBNeo#12]
Hi there,

I noticed pitfight.zip (Pit Fighter - rev 9) is now supported in the .dat file for the pre 0.2.97.44 build of lr-fbalpha.

I am trying to move off MAME on my x86 RetroPie build and onto FBA exclusively. I only have about 120 roms, and around 5-6 roms I had to use MAME for previously now are supported on FBA, which is great. I only have less than 10 roms which aren't supported on FBA which I don't play often, so I might just drop them and only use FBA. Anyway to try these new additions out I took them from a 0.203 MAME romset - 0.2.97.44 is not yet available as far as I understand.

All of them work as expected, like Mortal Kombat 2, Asteroids Deluxe, Joust etc, etc, but Pit Fighter runs quite jerkily (consistently - it's like it's running at half the frame rate). If I swap back to MAME it is smooth again. The game works fine though without error. It is just jerky.

Is this because of the recent implementation and further optimisation is needed, or is it because i've taken the rom from a 0.203 romset and I need a different version or wait for a 0.2.97.44 romset to be available?

Just wondering if you are able to replicate the same issue as me and if you have any suggestion as to what might be wrong?

Cheers!

PS. If I should be raising this on https://github.com/barry65536/FBAlpha let me know, I only use the Libretro implementation so i'm not sure if this happens on standalone.

**Comment by arcadez** [comment]
I am trying to move off MAME on my x86 RetroPie build and onto FBA exclusively.

I dunno what MAME version he was using.?? but maybe he's compairing older cores that have
the Midway speedups vs the newer builds which do not, hence the frameskipping on low spec
systems like the Rpi.

**Comment by barbudreadmon** [comment]
romhack (aka @zxmarcos ?) never mentioned it in https://neo-source.com/index.php?topic=2666.0, seeing his dev topic he might have written it from scratch ?

**Comment by zxmarcos** [comment]
> romhack (aka @zxmarcos ?) never mentioned it in https://neo-source.com/index.php?topic=2666.0, seeing his dev topic he might have written it from scratch ?

Yes, it was written from scratch. TMS34010 VGA emulation is very WIP, but I don't know when I'll have time to work on this.

**Comment by barbudreadmon** [comment]
The frame duping issue seems to be solved !
Closing

**Comment by movisman** [comment]
Hello again..! Is it possible that this is still an issue? I'm not too sure that it's solved. I posted this issue originally quite a while back. Since then i've not really played the Midway games much, however I was playing around with latency/run-ahead settings and booted up a couple of the MK games and Pit Fighter again. I noticed they are all still pretty choppy when compared to using MAME.

Pit Fighter is really jerky, it's like it runs at 10fps. If you pause the game and advance each frame, only one in six frames does anything actually move.

Mortal Kombat 2 and 3 are also similar, but advancing each frame in pause mode, it's every one in two frames where anything happens. As a result, these two aren't terrible, but they seem to be running around half the intended framerate (25-30).

It probably affects other games as well.

I know this issue is closed off now, with the solution from last July but thought i'd put a note here while it was in my mind. Are you aware of this still being a problem with these particular units?

I am running the latest build of Libretro FBNeo, although the roms I tested with above are possibly a few months old.

Thanks!

**Comment by barbudreadmon** [comment]
No it's not, the situation is better than before but there is still frameduping, i don't mind re-opening this but tbh, if @zxmarcos doesn't find the time to finish this, those games will probably stay like this forever.

**Comment by movisman** [comment]
Hello!
Thanks for replying - appreciate it. Ah right, I thought that might be the case, but thanks for confirming. It sounds like a fix for this might take quite some time, if it ever happens at all. No worries. The MK games are definitely better than they used to be though.

I was trying to get away with just using FBA for my library when I noticed it was compatible with every game I have - but perhaps i'll revert to MAME for these select few titles.

Pit Fighter I think is based on Atari G1 Hardware - looks like the only other game to share the same hardware is 'Hydra'. Not exactly a lot. I haven't tested that one, but Pit Fighter performs particularly poorly. Not sure if this is a separate issue to the Midway skipping, or if everything is all connected.

Just wanted to let you know anyway, but I understand the situation may never change. At least if others come across the same issue they may find this thread.

Thanks a lot!

**Comment by barbudreadmon** [comment]
> Pit Fighter I think is based on Atari G1 Hardware

You should really avoid talking about it in a totally unrelated issue then, especially since the W/T Unit issue won't be looked into anymore by the current FBNeo team. At first i thought Pit Fighter was another W/T Unit game.

**Comment by movisman** [comment]
To be fair I only realised yesterday that Pit Fighter was a different board. When you initially changed the issue title back at the end of 2018 I didn't think any more of it at the time. I can raise the Atari G1 performance as a separate issue rather than discussing here.

**Comment by barbudreadmon** [comment]
Yeah, even if i already aknowledged it as a different issue, it would be better for tracking it.

**Comment by barbudreadmon** [comment]
And yeah, it's my bad for assuming it was the same issue as MK2 when you mentioned it too. As a rule for future issues you might write, i recommend writing 1 issue per game and let us decide if issues are duplicates or not. For this one i rewrote the title again to make it more clear about the games affected.

**Comment by barbudreadmon** [comment]
@movisman don't bother opening a new issue about atari g1, the fix is already on git

**Comment by movisman** [comment]
Hi,
No problem at all re: future issues. I will log stuff separately, will keep it to one issue per game. Apologies if I contributed towards any confusion with this.

As for Pit Fighter - just tested quickly after updating, and it runs far far better than it did before. Thanks for the quick turnaround and getting it sorted out.

This particular outstanding issue with MK etc, although it may not ever be fixed, is at least correct now in terms of title. I think it is every other frame that is duplicating, but like you say, this is at least an improvement on what it was like before.

Thanks a lot.

**Comment by zxmarcos** [comment]
Hello guys,

At moment I am trying to fix frame skipping bug, but I cannot promise anything...

Thanks. :-)

**Comment by barbudreadmon** [comment]
Thanks, it's really appreciated :)

**Comment by movisman** [comment]
Thank you!

**Comment by zxmarcos** [comment]
Great News, this bug is fixed in main FBNeo repository

**Comment by barbudreadmon** [comment]
@zxmarcos yes, we were testing this over irc with dink, the fix is on the libretro fork too, thanks for looking into this :).

**Comment by zxmarcos** [comment]
> @zxmarcos yes, we were testing this over irc with dink, the fix is on the libretro fork too, thanks for looking into this :).

Where is irc channel?

**Comment by barbudreadmon** [comment]
it's somehow private, ask dink by pm on forum :)

**Comment by barbudreadmon** [comment]
@zxmarcos check forum :)

**Comment by movisman** [comment]
@zxmarcos 

This is great! Thanks a lot for fixing. I just tested MK2 and MK3 and they run at full speed now!

Cheers
