### ISSUE TITLE
World Rally 2 - just 1 screen

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/FBNeo#122]
World Rally 2 only displays 1 screen.

You can still hear the audio from the 2nd player but the audio from both sides are centred the same (1 player audio is more on the left speaker, 2nd player to the right one in FBN stand-alone).

win7

**Comment by Tatsuya79** [comment]
Backfire only displays 1 screen too.

**Comment by barbudreadmon** [comment]
Side effect of the changes to the core options stuff, fixed with https://github.com/libretro/FBNeo/commit/432be943446f4a03fee905987ad2a00d5e962897
