### ISSUE TITLE
Sega Model 2 support?

### ISSUE THREAD

**Issue by Cee123** [libretro/FBNeo#124]
Hi guys, would it be possible to add Sega Model 2 support? Or is this a difficult process? I noticed MAME has like 2 games that work, and one of which runs at like 5 fps.

**Comment by barbudreadmon** [comment]
We don't accept request.

**Comment by Cee123** [comment]
Why not?

**Comment by Cee123** [comment]
On second thought, I guess that would be pretty difficult to add support for.

**Comment by twinaphex** [comment]
While this would be very cool, this would be about the hardest system you could request right now to add. 

Plus MAME's Model 2 support still being in such a rough and premature state and that being the only open source reference to go on right now even compounds the challenges in porting this to FB Neo and having it turn out well.

**Comment by Cee123** [comment]
Ohhh OK. I didn't know that. Thanks for the explanation. I heard MAME are working on it but still hasn't been much progress for a while.

It's a shame that model2 emulator for PC isn't open source. Oh well I suppose.

**Comment by barbudreadmon** [comment]
> Why not? Isn't that a feature of Github?

Because it's FBNeo team policy, we don't accept system support request, furthermore we don't do 3D systems either.

**Comment by Cee123** [comment]
Oh OK, that's fair enough then. No worries.
