### ISSUE TITLE
Golden Tee '97 (gt97.zip) give a black screen and doesn't start. Works OK in FBNeo standalone.

### ISSUE THREAD

**Issue by fastpop72** [libretro/FBNeo#133]
As stated all the Golden Tee games works but not Golden Tee '97 in libretro core.

Tested in FBNeo standalone and works OK.

**Comment by barbudreadmon** [comment]
It was actually an issue with dipswitches upstream, the dipswitch parser in the libretro port seems more sensitive to those issues. It will be fixed once i merge https://github.com/finalburnneo/FBNeo/commit/78a046d439dd38c96b68c4d699c88ed3fc1cbbff

**Comment by fastpop72** [comment]
I saw your commit, thanks!!!
