### ISSUE TITLE
Major League (mjleague.zip) BAT SWING control doesn't work.

### ISSUE THREAD

**Issue by fastpop72** [libretro/FBNeo#134]
In Major League the BAT SWING control doesn't work, i think it's an analog trigger. Tried to remap it to mouse or another button but nothing. Works OK in FBNeo standalone.

**Comment by barbudreadmon** [comment]
It seems this game expects values from `-32767` to `0` for this axis, which isn't good when using the analog triggers (it will lock values from `0` to `32767`, with or without remapping). 

@dinkc64 Maybe we could change this ? Otherwise i can probably use some hack using the game name

**Comment by dinkc64** [comment]
I'll have a proper fix soon :)

**Comment by dinkc64** [comment]
Fix is in :)

**Comment by fastpop72** [comment]
Thank you for the fix @dinkc64 but i have one question.

The BAT SWING control must be mapped mandatorily to an analog control? Because i tried to map it to a simple button and the batter doesn't swing, not even setting a different sensitivity...

**Comment by barbudreadmon** [comment]
> Because i tried to map it to a simple button and the batter doesn't swing

On standalone ? Because i updated the libretro port only a few minutes ago, now the bat swing works properly.

@dinkc64 Thanks !

**Comment by fastpop72** [comment]
@barbudreadmon yes i tried only on standalone one hour ago... when i get home i will try the libretro core and see if it works!! Thanks.

**Comment by fastpop72** [comment]
Yes, works ok on libretro core! Thanks.
