### ISSUE TITLE
Tecmo World Soccer not loading - Neo·Geo

### ISSUE THREAD

**Issue by Riddler1** [libretro/FBNeo#137]
Tecmo World Soccer is not loading. I thought the rom name changed a while ago to **tws96** but the current driver (d_neogeo.cpp) shows it as **twsoc96**.

The 9 BurnRomInfo mask rom names are correct but the game name must be wrong?

Im positive the neogeo bios file i'm using is correct as ALL my other neogeo games run with it. 

I'm using commit 019618b
rertroarch 1.7.1

Thanks!

**Comment by barbudreadmon** [comment]
The name is correct, it was renamed in 2017 (MAME 0.190).

**Comment by Riddler1** [comment]
thanks for confirming!

👍
