### ISSUE TITLE
Language selection not working

### ISSUE THREAD

**Issue by keifus2581** [libretro/FBNeo#14]
Trying to change the language to English from default of Spanish (on Lethal Enforcers ROM). Changes to English in the menu, but still displays in Spanish after reset. Any help would be greatly appreciated. Thanks!

**Comment by dinkc64** [comment]
Hi,
I found a bug in the emulation of Lethal Enforcers, A fix should be available shortly :)

**Comment by keifus2581** [comment]
Awesome to hear!!!!Thanks!

**Comment by dinkc64** [comment]
keifus2581 should be ok now :)
