### ISSUE TITLE
About running the hack game?

### ISSUE THREAD

**Issue by ji125443** [libretro/FBNeo#141]
Previous versions can run, why the current version can not run, test platform: arm's lakka, ex05re, emuelec。

**Comment by ji125443** [comment]
For example: unlimited life, no time and other modifications, the main program memory size has not changed, but changed a few bytes, can not run? The computer platform runs, and a dialogue box pops up to click OK to run.

**Comment by ji125443** [comment]
Previous CRC validation can be skipped, but now it should be CRC validation can not be skipped.

**Comment by barbudreadmon** [comment]
> CRC validation can not be skipped

Yes, people abused this.
