### ISSUE TITLE
Kernel panic when trying to load content on 3DS

### ISSUE THREAD

**Issue by iosadosd-quarto** [libretro/FBNeo#151]
FB Neo core for RetroArch 3DS (stable, 1.7.8 v2) crash the console with a kernel panic screen when trying to load content.
I tried with 1942 and Tank Force (2 player version), both scanned and verified with the latest DAT; both games start with no issues e.g. on RetroArch Win64.

**Comment by barbudreadmon** [comment]
Afaik, 3DS is one of the worst device performance-wise to run RA, so i don't expect this device to run many FBNeo games at decent speed in the first place.
The old fbalpha cores are working ?

**Comment by iosadosd-quarto** [comment]
Yeah, I figured, but having found this core in the latest release, I wanted to at least give it a try :grin: 
Never tried the old FBA cores, I'll let you know when I test it.
