### ISSUE TITLE
Wrong default analog speed for "tnzs" driver games: arknoid2, plumppop, jpopnics

### ISSUE THREAD

**Issue by fastpop72** [libretro/FBNeo#153]
Just a tweak... seems Arkanoid 2 starts with a 100% analog speed that is too fast to play with a stick.

The default speed must be trimmed down a little.

Thanks.

**Comment by fastpop72** [comment]
Same issue for other two analog controlled games of the same driver: plumppop & jpopnics

**Comment by barbudreadmon** [comment]
should be better now :  https://github.com/libretro/FBNeo/commit/748d2e8b16051ba97bd416b5dc30f41e4f6a11f5

**Comment by fastpop72** [comment]
Much better thanks! Issue solved! Problem's gone for plumppop & jpopnics too!

Many thanks!
