### ISSUE TITLE
New Qsound has distortion on high notes

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/FBNeo#16]
I'm not sure what is the state of the new Qsound renderer, but I can hear noticeable distortion that wasn't there before like in Vampire Savior 2 on digital voices (Morrigan fireball for example).

Is there something to update (like bios files)?

**Comment by dinkc64** [comment]
I tried vsav2 in the regular fbn and it sounds the same as the old one (though the new one sounds "better" if that means anything).  maybe I'm doing it wrong.
Can you please make a recording with the old and new core of the distorted sound, and attach the wav files?

**Comment by dinkc64** [comment]
This is how it sounds for me, one .wav for the new and old emulation.

[vsav2_fireball.zip](https://github.com/libretro/FBNeo/files/3204979/vsav2_fireball.zip)

**Comment by barbudreadmon** [comment]
I played vsav2 a bit, i couldn't hear any distortion either.

**Comment by Tatsuya79** [comment]
I'm on studio monitors on this PC, so I certainly hear high notes more than on a standard setup.
I did some comparisons and I get that similar distortion on FBNeo stand-alone Dink posted on the forums and also in latest MAME (default, I don't see an option for LLE).

This is a sample from vsav2 soundtest (SE 0232) FBA/FBNeo cores in RA:
[vsav2_hahaha.zip](https://github.com/libretro/FBNeo/files/3206776/vsav2_hahaha.zip)

So perhaps that's just how it is now with a more accurate rendering and that qsound would need a lowpass filter to avoid those ear piercing slightly distorted notes like with megadrive or some yamaha chips.

**Comment by barbudreadmon** [comment]
Let's tag @superctr about this ? He might know more about this, or he might be interested by the feedback ?

**Comment by dinkc64** [comment]
the new vsav2 samples clearly sound better (higher fidelity) than the old.  Though the old does sound like there is some sort of filter on it,  Though TBH that high pitched noise would drive me nuts if i were playing that game too much, but there is no distortion.  I think its more of a personal taste issue here than technical issue.

**Comment by barbudreadmon** [comment]
I agree, the new one are a lot clearer and i don't hear a distortion, the high pitched noise might be annoying though. Did you try playing with the audio core options (samplerate, sample interpolation and fm interpolation) to see if one of those settings could fit your tastes ?

**Comment by Tatsuya79** [comment]
I tried, didn't change much for that. The lowpass filter in stand-alone helps though.
I could do that with dsp filters in RA but I wanted to know if it was supposed to sound like that.

**Comment by barbudreadmon** [comment]
I'll take a look at the lowpass filter in standalone, it might be something i could turn into a core option.

**Comment by Tatsuya79** [comment]
There's a configurable one in genesis+gx.

**Comment by dinkc64** [comment]
barbudreadmon, its very easy to integrate - I used it in several drivers for mixing tricks.

**Comment by superctr** [comment]
Sorry for the delay, The qsound emulator renders at a fixed 24khz (like LLE or the actual PCB) so there is going to be aliasing at higher frequencies. It does not do sample interpolation, although it does have a built in FIR lowpass filter as part of the qsound stereo effect. Not always noticable though.

**Comment by barbudreadmon** [comment]
> I don't think the filter should be enabled by default

I agree, best case scenario would be to have the option as a fake dip or something like that.

**Comment by Tatsuya79** [comment]
Let's close this as it's not a bug.
There's a lowpass filter in FBN stand-alone and we have DSP in RA too for now.
