### ISSUE TITLE
Arkanoid Returns analog fixed on standalone but not libretro core.

### ISSUE THREAD

**Issue by fastpop72** [libretro/FBNeo#169]
On libretro core the game autoselect "Lightgun" instead of "RetroPad" and the X-Axis (Left/Right + and Left/Right -) is missing on controls list.

**Comment by barbudreadmon** [comment]
> On libretro core the game autoselect "Lightgun" instead of "RetroPad"

No ? That's simply impossible, sadly a core can't force a device while that's something i would really love

> the X-Axis (Left/Right + and Left/Right -) is missing on controls list.

I see them.

**Comment by barbudreadmon** [comment]
I tested, it works, that's crazy fast as @dinkc64 mentioned though. If it's not working for you, you probably have some setup issue (idk if it'll help you, but i think the only way to autoselect "lightgun" would be through a core override in your setup), closing.

**Comment by fastpop72** [comment]
Sorry but i tested it with retroarch in Windows and i tought it was updated but the binary core is left behind at the 62ec63e commit.

Later i will test it updating the core from source using Debian.

Thanks.
