### ISSUE TITLE
Hiscores on iOS Core not working, but MacOS does

### ISSUE THREAD

**Issue by estefan3112** [libretro/FBNeo#177]
Hi, I believe that on the latest stable iOS build 1.7.9 (as well as the previous 1.7.8), the highscores do not work. I have tried different hiscore.dat files, and while it works in MacOS Retroarch, it does not on iOS. Any ideas?

**Comment by barbudreadmon** [comment]
No, seems more like a setup issue than a core issue to me

**Comment by estefan3112** [comment]
If somebody could confirm me a working setup, I would do further testing. That would be great! Cheers!

**Comment by estefan3112** [comment]
I am closing here and try my luck via the forum

**Comment by estefan3112** [comment]
So only today I learned that Runahead is the problem. As soon as you activate Runahead (which I had done all the time), Highscores no longer save. I deactivate Runahead and now my Highscores work again - both on Mac and iOS. I was already getting nuts, this should be definitely mentioned in the app!
