### ISSUE TITLE
3 Punches/3 Kicks hotkeys not available

### ISSUE THREAD

**Issue by pokeshark** [libretro/FBNeo#194]
Any plans to port from the standalone version the hotkeys (3 Punches/3 Kicks/AB/CD etc.) for remapping from Quick Menu - Controls?

**Comment by barbudreadmon** [comment]
duplicate of https://github.com/libretro/FBNeo/issues/51, closing

**Comment by pokeshark** [comment]
oops. sorry, didn't see it.
