### ISSUE TITLE
Neo Turf Masters CD Graphic Bug

### ISSUE THREAD

**Issue by TradeDraft** [libretro/FBNeo#195]
When I play Neo Geo Turf Masters CD Version. Comes up with a Graphic Bug in that on some holes that have water comes up and shows that you in the Water when you are not

Screenshot:

![img](https://forums.libretro.com/uploads/default/optimized/2X/f/fe9f05711c287556e5ec337d3eb3b4f7fbe90031_2_666x500.png)

I have tried it on the NEOCD Core and I did not see this Issue.

Tried the MVS/AES Version and the Issue did not come up

**Comment by barbudreadmon** [comment]
Other example : 
![img](https://forums.libretro.com/uploads/default/optimized/2X/6/6d96f1c3752837c18f21f82e85fd0e1be1975b77_2_666x500.jpeg)
The map shows that there should be water right before the player.

@dinkc64 does it happen on standalone ?

**Comment by dinkc64** [comment]
fixed in main, game uses line rendering/raster but it wasn't enabled. sorry about that!
after an update is available - please let me know if it fixes the problem.  I can't find the course you are on to test it.

**Comment by barbudreadmon** [comment]
Fixed :)
