### ISSUE TITLE
Vimana (Toaplan) - Retroarch controls option is missing "User 2 Button 1"

### ISSUE THREAD

**Issue by Riddler1** [libretro/FBNeo#198]
See screenshot. 

-Player 2 shot and bomb is the same button. 
-User 2 Button 1 is missing
-Player 1 works ok. 

Not sure if just a Retroarch issue or Core issue. Think it might be core.

![Screenshot_20191123-221544_Gallery](https://user-images.githubusercontent.com/43607359/69486233-9d1fee00-0e41-11ea-861d-ba0dff0ddcfb.jpg)

**Comment by barbudreadmon** [comment]
Thanks for the report, fixed
