### ISSUE TITLE
Add support for "Final Fight 30th Anniversary Edition" romhack

### ISSUE THREAD

**Issue by leomontenegro6** [libretro/FBNeo#202]
Yesterday, a romhacker nicknamed [Grego](http://www.romhacking.net/forum/index.php?action=profile;u=18394) released a romhack called [Final Fight 30th Anniversary Edition](http://www.romhacking.net/forum/index.php?topic=28073).

[![Teaser video](https://img.youtube.com/vi/EdMiM1AvE6Y/0.jpg)](https://www.youtube.com/watch?v=EdMiM1AvE6Y)

Basically, this romhack adds support for 3 players simultaneously, just like in Cadillacs & Dinosaurs. This hack features:

 * Three Players
 * Selectable Palettes
 * Unlocked Character Selection
 * More Health for Enemies/Bosses with three players
 * Uncensored Intro / No Region Warning

Everything was done using the original Final Fight from CPS1, more specifically, "ffight.zip" aka "Final Fight (World, set 1)". So if you ignore any issues about CRC32 checkings that commonly happens in romhacks of arcade games, in theory any CPS1 emulator can run it.

I was trying to run it on Final Burn Neo, but there's some issues. The first is: The patcher basically creates a new rom called "ffightae.zip" ('ae' meaning 'Anniversary Edition'), but FB Neo simply won't run it, saying it's an invalid rom. And if I simply rename it from "ffightae.zip" to "ffight.zip", it'll say that some files has a invalid CRC32.

Is there a way of adding support for this hack in FB Neo, so I could play it on my Raspberry Pi?

**Comment by barbudreadmon** [comment]
done
