### ISSUE TITLE
Thunder Hoop black screen from stage 4

### ISSUE THREAD

**Issue by furiadeoso** [libretro/FBNeo#205]
Hi!

Thunder Hoop (thoop-GAELCO) emulation is buggy from stage 4. Inmediately after the player lost a live in this stage the screen turns black and it seems to crash.

This is a MAME known bug, but it has been reported to be an emulation bug. The original PCB did't have this bug and the rom dump seems to be right.

You can watch the bug at https://www.twitch.tv/videos/517502595?t=00h17m37s

To reproduce it you can use the attached savestate. It is starting stage 4. Let your character die.

[thoopstate.zip](https://github.com/libretro/FBNeo/files/3934387/thoopstate.zip)

It would be great if this bug is fixed in FBN. We are available to test what is necessary. Thanks!

**Comment by furiadeoso** [comment]
@barbudreadmon Sorry to mention you. I found a little odd to have no answer. Do you know anything about this issue?

**Comment by barbudreadmon** [comment]
Oops, sorry, i totally forgot to answer, idk how to fix this but @dinkc64 told me he would look into it (he is quite busy atm), i'll let you know when a fix is available.

**Comment by furiadeoso** [comment]
Ok. No hurry. :) I just didn't want this to be forgotten. Happy new year!

**Comment by arcadez2003** [comment]
Does this in MAME also............

https://mametesters.org/view.php?id=3232

**Comment by furiadeoso** [comment]
> Does this in MAME also............
> 
> https://mametesters.org/view.php?id=3232

Exactly. That is this bug.

**Comment by barbudreadmon** [comment]
Haze figured it out, fix is on git

**Comment by arcadez2003** [comment]
Further research into other Gaelco games might be required as it's been confirmed that Squash was also 
affected although in it's case it just caused some issues with the continue screen text rather than a full blown
crash.

World Rally is confirmed to use the same timer protection but as yet no bug reports have surfaced.

**Comment by furiadeoso** [comment]
Thank you very much! 👏
