### ISSUE TITLE
Cyclone and DrZ80

### ISSUE THREAD

**Issue by duduke** [libretro/FBNeo#215]
Can those commits:
https://github.com/libretro/mame2000-libretro/commit/ad07ac38747bd8abc74ea143dd73b7a05ee4d3be
https://github.com/libretro/mame2000-libretro/commit/1e09c86764f74b2a0ebad601df745cb7995d5c7f

Be ported to the mame2003-plus core? Can they be enabled for Pi0 as well?

**Comment by barbudreadmon** [comment]
wrong project, closing

**Comment by duduke** [comment]
@barbudreadmon is this relevant for FBNeo? can you reopen?

**Comment by barbudreadmon** [comment]
cyclone is already available through core options, i don't plan on adding the other one.
