### ISSUE TITLE
Broken hiscore support

### ISSUE THREAD

**Issue by n1ghttrap** [libretro/FBNeo#220]
Used Mario Bros as a test case, used hiscore.dat from this site/metadata.  Put it in /system/fbneo, option is enabled in core settings, does not save data when I register score, close, and start the game again.

**Comment by n1ghttrap** [comment]
Cleared autoconfigs/confgs for the core, enabled hiscore, made sure run-ahead was off.  Still not working.

**Comment by barbudreadmon** [comment]
There are 2 known cases when hiscores won't work : 
- the game doesn't implement it yet
- you are using netplay or readahead

`mario` & its clones weren't implementing it, support added in https://github.com/finalburnneo/FBNeo/commit/a0251d30cd238039a42c23f7b182c915d6679671
