### ISSUE TITLE
maxrpm - can't get past diagnostic screen

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/FBNeo#227]
this game in mind seems to have not registered any sort of input at all on both p1 start and p2 start, therefore, it's stuck in diagnostics.

**Comment by fastpop72** [comment]
@dinkc64 already said that driver is incomplete.

**Comment by arnoldsecret** [comment]
then it's supposed to be marked as debug/not working

**Comment by dinkc64** [comment]
fixed in the main branch, might need some help from @barbudreadmon w/inputs for libretro's side of things :)

**Comment by barbudreadmon** [comment]
No need here, those 2 worked without a change in my input code :).
I'll close !

**Comment by dinkc64** [comment]
glad to hear it :)

**Comment by fastpop72** [comment]
@dinkc64 Thank you for these fixes! 

It's normal that player2 in Max RPM has inverted Wheel Left/Right?

I think it's an upright game...

**Comment by dinkc64** [comment]
fastpop72, oops, that was a mistake on my part - fix checked in.
