### ISSUE TITLE
Mainline has X-Men (6 Players) support, but it's missing from the libretro core

### ISSUE THREAD

**Issue by vaguerant** [libretro/FBNeo#231]
The parent X-Men ROM is 4-player and the 2-player clones are supported, but there are also two dual-monitor, 6-player clones which aren't supported in the libretro fork. The 6-player versions aren't included in the DAT file either, but I tried loading one up just in case and it wasn't recognized.

The [X-Men driver](https://github.com/libretro/FBNeo/blob/master/src/burn/drv/konami/d_xmen.cpp) is up-to-date with the mainline one and includes both of the 6-player clones, so I'm not sure why they're not supported in the libretro core.

**Comment by barbudreadmon** [comment]
As you can see in the driver, their structs are `BurnDriverD`, which means it's only available in debug builds (because they don't work), same upstream.

**Comment by vaguerant** [comment]
Ah, thanks, sorry about the false report.
