### ISSUE TITLE
PS3 Retroarch FBNeo driver d_ssv.cpp   black screen problem

### ISSUE THREAD

**Issue by gigibyte236** [libretro/FBNeo#232]
Hi,
 it works the game vasara, or vasara 2 and in general the games of the driver d_ssv.cpp, on my ps3 they always give a black screen. the roms are correct, tested on both android and windows. I have checked Retroarch from version 1.81 to 1.84 taken by xbins.org/libretro the same problem, even on the one compiled by myself.  Can someone help me?  thanks.

**Comment by barbudreadmon** [comment]
> on my ps3

Probably some kind of big endian issue

**Comment by barbudreadmon** [comment]
almost fixed, only the sound still doesn't work

**Comment by barbudreadmon** [comment]
sound fixed by https://github.com/finalburnneo/FBNeo/commit/c4c83eeb6c453eae60d92698e82b7539514bd877
