### ISSUE TITLE
Mortal Kombat (1,2 & 3) dosen't start with core libretro Neo for PS3 

### ISSUE THREAD

**Issue by crystalct** [libretro/FBNeo#234]
Black screen on PS3 using FB Neo core (with FB Apha, too). On PC those roms works correctly.
Maybe is it a little bug? Using mame2000 core on PS3 they works.

**Comment by barbudreadmon** [comment]
i've been trying to fix as many opened BE issues as possible, but i'm closing this one as wontfix, 2 reasons : 
- those 2 drivers (tunit & wuint) are in a bad shape, they need a major rewrite
- if they are rewritten, big-endianization will need to be done again

if you come up with a fix anyway, feel free to send the PR

**Comment by crystalct** [comment]
OK
