### ISSUE TITLE
[Runahead] Various Issues with Single Instance

### ISSUE THREAD

**Issue by Awakened0** [libretro/FBNeo#242]
I went through and tested some games with runahead enabled, 1 frame, secondary instance disabled and compiled a list of issues:

**batrider** - BGM is slowed down on Course Select screen.
**garegga** - All BGM slowed down.
**cotton** - BGM doesn't play.
~~**ddpdoj** - Can't enter credits.~~
~~**espgal** - Can't enter credits.~~
~~**garou** - Wierd "bwong" at character select. Sometimes notes hang in the BGM depending on the stage (pirate girl stage in particular).~~
~~**gng** - BGM doesn't play right. Mostly just clicks and random notes.~~
~~**ghouls** - SoundFX are messed up. Throwing the javelin makes a thunk sound or sometimes doesn't play at all. Insert coin sound sounds off at the end.~~
~~**kod** - Sound pops after certain soundfx, like the letters appearing on the title screen or when picking up gold.~~
~~**lastbld2** - Similar to Garou. "Bwoop" on character select and missing bass in BGM. Hung note stuck playing in the background during first stage.~~
~~**mslug3** - Missing bass in character select BGM.~~
~~**mslugx** - Missing bass in character select BGM. First stage BGM starts with weird noise.~~
~~**mslug** - Neo Geo BIOS sound missing notes. First stage BGM missing bass.~~
~~**nbbatman** - Errors on ROM check screen. Lots of crazy flashing on screens leading up to gameplay.~~
**outrun** - BGM slowed down slightly.
~~**wjammers** - Neo Geo BIOS sounds wrong. Audio clicks in stage BGM.~~
~~**wbmlvc** - Colors and tiles are messed up and you move all crazy. This one's interesting.~~

I mainly want to avoid using secondary instance since it writes a copy of the core to a temp folder every time it's run. Then deletes it when RetroArch is closed. Since the FBNeo core is over 50MB that's a decent amount of extra file i/o and wear and tear on the drive. Maybe there are other benefits of fixing these if it makes the save state code better. But I'd understand if this is just too much work to fix these just for runahead single instance.

**Comment by barbudreadmon** [comment]
@Awakened0 `ghouls` seems fixed, along other cps1 games that also had sound issues with netplay/runahead (see https://neo-source.com/index.php?topic=3704.0)

**Comment by barbudreadmon** [comment]
neogeo seems fixed too

**Comment by Awakened0** [comment]
Ok, I've at least marked off ghouls from the list.

**Comment by barbudreadmon** [comment]
`kod` is a cps1 game too btw, i think it's fixed too

**Comment by barbudreadmon** [comment]
i think `gng` and neogeo games are ok after https://github.com/libretro/FBNeo/commit/a16bb0d0172c7a63787e8469cdab1286b3df766c

**Comment by Awakened0** [comment]
Nice. That's a good chunk of the list fixed.

**Comment by barbudreadmon** [comment]
Please double-check btw, i might be missing things.

**Comment by Awakened0** [comment]
I retested all the ones I struckthrough in the first post and they all sounded correct to me with single instance runahead.

**Comment by barbudreadmon** [comment]
@dinkc64 nbbatman : i can get around the flashing issues by scanning `nPrevScreenPos`, no idea about the rom check issue though, it looks like this : 
![nbbatman-200721-111819](https://user-images.githubusercontent.com/10391265/88037141-d3367e80-cb44-11ea-98f1-a5bb4613f252.png)

**Comment by barbudreadmon** [comment]
@Awakened0 irem m92 (nbbatman) should be ok after https://github.com/finalburnneo/FBNeo/commit/1224076c8b74f91007d2092f3b8b544caed7a03e

**Comment by barbudreadmon** [comment]
@dinkc64 wbmlvc : all sega system 2 games are actually glitched in one way or another, and seems to be fixed by the following : 
```
if (IsSystem2 || Sys1UsePPI)
	ppi8255_scan();
```
NB : weirdly, regulus, which does use ppi8255, doesn't seem to care whether we scan it or not.

**Comment by barbudreadmon** [comment]
@Awakened0 re outrun : i can't hear the issue for this one, are you sure ?

**Comment by Awakened0** [comment]
> @Awakened0 re outrun : i can't hear the issue for this one, are you sure ?

I managed to clip a section of Passing Breeze well enough in this comparison of Runahead off vs on:

![offvson](https://user-images.githubusercontent.com/4565863/88317459-4972e680-cce7-11ea-84e0-5cff54bf6870.png)

If you listen to the [two wav files](https://github.com/libretro/FBNeo/files/4967739/Runahead.Off.vs.On.zip) in quick succession, the off version sounds like it has a faster tempo than the on one.

**Comment by barbudreadmon** [comment]
I just can't hear this one, but i have a feeling we might solve it if we solve the more noticeable issue on batrider & bgaregga, which use ym2151 too.

**Comment by barbudreadmon** [comment]
@dinkc64 re ddpdoj/espgal : scanning hold_coin seems to fix this one

**Comment by barbudreadmon** [comment]
@Awakened0 pgm (ddpdok/espgal) should be ok now

**Comment by barbudreadmon** [comment]
@Awakened0 https://github.com/libretro/FBNeo/commit/bab39c7996fa0d3c50e4e9d23c5d1983b4c1e6f9 should solve all issues with ym2151, so basically all remaining issues

**Comment by Awakened0** [comment]
Yep, all sounds and looks great now. Thanks for all the work @barbudreadmon and @dinkc64 !

PS @barbudreadmon , could you set up digital controls for Outrun on the RetroPad? Sometimes I like to test it quickly with my keyboard, but steering, accel and brake don't work with the DPad or face buttons. Could be nice for people who want to play that game with controllers without analog sticks or triggers too.

**Comment by barbudreadmon** [comment]
i'll try to think on a solution to dual map directions, actually that's something i thought about in the past, thanks for reminding me

**Comment by Awakened0** [comment]
No problem!

**Comment by barbudreadmon** [comment]
https://github.com/libretro/FBNeo/commit/3ee3337129e5c26946f14ef65c62fef17dddd251 should do the trick, it works both way : 
- if dpad is free, analog left will also be mapped on dpad
- if analog left is free, dpad will also be mapped to analog left

It shouldn't mess with games using both analog left and dpad (i know there are some, but i can't remember their names)

**Comment by Awakened0** [comment]
Would it cause anything weird with RetroArch's Analog to Digital Type setting? I have that set to Left Analog globally and disable it per core or game for ones that support analog. With this commit I guess I could just disable it for FBNeo instead of each analog game.

**Comment by barbudreadmon** [comment]
> Would it cause anything weird with RetroArch's Analog to Digital Type setting?

I don't know if there is any safety mecanism on that setting to disable it at runtime if the target analog is already mapped. In doubt i would recommend disabling that setting which is useless with fbneo now.

**Comment by Awakened0** [comment]
It didn't seem to cause any issues in a quick test, but I left it disabled in my FBNeo override since I didn't see the need to over complicate things.
