### ISSUE TITLE
1:1 PAR for Vertical Games is Not Correct With Vertical Mode Off

### ISSUE THREAD

**Issue by Awakened0** [libretro/FBNeo#25]
If you load a vertical game like Dimahoo in FBA, the 1:1 PAR aspect ratio option is not correct unless the Vertical mode core option is enabled. Core Provided (DAR) works correctly, but it'd be nice to have both working for games like Dimahoo which have different PAR and DAR.

FBN 1:1 PAR:
![fbn par](https://user-images.githubusercontent.com/4565863/58446257-1b3b4c00-80ce-11e9-96b9-7dd327e1279f.png)

MAME 1:1 PAR:
![mame par](https://user-images.githubusercontent.com/4565863/58446270-242c1d80-80ce-11e9-816e-56e6d64a582d.png)

**Comment by barbudreadmon** [comment]
Using core-provided ratio is the right way to use this core, i don't even know what could be done to support custom ratio.

**Comment by Awakened0** [comment]
Is it something with the rotation that throws PAR off? A non-vertical game like gng works with PAR just fine (8:7 PAR vs. 4:3 Core Provided). A lot of vertical games that I like I prefer at core provided, or they don't even have a PAR that's different from that in MAME. But with Gunlock / Rayforce I like PAR, since the Taito logo's blue dot and the craters in background asteroids are symmetrical at that aspect.

I can at least force a custom ratio with an override. Just have to refer to MAME for the PAR and convert the fraction to a decimal.

**Comment by barbudreadmon** [comment]
> Is it something with the rotation that throws PAR off?

Yes, basically the width/height provided to RA is the one from the arcade cabinet and the same whatever the rotation (we don't switch width/height when using 90/270 rotation, iirc it messes with integer scaling if we switch them), so when you apply a 1:1 ratio the resolution for gunlock is 320x224, not 224x320.

**Comment by Awakened0** [comment]
I'm closing this since it should be on the frontend to properly rotate the pixel aspect ratio when doing 90 or 270 degree rotations.
