### ISSUE TITLE
1942 (1942) a new bug introduced after last commit?

### ISSUE THREAD

**Issue by fastpop72** [libretro/FBNeo#259]
I just tested the new commit with the fixed Capcom logo... but i noticed a new bug that has been introduced?

You can see it moving plane at far right:

![1942-200302-191622](https://user-images.githubusercontent.com/32760152/75709433-f01c0380-5cc2-11ea-9d51-2a516c6d6531.png)

**Comment by barbudreadmon** [comment]
Didn't see this one :(

@dinkc64 if i replace `GenericTilesSetClip(-1, -1, y-16, y-15);` by `GenericTilesSetClip(-1, -1, y-16, y);`, it fixes this one, however it's introducing a new glitch on the capcom logo (only visible on first frames of its first appearance), any idea about what i'm doing wrong ? I tried so many values already that i'm thinking of reverting it and calling it a day...

**Comment by barbudreadmon** [comment]
https://github.com/finalburnneo/FBNeo/commit/e2aa448f0785774461570a4e01560ba31aae5823 seems to fix it

**Comment by fastpop72** [comment]
Seems ok now! Thanks!

**Comment by barbudreadmon** [comment]
Thanks for the report :)
