### ISSUE TITLE
World Cup 90 (twcup90) sound effects issue.

### ISSUE THREAD

**Issue by fastpop72** [libretro/FBNeo#261]
Seems there's a sound effects issue during game, if you play you can hear it using kicks.

Some sound effects are "crackly".

This occur only with RetroArch using FBNeo core, Mame core and standalone FBNeo are OK.

I tried with Linux (debian) and Windows 10 RetroArch using default audio driver.

**Comment by barbudreadmon** [comment]
I don't think FBNeo core & standalone could have differences about the sound, both will produce exactly the same audio buffer before passing it to audio backend (retroarch for the core, directsound/xaudio for standalone), let's compare apples with apples, it is most likely about settings : 
- make sure to enable "sync to exact framerate" in RA's frame throttle setting, or RA will force 60Hz (the game run at 59.17Hz), it will do that for any game between 57 & 60Hz.
- make sure you are using the same samplerate & interpolation settings than standalone in core options

**Comment by fastpop72** [comment]
@barbudreadmon The "sync to exact framerate" didn't help.

Instead helped the interpolation settings: I changed the sampled interpolation and FM interpolation to the standalone default.

First was 4-point 3rd order for both settings, then i changed to 2-point 1st for sample interpolation and disabled the FM interpolation and the sound effects are OK now.

Thanks.
