### ISSUE TITLE
Tutankham (tutankhm) wrong commands setup on libretro core.

### ISSUE THREAD

**Issue by fastpop72** [libretro/FBNeo#265]
In libretro core this game share the "Left Stick - L/R" with "Right Stick L/R" but must be separated commands... Standalone is ok!

**Comment by barbudreadmon** [comment]
https://github.com/libretro/FBNeo/commit/e52c31c6ad6e69892a1d38cbc5eb7a018a5b6cc6 should fix it, thanks for the report !

**Comment by fastpop72** [comment]
Perfect! Thanks!
