### ISSUE TITLE
Two Tigers (twotiger) is missing P1 START button, standalone is OK.

### ISSUE THREAD

**Issue by fastpop72** [libretro/FBNeo#267]
A remap problem similar to Tutankham...

There must be two Start buttons for Player1. One for single play and one for 1on1 dogfight.

In libretro core are wrongly mapped. There's only the dogfight start.

Thanks.

**Comment by barbudreadmon** [comment]
Oops, sorry i totally forgot about this issue, fixed with https://github.com/libretro/FBNeo/commit/e31fce55e397f3b35627f06b0acd6c08bf9d4a76
