### ISSUE TITLE
Max Analog Range Isn't Far Enough

### ISSUE THREAD

**Issue by Awakened0** [libretro/FBNeo#27]
Not sure if that's how to phrase it, but in Space Harrier I noticed that pushing the analog stick as far as possible doesn't cause your character to go as close to the edge of the screen as is possible in MAME. Same in Outrun, where you can't turn far enough to make the tires squeal during turns.

**Comment by barbudreadmon** [comment]
I played around with values in the analog mapping code but it doesn't seem to improve anything. Let's ask @dinkc64 if he knows anything about this.

**Comment by dinkc64** [comment]
I changed it over to use my new analog processing device instead of raw-processing of analog stuff, and let the game use the full swing (0x20 - 0xe0) instead of the limited range it had before - please let me know if it helps :)

just fyi, before and after this change, sharrier in fbn and mame played side-by-side moved to the exact same edge of the screen when I tested it, so I'm not sure really what's going on here.  Hopefully the issue is solved with the new code, though!

**Comment by Awakened0** [comment]
Built with those changes and Space Harrier has the full range now. Outrun is unchanged.

**Comment by dinkc64** [comment]
Oops, I missed the note about outrun - will be in soon :)

**Comment by dinkc64** [comment]
2 hours later, and I managed to remove all of the old hacky analog handling code from most of the sega games and replaced it with proper analog handler.  I think the games include:
outrun, space harrier, hangon, s.hangon, thunder blade, abcop, gprider, racing hero, super monaco gp and after burner 1 and 2.
Thanks for the bug report, and please let me/us know if you notice any others :)
best regards,
- dink

**Comment by Awakened0** [comment]
I'm getting this error when trying to build now:

> ../../burn/drv/pre90s/d_asteroids.cpp: In function 'UINT32 scalerange(UINT32, UINT32, UINT32, UINT32, UINT32)':
../../burn/drv/pre90s/d_asteroids.cpp:691:15: error: 'UINT32 scalerange(UINT32, UINT32, UINT32, UINT32, UINT32)' was declared 'extern' and later 'static' [-fpermissive]
 static UINT32 scalerange(UINT32 x, UINT32 in_min, UINT32 in_max, UINT32 out_min, UINT32 out_max) {
               ^~~~~~~~~~
In file included from ../../burn/burnint.h:17:0,
                 from ../../burn/tiles_generic.h:1,
                 from ../../burn/drv/pre90s/d_asteroids.cpp:9:
../../burn/devices/joyprocess.h:24:8: note: previous declaration of 'UINT32 scalerange(UINT32, UINT32, UINT32, UINT32, UINT32)'
 UINT32 scalerange(UINT32 x, UINT32 in_min, UINT32 in_max, UINT32 out_min, UINT32 out_max);
        ^~~~~~~~~~
make: *** [Makefile:655: ../../burn/drv/pre90s/d_asteroids.o] Error 1

**Comment by dinkc64** [comment]
oops!, try now :)

**Comment by Awakened0** [comment]
Compiling works now. I can now get the tires to squeal. But the steering still feels kind of "heavy" compared to MAME. Like it takes longer to reach maximum turning on the left and right, which makes the car feel less responsive. Maybe MAME's analog sensitivity is higher, or it uses a smaller x axis. I tried changing the FBN analog option from 10 to 1, but it didn't seem to help.

**Comment by barbudreadmon** [comment]
@Awakened0 give this a try, replace `0x0800` by `0x0E00` in the following line and rebuild : https://github.com/libretro/FBNeo/blob/85a4cdd34032d086dcb281f001e11b7189456197/src/burner/libretro/retro_input.cpp#L260

Let me know if it feels better.

**Comment by Awakened0** [comment]
That's better. Still not quite as fast as MAME in changing the direction from left to right if I wiggle the stick back and forth. It almost feels like there's extra input lag in FBN when doing that, but I don't think it's that since FBN has 1 less lag frame than the MAME core.

**Comment by barbudreadmon** [comment]
Ok, thanks for the feedback, i'll try to implement a way to fine tune all those analog controls then.

**Comment by Awakened0** [comment]
Cool :)

**Comment by dinkc64** [comment]
barbudreadmon, it should only use the slider values for digital controls.  For analog controls, it should map directly.  I think this is where the lag is coming from.

**Comment by dinkc64** [comment]
Awakened0, are you using a digital or analog control on your gamepad?

**Comment by barbudreadmon** [comment]
Ok, so i should use the slider thing only when i'm mapping digital physical controls to analog emulated controls ? Thanks for the information, i always thought the slider thing was some sort of wheel-like control.

**Comment by dinkc64** [comment]
yes :)

**Comment by Awakened0** [comment]
> Awakened0, are you using a digital or analog control on your gamepad?

Left analog, with RetroArch's "Analog to Digital" option disabled.

> @Awakened0 my last commit should fix your issue then :)

Yep, feels just as responsive as MAME now. Thanks you two!

**Comment by dinkc64** [comment]
great! :)
