### ISSUE TITLE
Analog Trigger Support

### ISSUE THREAD

**Issue by Awakened0** [libretro/FBNeo#28]
I only tested Outrun, but I couldn't find any way to enable something like this. Tried setting the input type to Classic and Modern. Would be nice to have this for analog acceleration and brake in driving games.

**Comment by barbudreadmon** [comment]
I agree it would be nice

**Comment by dinkc64** [comment]
I agree, I started working on it but didn't have time to do it all last night.

**Comment by dinkc64** [comment]
Hi, I added the analog accel for outrun, hangon, shangon, enduror,  I will do the sega xbrd games later today.  Any others you can find let me know.

best regards,
- dink

**Comment by barbudreadmon** [comment]
Nice, now i just have to hook those to retropad's triggers :)

**Comment by Awakened0** [comment]
@barbudreadmon in case you need some reference: https://github.com/libretro/mame/pull/85

The way it's done in MAME works, though admittedly it feels like there's very little range. I feel like I have to just barely press my XBone controllers right trigger to get less than max throttle in Outrun.

**Comment by dinkc64** [comment]
sega xbrd and ybrd games now have proper analogs hooked up for everything. 
(y: gloc, pdrift, gforce2  x: abcop, gprider, rachero)

**Comment by dinkc64** [comment]
how's everything working out regarding these new analog changes? :)

**Comment by barbudreadmon** [comment]
They work really well ! It's especially noticeable in ybrd. I still need to move their default control to triggers though.

**Comment by dinkc64** [comment]
that's good to hear :)  I'm especially happy about removing all of that ugly code, besides, I think that ex-team member had a copyright on it :P

**Comment by barbudreadmon** [comment]
I started implementing analog trigger support : https://github.com/libretro/FBNeo/commit/f4ba4285d5cf4b96f1ce002ce9d706a7a96d3d1b

There is still a lot to do, but at the very least it should work in most sega racing games.

**Comment by Awakened0** [comment]
Works great in Outrun. The range feels wider than MAME to me too.

Thanks @dinkc64 and @barbudreadmon !

**Comment by dinkc64** [comment]
excellent, glad things worked out! :)

I need some help:
When adding the new analog stuff to Sega YBoard games, I noticed a bug in Galaxy Force 2, which is an awesome shooter I've never played before.  While moving around on the screen, the player sprite "jitters" around.  I added a fix for this, but since it changes the timing I am worried that it might affect other YBoard games.  If a bug is noticed in Power Drift, Gforce2, gloc that didn't exist before, please let me know :)
Here's the new fix: https://github.com/finalburnneo/FBNeo/commit/58f3b033557bbb29debed730f906b5a21f565268

best regards,
- dink

**Comment by Awakened0** [comment]
I'm not super familiar with those three (I've played pdrift and gforce2 before), but testing them in MAME for a little, then FBN, I don't notice anything off. Just that there's no acceleration mapped to a trigger in gforce2, but looks like that's just not hooked up in the core yet.

**Comment by dinkc64** [comment]
very nice, thank you for testing :)

**Comment by barbudreadmon** [comment]
More analog trigger support in https://github.com/libretro/FBNeo/commit/3f77785be9c9abd0808d68f1ede3cd5a2bae4d20 . I should be done with racing games, next batch will be about "flying" games like Galaxy Force 2.

**Comment by barbudreadmon** [comment]
It should be the last batch : https://github.com/libretro/FBNeo/commit/0fc2b813aec562f5689d43202034612a35ee06b2
Let me know if i forgot some.
