### ISSUE TITLE
[Issue] Control problem with Neo-Geo

### ISSUE THREAD

**Issue by Immersion95** [libretro/FBNeo#281]
Hi,

Neo-Geo input layout suffered regression.

Classic : Doesn't match the Neo-Geo CD layout
Modern : There are only 3 buttons, 1 is missing -->In KOF, characters do C+D when you press the top button.

**Comment by barbudreadmon** [comment]
Oops, should be fixed with https://github.com/libretro/FBNeo/commit/dfc66aface0abd73d52d0a96caea4061bad4c476

**Comment by Immersion95** [comment]
It is now :)
