### ISSUE TITLE
Mapping Support for Service and Test buttons

### ISSUE THREAD

**Issue by LordPinkerton** [libretro/FBNeo#286]
As title says, please add support to map the Service and Test switches/buttons.

**Comment by barbudreadmon** [comment]
Service menu is accessible in every game supporting this by setting the shortcut for "diagnostic input" in core options. If it's not enough, explain your use case.

**Comment by LordPinkerton** [comment]
Well, Crack Down requires these buttons to navigate the service menu. Not sure how many other games may also have this issue.

**Comment by barbudreadmon** [comment]
ok, i know another game needed something like this, i'll look into it.

**Comment by barbudreadmon** [comment]
Should be ok with https://github.com/libretro/FBNeo/commit/71cf627f2cb5f4c003cbfa535e8cf5950b561f10 .
The diagnostic input is actually the test button, so only the service button was required (i mapped it to R by default).
NB : there are several service buttons, but only the "Service 1" button seems to do something
