### ISSUE TITLE
[Android] mslug5, kof2003 force closes

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/FBNeo#3]
Load Content > mslug5.zip or kof2003.zip > Arcade (FB Alpha)
Expected: Metal Slug 5/The King of Fighters 2003 loads
Result: force close, no Retroarch has stopped message.

Android 6.0.1
1.4GHz Snapdragon 425 Quad-core
2GB RAM

**Comment by barbudreadmon** [comment]
@arnoldsecret i'm not against adding those clones, but maybe try the following clones first : 
- kf2k3bl
- kf2k3bla
- kf2k3pl
- kf2k3upl
- ms5plus
- mslug5b
- mslug5w

I think their init functions is faster than their parent so it might solve your issue.

**Comment by grant2258** [comment]
I know when i was having issues in plus i was getting casting issues didnt cause a crash on windows or linux though. Asan will should you there issues when a the games are run it probably that android seems less forgiven than any other os.

**Comment by barbudreadmon** [comment]
@arnoldsecret i just did another blind attempt at fixing that wrong behavior on android, please let me know if it improves situation with those games
