### ISSUE TITLE
Demon Front black screen

### ISSUE THREAD

**Issue by toccata10** [libretro/FBNeo#30]
I'm trying to migrate from fbalpha to fbneo. Seems to work fine, except for 1 game (so far): demon front (rom: dmnfrnt.zip, size 22 900 742o and pgm.zip:2 190 114o).
It plays fine with fba, but in fbneo, it launches and doesn't display the background graphics (see screenshots). If I insert coin and launch the game, it entirely black.
I tried several other pgm games (martial master, kovsh,...): they all work fine.
I'm using the flatpak version of retroarch, on a laptop with a pentium n4200 igpu (mesa 19.0.5).

![fbalpha](https://user-images.githubusercontent.com/7478580/58509991-1b078300-8198-11e9-9792-59de257cbda7.jpg)
![fbneo](https://user-images.githubusercontent.com/7478580/58510001-1d69dd00-8198-11e9-9978-a4b9a23dc3d4.jpg)

**Comment by barbudreadmon** [comment]
I'm having the same issue, it fails differently depending on when and what you press, sometime you get black screen, sometime you get some text (not necessarily text usually displayed by this game though), sometime you can go to select screen, let's tag @dinkc64 about this.

**Comment by dinkc64** [comment]
something is wrong on my side, too - I'll try to get it fixed asap :)

**Comment by dinkc64** [comment]
all fixed now.  thanks for the bug report! :)

**Comment by toccata10** [comment]
Works perfectly now. So, fixed in less than 12h after the bug report...Amazing ! Thanks for your dedication to this project.
