### ISSUE TITLE
NES: remove "NES" from driver name (BurnDrvGetTextA)

### ISSUE THREAD

**Issue by Cpasjuste** [libretro/FBNeo#300]
Hi,

Most of the NES roms/drivers names are wrongly named, to me. The other platforms don't append the platform name on rom name (BurnDrvGetTextA). 
For example, BurnDrvGetTextA for "10-yard fight (usa)" returns "NES 10-yard fight (usa)" while it should returns "10-yard fight (usa)".

**Comment by dinkc64** [comment]
@cpasjuste, this is something left over from development that was supposed to turn into a toggleable feature, BUT I didn't get a chance to make it happen yet.

@barbudreadmon, for HARDWARE_NES/HARDWARE_FDS case - it might be a good idea to do that with code for now until I come up with a better way to realize the feature I am trying to accomplish.  sorry for the troubles!

**Comment by barbudreadmon** [comment]
@dinkc64 that shouldn't be a problem as far as the libretro port is concerned, it doesn't really use `BurnDrvGetTextA` since there is no factory to provide the game name to RA, it's only shown in logs but who look at logs ? :)

**Comment by Cpasjuste** [comment]
> @dinkc64 that shouldn't be a problem as far as the libretro port is concerned, it doesn't really use `BurnDrvGetTextA` since there is no factory to provide the game name to RA, it's only shown in logs but who look at logs ? :)

Well, libretro is not the only project using fbneo :D

**Comment by barbudreadmon** [comment]
> Well, libretro is not the only project using fbneo :D

Yes, but since you are posting in the libretro fork instead of upstream, that's a bit misleading :)

**Comment by Cpasjuste** [comment]
Crap, you're right, I did an error (and I hate this :)), what a shame. I wanted to open this on upstream of course, I guess I didn't sleep enough :x

**Comment by barbudreadmon** [comment]
Can i close this ?

**Comment by Cpasjuste** [comment]
Yes sorry, I'll try to remember to re-create this on fbneo repo directly.

**Comment by barbudreadmon** [comment]
> I'll try to remember to re-create this on fbneo repo directly.

I don't think there is much point since you got an answer already : there will be a feature to toggle this in the future, until then you can remove it programmatically in your fork.

**Comment by Cpasjuste** [comment]
Yes, it's done in my fork since a while now. 
Else, I don't see the need for this feature, as you can already retrieve the platform/hardware.

**Comment by dinkc64** [comment]
I use it all the time.  example, bring up game list & type:
_neskirb_ and instantly go to Kirby's adventure on nes without having to move the mouse (or even reach for it..)

**Comment by Cpasjuste** [comment]
Yes i see. I still think this should be handled by the user interface, not in fbn driver (as i do here for example: https://github.com/Cpasjuste/pemu/blob/master/ui/c2dui_ui_romlist.cpp#L156)

**Comment by dinkc64** [comment]
of course, it's a left-over from developing the driver for 6+ months straight.   I don't do anything for retroarch, it's ui...............

**Comment by barbudreadmon** [comment]
> fbn should not target retroarch to my opinion (of course ^^).

You are misunderstanding something, so i'll repeat : this port basically doesn't use this call.
