### ISSUE TITLE
Retroarch crashes when launching Golden Axe with FBNeo core

### ISSUE THREAD

**Issue by viaDomitia** [libretro/FBNeo#302]
Retroarch (Windows or Android) crashes immediately when launching Golden Axe with FBNeo core ( v0.2.97.44 - 7ae7604). Log files are empty. I only have the time to capture this error in the console:
![fbneo_goldnaxe](https://user-images.githubusercontent.com/30547764/78979295-db315c00-7b1b-11ea-996a-f95e74430d93.JPG)

No problem running this rom with the standalone version of FBNeo (lastest Windows x86 build v0.2.97.44).

**Comment by barbudreadmon** [comment]
I can't reproduce this issue here, make sure you are using the latest version of the core, @dinkc64 fixed an issue with savestates in the sound core used by this game (https://github.com/finalburnneo/FBNeo/commit/5a27684fdbc112e5959c52fc1ac21ac6b1f80004) a few hours ago.

**Comment by viaDomitia** [comment]
OK. Seems I already have the lastest version of the core:
![image](https://user-images.githubusercontent.com/30547764/78990371-92d36780-7b36-11ea-81d5-7a47a4d7313a.png)
Could you confirm me you have this version as well ?

**Comment by dinkc64** [comment]
That was probably the issue, since ra uses runahead and/or rewind (in the state system).

**Comment by barbudreadmon** [comment]
> OK. Seems I already have the lastest version of the core:
> ![image](https://user-images.githubusercontent.com/30547764/78990371-92d36780-7b36-11ea-81d5-7a47a4d7313a.png)
> Could you confirm me you have this version as well ?

There is a more recent version of the code, but maybe it didn't make it yet on the libretro buildbot, you'll have to wait then

**Comment by viaDomitia** [comment]
OK, thank you !
I'll wait for the next online update of the core and let you know.

**Comment by viaDomitia** [comment]
Hello,
Well done ! As expected, problem solved with the new updated FBNeo core. Thanks !!
![image](https://user-images.githubusercontent.com/30547764/79043651-ad721300-7c00-11ea-88eb-59f133f3220c.png)
