### ISSUE TITLE
Osman has corrupted background graphics on Wii U (big endian issue?)

### ISSUE THREAD

**Issue by vaguerant** [libretro/FBNeo#308]
Screenshot:

![osman-200418-024302](https://user-images.githubusercontent.com/5259025/79594000-a1fe7a80-811f-11ea-829e-d2b435cf2bfd.png)

Seems like this is probably another endianness issue ala #271. The game otherwise actually seems to run very well: sprites work, coins are accepted, looks and sounds like full speed, etc. It seems very close to being playable except for being completely unplayable.

**Comment by dinkc64** [comment]
I think this should be fixed now

**Comment by vaguerant** [comment]
Confirming that running via 64b5c46 this issue is completely resolved. Thanks!
