### ISSUE TITLE
Jr Pac-Man not saving high scores

### ISSUE THREAD

**Issue by Dannonew** [libretro/FBNeo#315]
Submitted this yesterday to the main FBNeo git, and they closed it saying it was updated and fixed, but I re-installed on my Retropie rig from source and it's still not in the LR-FBNeo fork. Does LR-FBNeo automatically update from the main branch, or are changes committed individually until a major update?

**Comment by barbudreadmon** [comment]
There is a delay, but this one should have been ok ~3 hours before you wrote this issue, i'll do some tests to confirm it works

**Comment by Dannonew** [comment]
Rebuilding now. thanks!
