### ISSUE TITLE
Option to Not Auto Rotate Shaders

### ISSUE THREAD

**Issue by Awakened0** [libretro/FBNeo#32]
This is a bit of a weird request, but I was playing around with crt-guest-dr-venom with vert games and it doesn't really look great. Something about it isn't aligned properly or scaled badly. This shader has a TATE option that looks really nice with MAME. If you enable that with FBN the scanlines end up horizontal though. Here's a comparison in how it looks in MAME with TATE on and FBN with TATE off: http://screenshotcomparison.com/comparison/701

**Comment by barbudreadmon** [comment]
That's basically the same issue than what i explained in https://github.com/libretro/FBNeo/issues/12 . It works with MAME because MAME uses software rotation internally instead of using libretro's "hardware accelerated" rotation api call. Providing switched height/width would probably solves this but it would break integer scaling.
Both this issue and the other are basically frontend issues.

**Comment by Awakened0** [comment]
Hmm, so it'd probably be better to open an issue about rotation api on the RetroArch issues page and maybe reference these there.

**Comment by barbudreadmon** [comment]
Yeah, we need clarification about this, and you can also mention https://github.com/libretro/RetroArch/issues/8551

**Comment by Awakened0** [comment]
In the meantime, could a core option to report the rotated height/width to the frontend be added? With a small description in parenthesis like "(fixes shaders/PAR; breaks integer scale)".

**Comment by Awakened0** [comment]
I mentioned this in the other issue on the RetroArch repo:

A workaround for FB Neo I found is to turn on Vertical mode in it's core options, then set Screen Orientation to 270. crt-guest-dr-venom looks about the same as it does with MAME with TATE mode enabled and both PAR and DAR aspects work as expected. Though that also makes the GUI sideways :P

**Comment by Awakened0** [comment]
I'm closing this since it seems to be something wrong in how the frontend scales shaders during 90 or 270 degree rotations.
