### ISSUE TITLE
Crashes loading content on Vita

### ISSUE THREAD

**Issue by rsn8887** [libretro/FBNeo#321]
To reproduce:
- Load any content and start with fbneo core on Vita
- Observe crash with error C2-12828-1

I tried playlist (import content), loading .zip file via Load Content, and tried all fb* cores, and got a crash on all of them.

Tested mostly with Ghouls'n'Ghosts rom. My rom scanned correctly and is in the "Arcade Games" playlist with the FB logo.

core version: ad26e81

**Comment by barbudreadmon** [comment]
I know nothing about psvita, and i don't have the means to debug this. However, a quick "C2-12828-1" search on google tells me that the issue is well known with "henkaku" and probably totally unrelated to the core.

**Comment by rsn8887** [comment]
No. It is a generic error messages. It is the core.

**Comment by barbudreadmon** [comment]
Are you sure ? What i read about this error on http://www.logic-sunrise.com/dossiers-et-tutoriaux-869717-comment-corriger-lerreur-c2-12828-1-pour-henkaku.html (it's french, sorry) is "It is not directly linked to the application itself but to its execution and invalid processing.".

Is the issue new ? The core worked previously ? Other cores work ?

**Comment by rsn8887** [comment]
You are right I was stupid. I used an old version of the rom. I updated to latest FBNeo roms, and now it works. But still weird that it crashed instead of saying "Failed to load content".

Sorry.
