### ISSUE TITLE
Fatal Fury 2 doesn't load

### ISSUE THREAD

**Issue by Cee123** [libretro/FBNeo#33]
Fatal Fury 2 doesn't seem to be supported. And I've tried several different versions of this rom but no such luck.

**Comment by barbudreadmon** [comment]
> Use clrmamepro (which runs fine on linux with wine and on mac with crossover) to build valid romsets with dats from the dats directory. Don't report issues if you didn't build a valid romset

Closing

**Comment by Cee123** [comment]
Yeah but the thing is, all the rest of my roms work fine except that one game. And I have tried various different sources. No such luck. Also I don't have Linux, is there an alternative I can use for Windows? If not, I'll just run Ubuntu under a virual drive.

**Comment by Cee123** [comment]
Nevermind I found a version of clrmamepro that works on Windows. Thanks! I'll try what you said.

**Comment by barbudreadmon** [comment]
> And I have tried various different sources

That's the problem here, you try random roms instead of following the README/FAQ.

> You mentioned clrmamepro, is there an alternative I can use for Windows? 

That's a windows app

**Comment by Cee123** [comment]
Still doesn't seem to work. Strange.

**Comment by barbudreadmon** [comment]
Post logs

**Comment by Cee123** [comment]
[retroarch__2019_05_30__18_24_42.log](https://github.com/libretro/FBNeo/files/3236589/retroarch__2019_05_30__18_24_42.log)

**Comment by barbudreadmon** [comment]
Nothing is strange, your rom is incomplete : 
>[libretro ERROR] [FBNEO] ROM at index 0 with CRC 0xecfdbb69 is required ...
[libretro ERROR] [FBNEO] Can't launch this game, some files are missing.
[ERROR] Failed to load content.

That's why i ask people to use clrmamepro to check their romsets before reporting any issue.

**Comment by Cee123** [comment]
You were right. It was incomplete. I couldn't find a complete version of that rom anywhere. And even after trying to rebuild it it still gave the error. I will try to get another version of that file. Thanks for the help.
