### ISSUE TITLE
Captain America and the Avengers has corrupted graphics on Wii U

### ISSUE THREAD

**Issue by vaguerant** [libretro/FBNeo#341]
Captain America and the Avengers (`captaven.zip`) is another likely candidate for big endian issues. A couple of screenshots:

![captaven-200523-224242](https://user-images.githubusercontent.com/5259025/82731030-63c03080-9d47-11ea-9765-6649ea0679b5.png)
![captaven-200523-224410](https://user-images.githubusercontent.com/5259025/82731033-6589f400-9d47-11ea-9d6b-6244ae20db42.png)

Some graphics are becoming corrupted and appearing as a garbled, flickering mess toward the left and bottom left of the screen. In gameplay, it seems to be mostly the sprite graphics that have issues (e.g. the player character and enemies), but other graphics like the cutscenes (second screenshot above) are also not displaying correctly. However, stage backgrounds (as seen in the first screenshot) are displaying without issue.

Expected behavior during cutscenes:
![captaven-200523-225242](https://user-images.githubusercontent.com/5259025/82731161-388a1100-9d48-11ea-93af-c55704f244ab.png)

I am running an up-to-date nightly core, 64b5c46.

**Comment by dinkc64** [comment]
Hi, I made an attempt to endi-fix captaven - please give it a try when the new lr core is updated, and post new screenshots - especially if there continues to be issues, because I'll need them to figure out the remaining issues.

best regards,
- dink

**Comment by vaguerant** [comment]
I went to grab today's nightly but noticed the buildbot hasn't been serving updated cores for Wii U for the last two days. I filed this as an issue over at libretro/RetroArch#10762, so I will update as soon as I can actually get a nightly. Sorry for the delay.

**Comment by barbudreadmon** [comment]
> Depending on when during the attract mode sequence the player inserts their credits, the background color changes

I can reproduce this, so that's not a big endian issue. I think there is an issue with background color in attract mode, and it's affecting the "press start" screens too.
The video quality isn't that good so i'm not sure, but i think the background color is supposed to be black : https://www.youtube.com/watch?v=9xUfmTfYcn4

**Comment by dinkc64** [comment]
It's actually normal how it works now.
barbudreadmon, if you look closely on the video you posted, you'll notice the screen is actually grey after coin-up.  The reason its black if you coin up right @ boot - the palette isn't fully loaded yet.

best regards,
- dink

**Comment by dinkc64** [comment]
I wonder if there exists a pcb video of coining up real fast while its booting.

**Comment by barbudreadmon** [comment]
tbh, the contrast is so bad that i'm unable to distinguish background colors i think. Sounds ok then, i'll close !
