### ISSUE TITLE
[Request] Neo Geo HD Zoom

### ISSUE THREAD

**Issue by MagitekArmor** [libretro/FBNeo#348]
When zooming, NG games looks too pixelated.

Samurai Shodown Collection has this implemented by rendering 2x (or more) doubling scanlines and horizontal pixels: https://twitter.com/MikeJMika/status/1265687928652525568

Can something like this be implemented on FBNeo?

![EZCdpBRVAAEE-Wu](https://user-images.githubusercontent.com/65924409/83314446-cbb3c280-a1f0-11ea-8d0e-d75d04ab08c0.png)
![EZCdvuCUcAI-o9O](https://user-images.githubusercontent.com/65924409/83314449-cfdfe000-a1f0-11ea-80ee-ff9267f23f00.png)

**Comment by barbudreadmon** [comment]
By policy, the FBNeo team doesn't accept requests, only bug reports. We might implement this or not (most likely we will, we were talking about it already). Closing.
