### ISSUE TITLE
[FR] Neo Geo memory card support

### ISSUE THREAD

**Issue by rhester72** [libretro/FBNeo#354]
It looks like there may already be substantial code for it already - any chance of (working) support for Neo Geo memory cards (beyond saving UNIBIOS configuration settings)?

**Comment by barbudreadmon** [comment]
it seems to work as some kind of special savestate, i'll try to implement it this week-end.

**Comment by rhester72** [comment]
Thank you very much!  Happy to test (via Raspberry Pi/RetroPie, at least) whatever you like.

**Comment by barbudreadmon** [comment]
I think it should work now

**Comment by rhester72** [comment]
Compiled @ 215503d - no observable change from within Retroarch.

Testing methodology I use:

- Switch Neo Geo BIOS to UNIBIOS
- Restart emulation, immediately hold down A+B+C+D to enter Memory Card Manager
- Display Stored Data should *not* say "Plug the Card In", and Format Memcard should format when pressing the A button

**Comment by barbudreadmon** [comment]
It might be fixed by https://github.com/libretro/FBNeo/commit/212ab065614b91663df0ae292c118d2fff625ec4

At the very least the memcard is properly detected by unibios now, it seems it needed to be inserted after calling the neogeo init function, because the init function force the memcard status to ejected.

**Comment by barbudreadmon** [comment]
With https://github.com/libretro/FBNeo/commit/aae1e0bfba9da7dac617f8c0b22a03569f4f6f5f, i also made it optional (through core options) because it's using space while i don't think many people will use this feature.

**Comment by barbudreadmon** [comment]
re-open if it's still not functional

**Comment by rhester72** [comment]
Very sorry for the very late response, had hardware issues - tested and working perfectly, thank you very much!
