### ISSUE TITLE
PS3 compilation error

### ISSUE THREAD

**Issue by crystalct** [libretro/FBNeo#357]
../../cpu/tlcs900/900tbl.c:5606: error: expected unqualified-id before numeric constant
make: *** [../../cpu/tlcs900/tlcs900.o] Error 1

Probably _D0 is not ammitted as function name.

**Comment by barbudreadmon** [comment]
> ../../cpu/tlcs900/900tbl.c

I think you are doing something wrong, that file isn't supposed to be built, maybe try again from a clean clone of the repository

**Comment by crystalct** [comment]
$ git clone https://github.com/libretro/FBNeo
$ cd FBNeo
$ make -j5 -C src/burner/libretro platform=ps3
.....Error
Just that
If you confirm that a rename of _D0 in H_D0 (for example) of all occurrencies is good then all is OK for me.

**Comment by crystalct** [comment]
I confirm.... SDK sony have _D0 somewehe.
Just tested in a test.c:
int alpha = _D0;
char txt[64];
sprintf(txt, "_D0 is: %d", alpha);

No error. If i used _D9 (for example): error: '_D9' was not declared in this scope
I got 0 when txt was printed

**Comment by barbudreadmon** [comment]
ok, could you try renaming all occurences of `_D0` in `900tbl.c` ?

**Comment by crystalct** [comment]
Done... with H_D0 compilation successfully.

**Comment by crystalct** [comment]
Very elegant solution:
#if defined(__CELLOS_LV2__)
#undef _D0
#endif

on top of 900tbl.c

**Comment by barbudreadmon** [comment]
thanks for the suggestion, done, feel free to close after testing latest commit :)

**Comment by crystalct** [comment]
Yep!
