### ISSUE TITLE
Support for aspect ratio setting

### ISSUE THREAD

**Issue by dezraj** [libretro/FBNeo#366]
Dear developers, would it be possible to add an option to change the aspect ratio of the games within the core? I'm concerned about some arcade systems which run in 16:9 aspect ratio such as CPS1, 2 and 3. Currently the only way to show these systems in 16:9 is by changing Retroarch's scaling options. But then other arcade systems which run in 4:3 such as NeoGeo will look deformed.

It would be more user-friendly to have a core setting for changing the aspect ratio such as we have in the standalone emulator. That way we could save per-game core settings.

Thank you for your attention and for your work in the core.

**Comment by barbudreadmon** [comment]
> I'm concerned about some arcade systems which run in 16:9 aspect ratio such as CPS1, 2 and 3

They don't, cps run in 4:3. You are supposed to use "core provided" in retroarch's aspect ratio, otherwise every game in every libretro core will be deformed. Closing as i don't intend to implement settings to deform games, especially ones that would be duplicates of settings already existing in retroarch.

**Comment by dezraj** [comment]
Thanks for clarifying. I got confused because if we select stretch -> normal stretch in the standalone emulator we do get a widescreen picture for CPS games and we do get a 4:3 picture for NeoGeo. So I thought we could have the same in FBNeo for Retroarch.

Thanks again for your time and work.

**Comment by barbudreadmon** [comment]
> we do get a widescreen picture for CPS games and we do get a 4:3 picture for NeoGeo

What you are refering to is probably equivalent to PAR (pixel aspect ratio), where the pixel aspect ratio is 1:1 (that setting exists in RA). That's not how games are supposed to be rendered, but some people seems to like it that way.

**Comment by dezraj** [comment]
Thank you for the clarification.

Is it be possible in Retroarch to add a frame to the picture to fill the black bars produced by a 4:3 picture shown in a 16:9 display, just like we have in modern official compilations? It would be interesting to display a sideways art that matches each game there.

Thank you so much again.

**Comment by barbudreadmon** [comment]
You are talking about retroarch overlays, there are some tutorial on internet, here is one on youtube : https://www.youtube.com/watch?v=8MDokZYxHIY
