### ISSUE TITLE
Killer Instinct 1.5d freezes using FBNeo but only with Thunder and Orchid

### ISSUE THREAD

**Issue by thetallguy24** [libretro/FBNeo#367]
Have an issue using the 1.5d rom for KI using Retroarch (1.8.9) and the FBneo core. 

The FMV right after the attract mode (VS screen) anytime Thunder is a player or cpu character causes a glitch to occur and freezes the VS screen. The game only freezes as I can still reset it.

Also, during fights, using Orchid causes the game to freeze as well and she shows no animation when any action is pressed,

I tested FBneo in RA 1.8.5 as well
 and had the same issues.

Works fine with all other characters and in the Mame current in RetroArch. 

![thunder](https://user-images.githubusercontent.com/22628415/85649417-c2d7d480-b668-11ea-9f09-69de1f1a1245.PNG)

**Comment by barbudreadmon** [comment]
Support for those games was removed yesterday : https://github.com/libretro/FBNeo/commit/b76bbb4dd697af0776e9534dc724ca94f71f4035
Closing
