### ISSUE TITLE
Android Compile Issue

### ISSUE THREAD

**Issue by webgeek1234** [libretro/FBNeo#369]
I've been trying handle these errors myself as much as I can, but this one is a bit out of my knowledge. Build log:
https://gitlab.incom.co/libretro/FBNeo/-/jobs/37611

Specifically the part that says:
```
error: character ' ' cannot be specified by a universal character name
```

Seems there's two strings in there that the Android fortification flags are marking as invalid.

**Comment by barbudreadmon** [comment]
Your report was a bit late, it was fixed with https://github.com/libretro/FBNeo/commit/425a39b8fb83406eb9188085452933c065d11fe7 :)

**Comment by webgeek1234** [comment]
Yeah, so I noticed when builds completed a few minutes ago. Was going through my builds from last night when I reported it. Well then, don't mind me. :P
