### ISSUE TITLE
RunAhead disables hiscore.dat functions

### ISSUE THREAD

**Issue by TesterNes** [libretro/FBNeo#37]
Os: Windows 10.
Software: Retroarch 1.7.7 64 bits
core version: FinalBurn Neo v0.2.97.44 490d1fb
rom tested: 1941j.zip

Hiscore will be saved (1941j.hi) only if Runahead is completely disabled from retroarch. 

Keep up the good work and thanks for this "ultimate" Final Burn.

**Comment by barbudreadmon** [comment]
https://github.com/libretro/RetroArch/issues/8571
Closing

**Comment by barbudreadmon** [comment]
@TesterNes i also transfered the first report about this issue from the deprecated fbalpha repo : https://github.com/libretro/FBNeo/issues/52
