### ISSUE TITLE
Atari Gauntlet II (gaunt2) cannot play beyond level 1

### ISSUE THREAD

**Issue by roslof** [libretro/FBNeo#393]
**Summary:**
There are multiple Exits in Level 1. Using any exit results in impossible game boards.

**FinalBurn Neo Version Tested***
v0.2.94.44 (commit 706d8ae)
*Note: Tested version does not suggest issue was introduced with this version.

**Current Behavior**
Taking any exit will result in either a crash, freeze or visually broken game board.

**Expected Behavior**
(Reference MAME 0.220 for correct behavior)
Levels beyond level 1 should load properly.

**Comment by barbudreadmon** [comment]
Same question as gauntlet, i can't reproduce this one either

**Comment by barbudreadmon** [comment]
Same issue as gauntlet, fixed
