### ISSUE TITLE
Diamond Run (diamond) gameplay music and SFX are missing.

### ISSUE THREAD

**Issue by roslof** [libretro/FBNeo#396]
**Summary:** Diamond Run is a Boulder Dash-like game. While playing, music and SFX should play.

**Test Device:** Raspberry Pi 4B (4GB)

**Steps:**  1. Add Credit (audio will be heard). 2. Press Start button. 3. Observe audio

**Results:**  Gameplay music and SFX are missing.

**Expected Results:**  Reference lr-mame-2016 version for an example of correct behavior (lr-mame works, but has audio pops/misses)

**Comment by barbudreadmon** [comment]
fixed by https://github.com/libretro/FBNeo/commit/3442cfe9a0b9b9fb7548fc0e3774fcab7e92f032 , thanks for the report !
