### ISSUE TITLE
Demon Front segfaults in 7z format

### ISSUE THREAD

**Issue by Sanaki** [libretro/FBNeo#399]
This was momentarily talked about in #271. I've rebuilt the archive a few times, both solid and not, for some reason this game and only this game (and its clones) is segfaulting in 7z format. Strangely enough, it can load -if- dmnfrnt.zip is present and intact alongside it, so while I don't know why, it appears FBNeo is successfully loading the files from the 7z, then is attempting to access them from a zip that may not exist. I did verify that when loaded from 7z, the logs show successfully checking all files. I also verified that if the zip is emptied but present, the 7z will still segfault.

System: Linux Mint 19.3 x86_64
Retroarch: 1.8.9 libretro/RetroArch@03c7403
FBNeo: 8a25bb4 (rebuilt minutes before this issue was filed)

Independently verified by @bslenul on Windows 10.

**Comment by bslenul** [comment]
If it can be of any help (Windows 10): [crash-200714-184236.log](https://github.com/libretro/FBNeo/files/4920305/crash-200714-184236.log)

**Comment by barbudreadmon** [comment]
I can't reproduce this, try pming me on discord (barbudreadmon on FBNeo & libretro's discords)
