### ISSUE TITLE
Unable to open NeoGeo AES memcard manager in fbneo

### ISSUE THREAD

**Issue by rhester72** [libretro/FBNeo#415]
Now that the NeoGeo has proper memory card support (thank you VERY much!), only one issue seems to remain from perfect support.

On actual AES hardware, pressing A+B+C+D on power-on/startup brings up a memory card manager where you can format, copy, delete, and otherwise manage memory card data.

This is possible using UNIBIOS (with the same button sequence), but not currently with the AES BIOS.

NOTE: This functionality is definitely part of the Japanese AES BIOS (neo-po.bin) - I am not 100% certain if it is part of the English AES BIOS (neo-epo.bin) because I don't have access to one in real life (but I would assume so!).

**Comment by barbudreadmon** [comment]
If those buttons need to be pressed at boot time, then it might be a retroarch issue, it seems retroarch will ignore any button already pressed when starting a game.

@dinkc64 does that work on standalone ?
