### ISSUE TITLE
Lost Tomb (losttomb) missing 2nd joystick controls

### ISSUE THREAD

**Issue by roslof** [libretro/FBNeo#418]
**Summary:**
The Lost Tomb game supports separated movement of the player and directional firing via dual joysticks. Note that an additional action button is used for "magic" and does not fire the player gun. The player should use L-stick for 8-directional movement, R-stick for 8-way directional firing and the additional button for "magic" which removes walls around the player.

**Test Device:**
Raspberry Pi 4B (4GB) ARM

**lr-fbneo version**
1.8.8 - FinalBurn Neo (v0.2.97.44 8054409)

**Steps**:
1. Add Credit
2. Press Start button.
3. Wait until player avatar appears in a tomb/maze.
4. Attempt to fire a projectile

**Results:**
Player cannot fire in any direction with any control.

**Expected Results:**
The right stick should feature 8-way directional firing, similar to Robotron. You may reference lr-mame-2003 version for an example of correct dual-stick behavior.

**Recommendation**
Unlike Robotron, this game has an additional button for magic., By default, lr-mame2003 maps this to the gamepad B-button, which is not wise for their engine, since shooting down via R-stick is mapped to the B-button, causing unwanted activation of magic. Since the player will be using 2 joysticks, **I strongly recommend mapping magic to both L1 and R1 to the magic button.** Both of these buttons are easily accessible to the player, and they can choose which is easier to activate during gameplay.

**Comment by barbudreadmon** [comment]
Thanks for the report, fixed

> I strongly recommend mapping magic to both L1 and R1 to the magic button

While i totally agree with that, i won't add a hack for this one since it can easily be done through retroarch's remapping
