### ISSUE TITLE
Krull (krull) missing 2nd joystick controls

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#420]
**Summary:**
Krull game supports separated movement of the player and directional firing via dual joysticks. The player should use L-stick for 8-directional movement, R-stick for 8-way directional firing.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 3ee3337)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 8054409) 

**Steps:**
Add Credit
Press Start button.
Collect all Glaive pieces on the first stage to progress to stage 2 (very easy, takes less than a minute)
On stage 2, attempt to fire Glaive projectile in any direction

Results:
Player cannot fire in any direction with any control.

Expected Results:
The right stick should feature 8-way directional firing. lr-mame2003-plus has the correct behaviour. I assume other MAME versions do as well.

**Comment by barbudreadmon** [comment]
fixed by https://github.com/finalburnneo/FBNeo/commit/5d81d333e36a7806cc37c87981774e4246b17349
