### ISSUE TITLE
Line of Fire / Bakudan Yarou (loffire) freezes at startup.

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#425]
**Summary:**
Game freezes at startup.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 3ee3337)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 8054409)

**Steps:**
Just load the ROM.

**Results:**
Small amount of garbage appears at top of screen. Coin sound plays when coin is entered. Nothing else happens. Same behaviour on both ARM and x64.

**Expected Results:**
Game should progress to lightgun calibration screen and upon pressing both missile buttons should load to attract screen and be playable. See MAME 0.222 for correct behaviour.

**Comment by dinkc64** [comment]
thanks for letting us know, a fix has been checked in and should be available shortly.

best regards,
- dink

**Comment by barbudreadmon** [comment]
fix backported to the hybrid musashi/cyclone interface with https://github.com/libretro/FBNeo/commit/f17b93817f9d776b373a2ed425ca2c712f6cfb7c

**Comment by adelpha** [comment]
Progress, of a sort. Now the game starts as it should, but firing the gun does not damage the enemies in-game.

The gun firing sound plays (quietly), but the enemies never take damage or react in any way. The secondary fire (grenade launcher) seems to work as expected

Also, I'm unable to modify anything in the diagnostic mode (accessed by holding Start) because it wants me to press the Service and Test buttons, and those don't seem to exist.

**Comment by dinkc64** [comment]
everything working fine on the main branch, although someday when things are a little slow I'll have the game automatically calibrated to save people the hassle.

**Comment by barbudreadmon** [comment]
> Also, it freezes at startup with Cyclone enabled, but I'm guessing that's expected?

yes, cyclone is hit or miss
