### ISSUE TITLE
Michael Jackson's Moonwalker (World, FD1094/8751 317-0159) (mwalk) freezes at startup.

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#429]
**Summary:**
Game freezes at startup.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 282f38f)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 f17b938)

**Steps:**
Just load the ROM.

**Results:**
Small amount of garbage appears at top of screen. Nothing else happens. Same behaviour on both ARM and x64. Also tried US bootleg version (mwalkud) to see if unprotected roms worked but it still just freezes.

**Expected Results:**
Game should be playable. See MAME 0.222 for correct behaviour.

**Comment by barbudreadmon** [comment]
Thanks for the report !

@dinkc64 it seems https://github.com/finalburnneo/FBNeo/commit/35dcacc31979a36e7a715d089e799b4280691c3f broke this one

**Comment by dinkc64** [comment]
thanks I'll have a look

**Comment by dinkc64** [comment]
sorry about that, it's fixed now!

p.s.fixing all of the problems that *the traitor* left for us is going to be a bumpy ride.  hold on to your seats :)

**Comment by adelpha** [comment]
Yep, works fine.  Crashes at startup with Cyclone, which is a shame since it would probably benefit from the speedup, but it's good to have it working anyway.

**Comment by barbudreadmon** [comment]
cyclone is provided as-is, and in this case it's a big no-no, system18 and megadrive require a special version of cyclone where several instructions act differently, most likely breaking any other m68k games.
