### ISSUE TITLE
Momoko 120% [Japan] (momoko) - fire not drawn, makes game unplayable.

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#431]
**Summary:**
The rising flames - a major gameplay element - are not visible.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 282f38f)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 f17b938)

**Steps:**
Just load the ROM, insert a coin and start the game.

**Results:**
Fire graphic is not drawn (or perhaps drawn behind the foreground layer?). This makes the game very difficult as you can't determine visually how much time you have left.
![momoko-200730-231031](https://user-images.githubusercontent.com/13021896/88980542-db688980-d2bb-11ea-9027-7e14d56f2389.png)

**Expected Results:**
Fire graphic should be drawn over lower part of screen and slowly rise as game progresses. See MAME 0.222 for correct behaviour.
![momoko_mame_0222](https://user-images.githubusercontent.com/13021896/88980553-e02d3d80-d2bb-11ea-970d-91a88b034f0c.png)

**Notes:**
MAME 0.222 also cuts off the lowest line of "floor" tiles. I assume this is correct, but I don't know.

**Comment by dinkc64** [comment]
Thanks for letting us know, the problem is fixed as well as a few other bugs in this emulation.

best regards,
- dink

**Comment by adelpha** [comment]
Yep, fixed. Thanks!
