### ISSUE TITLE
Super Spacefortress Macross 2 (macross2) - audio channel inaudible

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#436]
**Summary:**
The melody in the intro is being drowned by other channels. Probably other sounds too.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 282f38f)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 f17b938)

**Steps:**
Just load the ROM and listen to the intro and demo.

**Results:**
[macross2_fbneo_rpi3.zip](https://github.com/libretro/FBNeo/files/5004001/macross2_fbneo_rpi3.zip)

**Expected Results:**
[macross2_mame_0222_x64_(dc_offset).zip](https://github.com/libretro/FBNeo/files/5004003/macross2_mame_0222_x64_.dc_offset.zip)

**Notes:**
Looking over the MAME history for this rom, it seems the audio is still not considered 100% accurate, which is pretty obvious just from listening to it. The audio, as emulated in MAME 0.222 has a huge negative DC offset, but for all I know that's how the actual hardware worked. Regardless, the audio in MAME 0.222 is almost certainly more accurate than in FBNeo.

**Comment by dinkc64** [comment]
thanks for letting us know, it should be alright now :)

**Comment by adelpha** [comment]
Yep, confirmed fixed.
