### ISSUE TITLE
Armed Police Batrider Slow Music

### ISSUE THREAD

**Issue by OperationWalker** [libretro/FBNeo#44]
First of all, thank you for continuing development as FBNeo. I noticed that "Let's Ass Kick Together" which is boss stage music, is slower than arcades etc. Is this on intentional like TAITO F3? If you don't mind, could you make it the same speed as the original? Thanks

**Comment by barbudreadmon** [comment]
There is actually a dipswitch called "music tempo" in core options, it was added a few days ago in https://github.com/libretro/FBNeo/commit/663b32812d63212eac5a2f716cdff52e4e05d614. See original issue at https://github.com/finalburnneo/FBNeo/issues/33 .

**Comment by OperationWalker** [comment]
There was a music tempo dipswitch in the Darius Gaiden of TAITO F3, but not in the Armed Police Batrider. The core used is [04d168c](urlhttps://github.com/libretro/FBNeo/commit/04d168c5e912b21adc66dc555b2deee94fa5f414).

**Comment by barbudreadmon** [comment]
Nevermind, actually it's not a TAITO F3 game, it's a TOAPLAN game. There is indeed no such dipswitch for TOAPLAN games.
Let's tag @dinkc64 about this.

**Comment by OperationWalker** [comment]
Thank you for your support.

**Comment by Awakened0** [comment]
Huh, I tested this game a fair bit when I initially started playing around with this core, and didn't notice the difference. Checking again the BGM does seem ever so slightly slower in FBN compared to MAME. The slowness in Rayforce was much more obvious.

**Comment by dinkc64** [comment]
Hi,
The speed of "lets kick ass together" in Batrider is exactly the same in FBN as Mame .209 (I bet the current version .210 is the same)
here's the visual proof:
![batrider_letskickasstogether_mamevsfb](https://user-images.githubusercontent.com/12570148/58768720-74dbc480-856d-11e9-9bf5-a80f709d0af4.png)

p.s. we try to emulate the sound exactly how it should be, the only reason Taito f3 stayed slow for so long is because I totally forgot about it:)

best regards,
- dink

**Comment by Awakened0** [comment]
I may have placebo'd myself into thinking it was different then. I'll trust @dinkc64 and the waveform on this one.

**Comment by OperationWalker** [comment]
I completely forgot that Run-Ahead slows down music for some titles (such as Fire barrel, X-Multiply). With RunAhead Use Second Instance enabled, the speed is the same as the original. I'm really sorry. It's completely my fault. I would like to thank you for your help with barbudreadmon and Awakened0, and verification for dinkc64.

**Comment by barbudreadmon** [comment]
Closing then !

**Comment by dinkc64** [comment]
OperationWalker, it's ok :)  

best regards,
- dink

**Comment by barbudreadmon** [comment]
@dinkc64 If you are ever interested, here is some doc on how readahead works : https://docs.libretro.com/guides/runahead/
It would be nice to have something like that in standalone, it allows "arcade perfect" or even better input lag.
