### ISSUE TITLE
Ocean to Ocean (Medal) (DECO Cassette MD) (No. 10/Ver.1,Japan) - (cocean1a) - audio plays continuously

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#440]
**Summary:**
Sound effect when selecting win lines or winning credits plays continuously, resulting in an annoying constant beeping noise.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 282f38f)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 f17b938)

**Steps:**
Just load the ROM, insert lots of credits, select all the win lines and spin the wheels.

**Results:**
Pretty quickly the game will just start making a constant beeping sound.

**Expected Results:**
The sound effects when selecting lines or winning credits should play for an appropriate length of time. See MAME 0.222 for correct behaviour.

**Notes:**
Terrible games need love too.

**Comment by dinkc64** [comment]
thanks again for this bug report, this issue has been solved.  p.s. please comment on each of the bugs you have verified have been fixed, so we can close the issues.

best regards,
- dink

**Comment by adelpha** [comment]
Confirmed fixed for the, perhaps, two people who will ever play this.

**Comment by dinkc64** [comment]
The fix might benefit other deco cass-system games, though - there's about 45 of them - so that's a good thing :)
