### ISSUE TITLE
Runahead Second Instance does not work anymore with latest core ("Failed to load state" error)

### ISSUE THREAD

**Issue by Ryunam** [libretro/FBNeo#446]
With the latest core version downloaded from the buildbot, Runahead stops working upon loading any content if `Use Second Instance` is set to ON. RetroArch will print an error stating "Failed to load state. RunAhead has been disabled".

This appears to be something very recent, introduced between 06fe120 and the current codebase (02/08/2020). I have a backup of version 0.9.44.1 06fe120 and it works fine with Second Instance.

This is particularly important for people who use Runahead, as without Second Instance a few games will exhibit video and audio issues.

**Comment by Ryunam** [comment]
I took the time to do a bisect on this. I had to do a few skips here and there while bisecting, but the culprit appears to be 746d346e6acbb967ce91cc27084d29b8ba425573.

**Comment by barbudreadmon** [comment]
this commit in particular was about fixing some readahead issues with single instance, so i'm not sure why it breaks second instance

**Comment by barbudreadmon** [comment]
Actually, are there games that still require second instance ? We did lots of work on this over the last weeks

**Comment by Ryunam** [comment]
I remember noticing a few audio issues specifically with Battle Garegga and Gunbird among the ones I had tested, but I am not sure whether those specific issues were fixed with single instance. I would have to do more testing. 

Typically I have a core override set to use second instance at all times with Final Burn Neo, since at least until now it seemed to provide better compatibility / stability, and that's what led me to notice this error upon updating the core.

**Comment by barbudreadmon** [comment]
> I remember noticing a few audio issues specifically with Battle Garegga and Gunbird among the ones I had tested, but I am not sure whether those specific issues were fixed with single instance.

They were fixed, any other ?

**Comment by Ryunam** [comment]
Not that I know of, specifically, but once again this would require more testing on my part. If I end up finding other games exhibiting issues like the ones Gunbird and Garegga had, I will make sure to document them here.

Still, I think there's a fundamental problem here with Second Instance not working anymore. If you enable it even by mistake and then go to disable it after getting the "Failed to load state error", with the current FBNeo code Runahead will not work anymore (even single instance) unless you close content / quit RA.

**Comment by barbudreadmon** [comment]
Tbh, if it leads to people reporting issues with single instance instead of using the second instance workaround, it might not be so bad, nonetheless i fixed it with https://github.com/libretro/FBNeo/commit/d8a0b6711a60ae6e554757d06ff64230ac66e6b1

Thanks for the report.

**Comment by Ryunam** [comment]
Thank you so much for taking the time to fix it! Much appreciated.

I will definitely test Single Instance too from now on and report back in case I find some other issues with it.
