### ISSUE TITLE
[Input] Correct Button layout for some games

### ISSUE THREAD

**Issue by Immersion95** [libretro/FBNeo#454]
As of today, only Neo-Geo games have the possibility to use the "Modern" layout, would it be possible to enable it for all of the 4-buttons games ?

There also could be some exceptions for : 

jojo
jojoba

These 2 could use the PSX/DC layout.

**Comment by barbudreadmon** [comment]
Well, i'll be honest, i use modern and don't want any of the changes you are suggesting, and while modern obeyed a certain logic for revised gameplay in ongoing fighting games franchise, i can't see that logic applying for jojo/jojoba (the only reason for different mapping on those systems is because of their controller's physical layout) or any other 4-buttons game.

**Comment by Immersion95** [comment]
> Well, i'll be honest, i use modern and don't want any of the changes you are suggesting, and while modern obeyed a certain logic for revised gameplay in ongoing fighting games franchise, i can't see that logic applying for jojo/jojoba (the only reason for different mapping on those systems is because of their controller's physical layout) or any other 4-buttons game.

I was suggesting that JoJo games would use the PSX layout instead of the clockwise ABCD layout.

**Comment by barbudreadmon** [comment]
Could you develop on the jojo/jojoba issue on gamepad ? I don't see the problem, what's the mapping on DC/PSX for those games ?

For the other ones, that's a definitive no, i don't see how a 4-button game like ddsom would benefit from it, it would only serve at bothering people who are used to the current layout with modern.

**Comment by Immersion95** [comment]
I could also make a list of 4 button games where it would be useful (like Power Instinct, SVG, etc...), would you accept it for those games :) ?

Regarding JoJo, here is [more information](https://jojoban.fandom.com/wiki/Controls_%26_Notations_Guide)

![Hftf_pad](https://user-images.githubusercontent.com/47425204/89435822-ab026e80-d745-11ea-90c5-69d01bef2543.jpg)

**Comment by barbudreadmon** [comment]
Done for jojo/jojoba, i was thinking the current default layout was following the arcade, but it turns out it was already wrong.
For any other game, i'll consider it if you make a valid statement, like the game actually having such layout on a modern platform.

**Comment by Immersion95** [comment]
Thanks a lot !

Let me do the homework for the other games, I'll try to trace all of them.

There are also 6 button layout games which are wrong by the way :

- kaiserkn
- fghthist

They should have the same Street Fighter mapping.

**Comment by barbudreadmon** [comment]
Those 2 games didn't have the Weak/Medium/Strong Punch/Kick button labels, which is why they weren't recognized for the sf2 layout, thanks for letting me know, it should be ok now.

**Comment by Immersion95** [comment]
Thanks :), I also updated the title.

**Comment by Immersion95** [comment]
So regarding my investigation : 

1. Power Instinct games should follow this layout : 

	3
1		4
	2

- powerins
- pwrinst2
- plegends

Why ? 

- Power Instinct was only ported to the SNES/Megadrive. It instead has a 6-button layout (borrowed from Street Fighter) which is close to this one when translated to 4-buttons.
- Power Instinct 2 was only ported to the PSX. It uses this layout.

2. Spectral vs Generation (svg) should have this layout : 

	2
1		3
	4

Why ? SVG was only ported to the PS2/PSP. It uses this layout.

3. Rabbit (rabbit) should follow this layout : 

	2
1		4
	3

Why ? Rabbit was only ported to the Saturn. It uses this layout.

**Comment by barbudreadmon** [comment]
Done => https://github.com/libretro/FBNeo/commit/7c032d15c5705954e411f49bb9542075b345e633

powerins & co => arcade actually uses the same layout than snes/md
svg => arcade uses a straight line of 4 buttons, so its layout doesn't really matter, let's use the one from from psp/ps2
rabbit => i couldn't find anything about this one's arcade layout, so let's go with the one from saturn

Those 3 changes were applied to both classic and modern

**Comment by Immersion95** [comment]
For Rabbit, i didn't find anything. I had to try the game directly.

Merci beaucoup :) (je crois que tu parles aussi français ?)

**Comment by barbudreadmon** [comment]
De rien

**Comment by Immersion95** [comment]
I also wanted to know if it would be possible to add games that don't have ports but would benefit greatly from his layout ?

------2
1----------4
------3

Why ? It's a straight line of 4 buttons - LP, HP, LK, HK

bloodwar
daraku
drgnmst
shogwarr
tkdensho

**Comment by barbudreadmon** [comment]
I'll be back home monday and i'll take a look

**Comment by barbudreadmon** [comment]
The change is done (actually i found evidence that the first 3 games are played with punches on top in arcade cabinets), however with the buildbots currently dead you'll have to wait except if you build the core yourself.

**Comment by Immersion95** [comment]
It works, thanks a lot !

I also wanted to modify the modern layout for some Neo-Geo games (Samurai Spirits, etc...), do you know if it would be accepted ?

**Comment by barbudreadmon** [comment]
> do you know if it would be accepted ?

as i said i'll consider anything as long as you make a valid statement, it'll be a hard one though

**Comment by Immersion95** [comment]
1. These NeoGeo games follow this pattern : A-B-C-D = LP-HP-LK-HK

doubledr
kabukikl
karnovr
ninjamas
samsho
samsho2
wakuwak7
whp

This layout suits those games well : 

------2
1----------4
------3

2. Those NeoGeo games follow this pattern : A-B-C-D = LP-MP-HP-K

samsho3
samsho4

Samurai Spirits Tenkaichi & Samurai Spirits 2019 which have the same button configuration use this layout which is the best to my knowledge : 

------2
1----------3
------4

3. Galaxy Fight follow this pattern : A-B-C-D = Light-Medium-High-Taunt

The PSX version of this game use this layout : 

------4
1----------3
------2

I do think though that this layout is better and is more "universal" across games (JoJo, SVG, Samurai Spirits) : 

------2
1----------3
------4

4. Those NeoGeo games follow this pattern : A-B-C-D = LP-MP-K-Special

samsho5
samsh5sp

Samurai Spirits 5 on the PS2/XBOX use this layout : 

------2
1----------3
------4

5. Those NeoGeo games follow this pattern : A-B-C-D = LP-MP-K-Repel

lastblad
lastbld2

Now those 2 games have button layouts all over the place on the different ports (DC & PS2 isn't the same) : 

DC : 

------4
2----------3
------1

PS2 : 

------3
1----------4
------2

I do think that both aren't great and that it should be like this : 

------2
1----------3
------4

**Comment by barbudreadmon** [comment]
tbh i don't think i'll do any of this, and will just restrict the "modern" layout to kof games instead of all fighting games,the reasons : 
- it was my original intention, i only wanted to match the kof serie layout from psx onward since it was the only serie that really kept going, i ended up enlarging it to all fighting games because someone requested it but as i already suspected at that time it was a bad idea, because those games with modern layout actually don't match anything existing
- the "classic" layout is how those games are played on real hardware with the official neogeo gamepad
- i don't think any of the layouts you are proposing is objectively better than the original, furthermore there are errors in there, `doubledr`'s has totally different layout from a character to another, sometimes you get 3P+1K, sometimes you have P at bottom, sometimes at top, etc...

I might consider adding a normalized modern layout for all samshos though, with samsho 2019 as model

**Comment by Immersion95** [comment]
> * `doubledr`'s

I don't think that there are errors apart from doubledr though but I would gladly be corrected as I also need those information :)

Regarding the layouts that I proposed, I disagree with you about these : 

- All of the Samurai Spirits ones are the one used from the official ports
- Waku Waku 7 in Saturn use this same layout
- Galaxy Fight can at least be changed to the PSX layout

For Last Blade games, there is not a definite answer so it's better to leave it like this.

There also can be a statement regarding the NeoGeo mini which use a "Modern" Layout for all of its games : 

------3
1----------4
------2

I still think that "Modern" should match the new direction that SNK chose for the NeoGeo mini pad for all the games and that "Modern" shouldn't be an hybrid configuration.

I just wanted to add that I'm not correcting the layouts for myself as I already know how to do it and did it. I just wanted to make the experience easy enough for people that won't go through all of these configuration and make it as friendly as possible :)

I think that I will try to check the layouts for the ports of the other games like Karnov's Revenge if you are still i,terested in this issue.

Thanks a lot for your help and the time you take @barbudreadmon !

**Comment by barbudreadmon** [comment]
> I still think that "Modern" should match the new direction that SNK chose for the NeoGeo mini pad for all the games and that "Modern" shouldn't be an hybrid configuration (I know that you already refused :p)

Actually, i don't remember it was ever mentioned that neogeo mini pad and arcade stick pro were using that layout, i just learned about this (it seems i missed that part the first time i read your post) and it's a very sound argument, change is done, now modern affects all neogeo games.

**Comment by Immersion95** [comment]
It's solved then :)
