### ISSUE TITLE
Crush Roller (Kural Samno) - crush - continuous high-pitched beep while entering initials at hiscore table.

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#460]
**Summary:**
Constant annoying high-pitched beep while entering initials at high score table.

Also, the following message is logged by RA when you start the game:

> Default value for '[Dipswitch] First Pattern' not found, it's a bug, please report it

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Achieve a score that gets you on the high score table.

**Results:**
As soon as the high score entry screen appears, the game will just start making a constant beeping sound.

**Expected Results:**
All audio should stop while the high score entry screen is visible. See MAME 0.222 for correct behaviour.

**Notes:**
Incoming!!! ;)

**Comment by barbudreadmon** [comment]
That's pretty bad timing, i'll be gone for a week, but thanks for all the reports anyway.

**Comment by adelpha** [comment]
Heh, no rush. Enjoy your time off!

**Comment by dinkc64** [comment]
this one was actually caused by the same problem as ponpoko, thanks for all these great bug reports :)

best regards,
- dink

**Comment by dinkc64** [comment]
@barbudreadmon,
going to leave this one open for the dips issue:  Not sure what's the issue here.
"Default value for '[Dipswitch] First Pattern' not found, it's a bug, please report it"

**Comment by barbudreadmon** [comment]
@dinkc64 that's a warning i implemented after the hustle issue : https://github.com/libretro/FBNeo/issues/416 , basically it means `(pgi->Input.Constant.nConst & bdi.nMask) == bdi.nSetting` is never true for that dips, does this dips work on standalone ?

**Comment by dinkc64** [comment]
aha, that's it!  thanks - there is a typo in the dip list after all :)
