### ISSUE TITLE
Dark Planet [Dial doesn't work very well] - darkplnt - screen is inverted

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#461]
**Summary:**
Screen is inverted.

Also, the note in the DAT about the dial is very accurate ;)

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the ROM.

**Results:**
Screen is inverted.

**Expected Results:**
Screen should be the correct orientation.

**Comment by barbudreadmon** [comment]
it seems this one was fixed one month ago and we totally forgot about it

**Comment by adelpha** [comment]
Yep, the screen is the correct orientation now. Thanks!

It's still completely unplayable though. I tried an xbox360 controller and also a trackball. With the 360 controller the ship just turns spasmodically, while the trackball does absolutely nothing.

It's not a good game anyway, so I don't really care. 😁

**Comment by dinkc64** [comment]
the dial is fixed now
