### ISSUE TITLE
Dragonball Z (rev B) - dbz - game speed is too slow

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#462]
**Summary:**
The game runs slowly, but not as if it's struggling to emulate at full speed. Instead, it's as if there's a bug causing the game to run at the incorrect speed.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the ROM and start the game.

**Results:**
Game seems to run at about 50% of the speed it should. Results are consistent on both RPi and x64.

**Expected Results:**
Game should run at the correct speed.  See MAME 0.222 for correct behaviour.

**Comment by dinkc64** [comment]
thanks, this one is fixed now :)
