### ISSUE TITLE
Hustle (Gremlin, 1977, Blockade hardware) - hustle - audio is incorrect

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#463]
**Summary:**
Sound effects don't match MAME.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load ROM. Start game. Listen.

**Results:**
Tones while moving in the 4 directions are much lower than in MAME. There is no sound effect when picking up a mystery target that has a negative score attached.

**Expected Results:**
Reference MAME 0.222 for correct behavior (or at least, more correct). Tones while moving in the 4 different directions should be higher pitched. There should be a sound effect played when recieving a negative score from a mystery target.

**Comment by dinkc64** [comment]
some games can't match mame due to how they emulate analog circuitry with netlist (for example, late 70s games), so we try to match the best we can using sound synthesis techniques.  I'll see what can be done about the missing sounds and possibly getting it to match better., thanks :)

**Comment by adelpha** [comment]
Great, thanks!

**Comment by dinkc64** [comment]
Hi,
I updated hustle / fixed sounds & pitch and added phosphor color selection to dip selection.

best regards,
- dink

**Comment by adelpha** [comment]
Awesome, it's much better now. Thanks!
