### ISSUE TITLE
Operation Wolf 3 (World) - opwolf3 - unable to calibrate lightguns on RPi only

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#464]
**Summary:**
X-axis doesn't seem to work, at least as mapped to the x360 controller.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Set the dipswitch and enter setup mode to perform calibration. You can see the X-axis seems to be locked to a value of 330 when setting the minimum position, and 0 when setting the maximum. None of the controls affect the X-axis.

The Y-axis appears to behave normally.

Importantly, this bug doesn't affect the Windows 10 x64 build. On that platform, the guns seem to be automatically calibrated on first start, and if you set the dipswitch and enter setup mode manually, both axes perform normally in calibration.

**Results:**
On RPi, moving the analog stick only affects the Y-axis.

**Expected Results:**
On RPi, Moving the analog stick should affect both axes.

**Comment by barbudreadmon** [comment]
should be ok after https://github.com/finalburnneo/FBNeo/commit/7b32c6373750890d909e2cb35543ea5c70778774 is merged

**Comment by adelpha** [comment]
Confirmed fixed.
