### ISSUE TITLE
Orbitron - orbitron - screen is inverted

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#465]
**Summary:**
Screen is inverted.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the ROM.

**Results:**
Screen is inverted.

**Expected Results:**
Screen should be the correct orientation.

**Comment by barbudreadmon** [comment]
should be ok when https://github.com/finalburnneo/FBNeo/commit/2a535f6bc6ceee901d7acc98a0b3b84df7c71c50 is merged

**Comment by adelpha** [comment]
Confirmed fixed.
