### ISSUE TITLE
Penguin Brothers (Japan) - penbros - Stage transition zoom not implemented

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#466]
**Summary:**
During stage transitions, there should be a full-screen zoom effect. This is not currently emulated in FBNeo but has recently been emulated in MAME.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the rom, start the game, complete a stage.

**Results:**
The screen scrolls strangely to the top-left instead of stretching/scaling.

**Expected Results:**
The screen should zoom into the centre during stage transitions. See: https://www.youtube.com/watch?v=WJtkXdnTC-c

**Comment by dinkc64** [comment]
@barbudreadmon, this one has your name on it :)

**Comment by barbudreadmon** [comment]
ok, i'll take a look when i'll be back :)

**Comment by barbudreadmon** [comment]
the fix is on github !

**Comment by adelpha** [comment]
Looks great! Thanks again.
