### ISSUE TITLE
Ponpoko - ponpoko - Player step sound effect plays continuous tone when player stops walking

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#467]
**Summary:**
Game plays intermittent beeping noise while player is moving. Around 50% of the time, when the player stops moving the beep continues to play as a constant tone.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the rom, start the game, walk left or right.

**Results:**
Around 50% of the time, the sound will continue while the player is stopped.

**Expected Results:**
Sound effect should stop when player stops.

**Comment by dinkc64** [comment]
thanks again for another good bug report, the problem is solved :)
