### ISSUE TITLE
Defend the Terra Attack on the Red UFO - redufo - screen is inverted

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#468]
**Summary:**
Screen is inverted.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the ROM.

**Results:**
Screen is inverted.

**Expected Results:**
Screen should be the correct orientation.

**Comment by barbudreadmon** [comment]
should be fixed after https://github.com/finalburnneo/FBNeo/commit/3425c2da863596ba4828a0c22bf9e1f7199374b0 is merged

**Comment by adelpha** [comment]
Confirmed fixed.
