### ISSUE TITLE
Shackled (US) - shackled - cannot continue when prompted

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#469]
**Summary:**
Pressing Start when prompted to continue after dying does not work.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the ROM.

**Results:**
Pressing Start during the Continue countdown does nothing. The continue timer inevitably counts to 0 and the game ends.

**Expected Results:**
Pressing Start during the Continue countdown should continue the game.

**Comment by dinkc64** [comment]
notes: this is actually an emulation bug, it happens in every emulator that emulates the game - although a patch can be made to work around the problem.  It's on the todo list :)

**Comment by dinkc64** [comment]
a patch has been made to work around the problem, thank you for the report!
