### ISSUE TITLE
Subroc-3D (US) - subroc3d - player has infinite lives and credits

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#470]
**Summary:**
The player has infinite lives and credits. I've tried setting the Free Play dipswitch on and off but there's no effect.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the ROM. Start the game. 

**Results:**
Notice that you don't have to deposit a coin to start the game. Lose a life; notice that you still have 3 lives.

**Expected Results:**
Player should have to deposit coins to start the game and should lose lives when killed.

**Comment by barbudreadmon** [comment]
confirmed, maybe that's normal behavior but i also noticed :
- "up" doesn't always work
- palette change from time to time (it might be different time of day ?)

**Comment by adelpha** [comment]
Yeah I dunno about the "up" control not working, but I think the palette change is supposed to represent time of day as you said, and it tends to flash when you hit something too.

**Comment by dinkc64** [comment]
up works here, it's just that the controls are reversed in this game for some reason... :)

**Comment by adelpha** [comment]
The original cab had a periscope thing that you looked through. It used spinning shutters synced to the monitor to generate a 3D image. Maybe turning the handle on the periscope right actually contacted a switch on the left or something?

![6807702041_60f357cf1a_o](https://user-images.githubusercontent.com/13021896/89792139-1076a680-db1c-11ea-877a-bb6b3d4243a9.jpg)

**Comment by dinkc64** [comment]
Yes, I'm with you there, great idea :)

**Comment by dinkc64** [comment]
Subroc 3d should be pretty solid now - I spent several hours tweaking this one to perfection today :)

best regards,
- dink

**Comment by adelpha** [comment]
Yep, well done. It plays great now :D
