### ISSUE TITLE
Tail to Nose – Great Championship - tail2nos - Graphical corruption in certain scenes

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#471]
**Summary:**
![tail2nos-200809-130646_bad](https://user-images.githubusercontent.com/13021896/89736002-46555580-da5e-11ea-8efc-cb986ba31acc.png) FBNeo ![tail2nos-200809-130646_good](https://user-images.githubusercontent.com/13021896/89736007-49504600-da5e-11ea-8681-430d71db7619.png) MAME

![tail2nos-200809-130624_bad](https://user-images.githubusercontent.com/13021896/89736010-4c4b3680-da5e-11ea-8e18-4ff090e08908.png) FBNeo ![tail2nos-200809-130624_good](https://user-images.githubusercontent.com/13021896/89736011-4d7c6380-da5e-11ea-91b8-2705145b123e.png) MAME

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the ROM. Start the game.

**Results:**
Graphical corruption of some tiles. See screenshots.

**Expected Results:**
See MAME screenshots.

**Comment by barbudreadmon** [comment]
confirmed

**Comment by dinkc64** [comment]
thanks - this one is now fixed as well :)
