### ISSUE TITLE
Ultraman (Japan) - ultraman - Graphical corruption in certain scenes

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#472]
**Summary:**
![ultraman-200809-150140_bad](https://user-images.githubusercontent.com/13021896/89736048-a51acf00-da5e-11ea-9705-ab44d168be0f.png)FBNeo![ultraman-200809-150140_good](https://user-images.githubusercontent.com/13021896/89736049-a64bfc00-da5e-11ea-87b7-b2b90904ea24.png)MAME

![ultraman-200809-145551_bad](https://user-images.githubusercontent.com/13021896/89736054-b06dfa80-da5e-11ea-8bbb-619f85e10a4e.png)FBNeo![ultraman-200809-145551_good](https://user-images.githubusercontent.com/13021896/89736055-b19f2780-da5e-11ea-81a3-31af22fbf093.png)MAME

![ultraman-200809-145709_bad](https://user-images.githubusercontent.com/13021896/89736061-b82d9f00-da5e-11ea-903d-4a5ef767d968.png)FBNeo![ultraman-200809-145709_good](https://user-images.githubusercontent.com/13021896/89736064-b95ecc00-da5e-11ea-908c-1fe0d9b0b594.png)MAME

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the ROM. Start the game.

**Results:**
Graphical corruption of some tiles. See screenshots.

**Expected Results:**
See MAME screenshots.

**Comment by barbudreadmon** [comment]
confirmed

**Comment by dinkc64** [comment]
thank you again for the nice bug report, this one is fixed (in main fbneo branch) :)
