### ISSUE TITLE
unknown Pac-Man gambling game - unkpacg - Incorrect colours and sounds

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#473]
**Summary:**

![unkpacg-200809-155058_bad](https://user-images.githubusercontent.com/13021896/89736102-f925b380-da5e-11ea-9011-644f6c25151b.png)FBNeo![unkpacg-200809-155058_good](https://user-images.githubusercontent.com/13021896/89736106-fa56e080-da5e-11ea-9352-003752036f81.png)MAME

Also, sounds tend to continue after they should have stopped.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the ROM. Start the game. Play a level.

**Results:**
Pac-man is cyan. Cyan!  Play a level and listen to the difference between FBNeo and MAME.

**Expected Results:**
See MAME screenshot for a nice yellow Pac-man. Listen to the audio in-game.

**Comment by barbudreadmon** [comment]
confirmed

**Comment by dinkc64** [comment]
this one is fixed now, thanks for the report :)
