### ISSUE TITLE
Ultra Toukon Densetsu (Japan) - utoukond - Loading ROM crashes RA

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#474]
**Summary:**
The game doesn't start at all. RA crashes and exits.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the ROM.

**Results:**
RA simply crashes back to EmulationStation on RPi. In Windows debug build it generates this crash log:

> -------------------
> 
> Error occurred on Sunday, August 9, 2020 at 16:03:18.
> 
> retroarch_debug.exe caused an Access Violation at location 000000001F0B7773 in module fbneo_libretro.dll Writing to location 0000000000000068.
> 
> AddrPC           Params
> 000000001F0B7773 00000000014AF420 00007FFD5D029C45 0000000000000000  fbneo_libretro.dll!ZetMapArea
> 000000001ED98F66 0010000000000000 004000063D50BBCD 000000001FFC4440  fbneo_libretro.dll!utoukond68kInit
> 000000001EDA1816 404E000000000000 000000001E20C67E 0000000000000000  fbneo_libretro.dll!DrvInit
> 000000001EDA3D3B 01D66E5E375171C4 0000000000000007 00000000000002D8  fbneo_libretro.dll!utoukondInit
> 000000001E2138A2 000000000000000F 0000000009AB8340 000000001AB94CC0  fbneo_libretro.dll!BurnDrvInit
> 000000001F297FBE 000000001B2FE3B0 0000000009AB856E 0000000000D2A242  fbneo_libretro.dll!retro_load_game_common
> 000000000044FE25 0000000009AB89E0 000000001B2FE3D9 0000000000001000  retroarch_debug.exe!core_load_game  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 39648]
> 0000000000464AD2 000000001B19E4A0 000000000126B9D8 000000001AB5B500  retroarch_debug.exe!content_file_load  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/tasks/task_content.c @ 1067]
> 0000000000465124 0000000009AB8B00 000000000126B9D8 000000001AB5B500  retroarch_debug.exe!content_file_init  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/tasks/task_content.c @ 1258]
> 000000000046776E 0000000001225060 0000000009AB8BEA 0000000009AB8C00  retroarch_debug.exe!content_init  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/tasks/task_content.c @ 2593]
> 0000000000419A7C 00000000102DC290 0000000001225060 0000000001242FF7  retroarch_debug.exe!event_init_content  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 14567]
> 000000000041A1FD 00000000102DC290 0000000001225060 0000000000000000  retroarch_debug.exe!command_event_init_core  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 14807]
> 000000000041C9B6 0000000000000029 0000000001225068 0000000000CEF249  retroarch_debug.exe!command_event  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 16062]
> 0000000000448CDD 000000000000000B 0000000009ABA3F0 0000000009ABA3F0  retroarch_debug.exe!retroarch_main_init  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 36289]
> 0000000000463DFF 0000000009ABA570 000000000126B9D8 0000000000001298  retroarch_debug.exe!content_load  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/tasks/task_content.c @ 604]
> 000000000046579B 000000000126B9D8 0000000009ABC7C0 0000000009ABA5F0  retroarch_debug.exe!command_event_cmd_exec  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/tasks/task_content.c @ 1458]
> 0000000000465F11 0000000009ABA7C0 0000000009ABC7C0 0000000009ABB7C0  retroarch_debug.exe!task_push_load_content_from_playlist_from_menu  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/tasks/task_content.c @ 1722]
> 0000000000701894 0000000009ABA7C0 0000000009ABC7C0 0000000009ABB7C0  retroarch_debug.exe!default_action_ok_load_content_from_playlist_from_menu  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/menu/cbs/menu_cbs_ok.c @ 1863]
> 00000000007029A7 0000000009ABEEB8 0000000009ABEFB7 0000000000000007  retroarch_debug.exe!action_ok_playlist_entry_collection  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/menu/cbs/menu_cbs_ok.c @ 2236]
> 0000000000405328 000000001AB9FCC0 0000000009ABEEA0 0000000000000000  retroarch_debug.exe!generic_menu_entry_action  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 4662]
> 00000000006A37E7 000000001AB9FCC0 0000000009ABEEA0 0000000000000000  retroarch_debug.exe!xmb_menu_entry_action  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/menu/drivers/xmb.c @ 7003]
> 0000000000407161 0000000009ABEEA0 0000000000000000 0000000000000005  retroarch_debug.exe!menu_entry_action  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 5363]
> 0000000000404F2E 0000000001225060 000000001AB99880 000000001AB9FCC0  retroarch_debug.exe!generic_menu_iterate  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 4584]
> 000000000040A01A 0000000009ABF9E0 0000002D9C5209FF 0000000009ABF940  retroarch_debug.exe!menu_driver_iterate  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 6963]
> 000000000044CF2F 0000000001225060 00000000102DC290 0000002D9C5209FF  retroarch_debug.exe!runloop_check_state  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 38416]
> 000000000044E94E 00000000102DC290 0000000001225060 0000000009ABFD30  retroarch_debug.exe!runloop_iterate  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 39003]
> 000000000041EBE1 0000000000000001 0000000009C90000 0000000000000000  retroarch_debug.exe!rarch_main  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 17228]
> 00000000005B81B7 0000000000000001 0000000009C90000 0000000009CB25EE  retroarch_debug.exe!SDL_main  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/ui/drivers/qt/ui_qt_application.cpp @ 151]
> 0000000000AC840E 0000000000000000 000000000000002B 000000000133FB60  retroarch_debug.exe!main_getcmdline
> 00000000004013B4 0000000000000000 0000000000000000 0000000000000000  retroarch_debug.exe!__tmainCRTStartup  [E:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 339]
> 00000000004014DB 0000000000000000 0000000000000000 0000000000000000  retroarch_debug.exe!WinMainCRTStartup  [E:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 195]
> 00007FFD5C1F6FD4 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
> 00007FFD5E1BCEC1 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart
> 
> retroarch_debug.exe
> ntdll.dll   	10.0.19041.207
> KERNEL32.DLL	10.0.19041.292
> KERNELBASE.dll	10.0.19041.388
> apphelp.dll 	10.0.19041.1
> ADVAPI32.dll	10.0.19041.1
> msvcrt.dll  	7.0.19041.1
> sechost.dll 	10.0.19041.388
> RPCRT4.dll  	10.0.19041.1
> comdlg32.dll	10.0.19041.329
> combase.dll 	10.0.19041.329
> ucrtbase.dll	10.0.19041.1
> shcore.dll  	10.0.19041.388
> USER32.dll  	10.0.19041.388
> win32u.dll  	10.0.19041.388
> GDI32.dll   	10.0.19041.1
> gdi32full.dll	10.0.19041.388
> msvcp_win.dll	10.0.19041.1
> SHLWAPI.dll 	10.0.19041.1
> SHELL32.dll 	10.0.19041.388
> ole32.dll   	10.0.19041.153
> SETUPAPI.dll	10.0.19041.1
> cfgmgr32.dll	10.0.19041.1
> bcrypt.dll  	10.0.19041.1
> WS2_32.dll  	10.0.19041.1
> COMCTL32.dll	5.82.19041.1
> DSOUND.dll  	10.0.19041.1
> DINPUT8.dll 	10.0.19041.1
> HID.DLL     	10.0.19041.1
> MSIMG32.dll 	10.0.19041.388
> IPHLPAPI.DLL	10.0.19041.1
> OPENGL32.dll	10.0.19041.1
> libwinpthread-1.dll	1.0.0.0
> WINMM.dll   	10.0.19041.1
> libass-9.dll
> libstdc++-6.dll
> avformat-58.dll	58.29.100.0
> libcaca-0.dll
> avutil-56.dll	56.31.100.0
> avcodec-58.dll	58.54.100.0
> cg.dll      	3.1.0.13
> cgD3D9.dll  	3.1.0.13
> cgGL.dll    	3.1.0.13
> libfreetype-6.dll	2.10.1.0
> Qt5Core.dll 	5.13.2.0
> libopenal-1.dll
> Qt5Network.dll	5.13.2.0
> CRYPT32.dll 	10.0.19041.21
> SDL2.dll    	2.0.10.0
> IMM32.dll   	10.0.19041.1
> OLEAUT32.dll	10.0.19041.388
> swresample-3.dll	3.5.100.0
> swscale-5.dll	5.5.100.0
> libusb-1.0.dll	1.0.23.11397
> powrprof.dll	10.0.19041.1
> winmmbase.dll	10.0.19041.1
> GLU32.dll   	10.0.19041.1
> exchndl.dll 	0.9.2.0
> PSAPI.DLL   	10.0.19041.1
> libssl-1_1-x64.dll	1.1.1.4
> libfontconfig-1.dll
> libharfbuzz-0.dll
> libfribidi-0.dll
> libgcc_s_seh-1.dll
> libbluray-2.dll
> libbz2-1.dll
> libmodplug-1.dll
> librtmp-1.dll
> libsrt.dll
> zlib1.dll
> libmfx-1.dll
> libcelt0-2.dll
> libgsm.dll
> liblzma-5.dll	5.2.4.0
> libmp3lame-0.dll
> libopencore-amrnb-0.dll
> libspeex-1.dll
> libopus-0.dll
> libtheoradec-1.dll
> libtheoraenc-1.dll
> libvorbisenc-2.dll
> libvorbis-0.dll
> libvpx-1.dll
> libwavpack-1.dll
> libwebpmux-3.dll
> libx264-157.dll	0.157.2970.0
> libwebp-7.dll
> libpng16-16.dll
> MPR.dll     	10.0.19041.1
> NETAPI32.dll	10.0.19041.1
> USERENV.dll 	10.0.19041.1
> VERSION.dll 	10.0.19041.1
> libicuuc65.dll
> libpcre2-16-0.dll
> DNSAPI.dll  	10.0.19041.1
> libzstd.dll
> libcrypto-1_1-x64.dll	1.1.1.4
> libexpat-1.dll
> libintl-8.dll	0.19.8.0
> USP10.dll   	10.0.19041.1
> libgraphite2.dll
> libxml2-2.dll
> libgmp-10.dll
> WSOCK32.dll 	10.0.19041.1
> libogg-0.dll
> mgwhelp.dll 	0.9.2.0
> libhogweed-5.dll
> dbghelp.dll 	10.0.19041.1
> dbgcore.DLL 	10.0.19041.1
> Qt5Widgets.dll	5.13.2.0
> Qt5Gui.dll  	5.13.2.0
> libiconv-2.dll	1.16.0.0
> libgnutls-30.dll
> libopencore-amrwb-0.dll
> libx265.dll 	3.2.0.1
> libopenjp2-7.dll
> xvidcore.dll
> libdouble-conversion.dll
> libnettle-7.dll
> libicudt65.dll
> libicuin65.dll
> libglib-2.0-0.dll	2.62.2.0
> dwmapi.dll  	10.0.19041.1
> UxTheme.dll 	10.0.19041.1
> libidn2-0.dll
> libtasn1-6.dll
> CRYPTBASE.DLL	10.0.19041.1
> NETUTILS.DLL	10.0.19041.1
> SRVCLI.DLL  	10.0.19041.1
> libp11-kit-0.dll
> libunistring-2.dll	0.9.10.0
> libpcre-1.dll
> libffi-6.dll
> UMPDC.dll
> ncrypt.dll  	10.0.19041.1
> NTASN1.dll  	10.0.19041.1
> CRYPTSP.dll 	10.0.19041.1
> rsaenh.dll  	10.0.19041.1
> bcryptPrimitives.dll	10.0.19041.264
> NSI.dll     	10.0.19041.1
> inputhost.dll	10.0.19041.388
> wintypes.dll	10.0.19041.329
> CoreMessaging.dll	10.0.19041.264
> PROPSYS.dll 	7.0.19041.1
> CoreUIComponents.dll	10.0.19041.1
> ntmarta.dll 	10.0.19041.1
> kernel.appcore.dll	10.0.19041.1
> dxgi.dll    	10.0.19041.1
> nvoglv64.dll	26.21.14.4575
> WTSAPI32.dll	10.0.19041.1
> DEVOBJ.dll  	10.0.19041.1
> WINTRUST.dll	10.0.19041.1
> MSASN1.dll  	10.0.19041.1
> cryptnet.dll	10.0.19041.1
> imagehlp.dll	10.0.19041.1
> gpapi.dll   	10.0.19041.329
> profapi.dll 	10.0.19041.1
> NvCameraWhitelisting64.dll	7.0.576.0
> dxcore.dll  	10.0.19041.1
> windows.storage.dll	10.0.19041.388
> Wldp.dll    	10.0.19041.1
> nvspcap64.dll	3.20.4.14
> nvcbl64.dll 	26.21.14.4575
> nvapi64.dll 	26.21.14.4575
> MSCTF.dll   	10.0.19041.388
> WINSTA.dll  	10.0.19041.1
> textinputframework.dll	10.0.19041.1
> xinput1_4.dll	10.0.19041.1
> clbcatq.dll 	2001.12.10941.16384
> deviceaccess.dll	10.0.19041.264
> explorerframe.dll	10.0.19041.329
> XAudio2_7.dll	9.29.1962.0
> MMDevApi.dll	10.0.19041.1
> resourcepolicyclient.dll	10.0.19041.388
> AUDIOSES.DLL	10.0.19041.264
> Windows.UI.dll	10.0.19041.264
> WindowManagementAPI.dll
> twinapi.appcore.dll	10.0.19041.388
> avrt.dll    	10.0.19041.1
> wdmaud.drv  	10.0.19041.1
> ksuser.dll  	10.0.19041.1
> msacm32.drv 	10.0.19041.1
> MSACM32.dll 	10.0.19041.1
> midimap.dll 	10.0.19041.1
> AppHook64_49595CB5-8098-4D6E-A457-9F2B5B670A61.dll	9.7.0.11
> fbneo_libretro.dll
> 
> Windows 10.0.19041
> DrMingw 0.9.2

**Expected Results:**
Game should start and be playable. See MAME 0.222 for reference.

**Comment by barbudreadmon** [comment]
backtrace : 
```
#0  ZetMapArea(int, int, int, unsigned char*) (nStart=0, nEnd=57343, nMode=0, Mem=0x7fffea1e5010 "\363\061") at ../../cpu/z80_intf.cpp:541
#1  0x00007fffec8aa262 in utoukond68kInit() () at ../../burn/drv/pst90s/d_seta.cpp:6179
#2  0x00007fffec8adb43 in DrvInit(void (*)(), INT32, INT32, INT32, INT32, INT32, INT32)
    (p68kInit=0x7fffec8aa0b1 <utoukond68kInit()>, cpu_speed=16000000, irq_type=513, spr_buffer=0, gfxtype0=0, gfxtype1=2, gfxtype2=2) at ../../burn/drv/pst90s/d_seta.cpp:7048
#3  0x00007fffec8b53cf in utoukondInit() () at ../../burn/drv/pst90s/d_seta.cpp:10399
#4  0x00007fffebfb7c69 in BurnDrvInit() () at ../../burn/burn.cpp:653

```

**Comment by dinkc64** [comment]
this is fixed, thank you! :)
