### ISSUE TITLE
Wacko - wacko - Joystick not available for mapping

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#475]
**Summary:**
Only the trackball seems to be available for control. An 8-way joystick should be used for shooting but doesn’t seem to be available.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)

**Steps:**
Load the ROM. Start the game.

**Results:**
You can move with the trackball control, but you cannot shoot because the joystick isn't available. See cabinet photo here: http://www.pixelatedarcade.com/pictures/6630

**Expected Results:**
You should use the trackball to move and the joystick to shoot.

**Comment by barbudreadmon** [comment]
It seems ok on my side (it uses left analog to move and dpad to shoot), maybe you set something into retroarch's "Analog to Digital Type" ? Anyway the game would probably be more playable as a dual stick game with shoot on right analog, leave the issue open so that i don't forget about it.

**Comment by barbudreadmon** [comment]
should be better with https://github.com/libretro/FBNeo/commit/93aa6372540df670d06d071b007b7f2dc3973466

**Comment by adelpha** [comment]
Confirmed fixed.
