### ISSUE TITLE
Top Speed (World) - topspeed - Accelerator range only seems to extend to 50%

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#476]
**Summary:**
Accelerator (and probably brake) seem to be analog inputs but only seem to have limited range.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game. See how the controller's inputs behave. You can see the actual values if you enable Service Mode and goto Input Test.

**Results:**
At least on the 360 controller, the triggers only have about half the range they should have. You cannot fully accelerate, which is ironic because this game is called Top Speed :D

**Expected Results:**
Analog controls should have their full range mapped to the full range of analog inputs for the controller.

**Comment by barbudreadmon** [comment]
it doesn't seem this game has analog controls hooked besides steering, instead it has 3 different kind of gas, with "Fire 1 (Gas)" having the highest value, "Fire 7" being the middle one and "Fire 5" being the lowest one, the same logic applies to brake. It seems arcade cabinet had analog pedals : http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=topspeed&search_id=2&lang=en

**Comment by adelpha** [comment]
Well, MAME's inputs have 3 analog inputs for Steering, Gas and Brake, plus a Nitro button and a Shifter (presumably a button but maybe a lever).

Sounds like the way it's setup now is a hack?

**Comment by dinkc64** [comment]
Thanks for the report, this has been fixed on the main branch of fbneo: support for analog accel/brake added in the deluxe and mini cab-type.

best regards,
- dink
