### ISSUE TITLE
Rescue - rescue - Moving and firing should be separate joysticks

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#478]
**Summary:**
Moving and shooting seem to be combined into one joystick. The real game uses two 8-way sticks, one for moving and one for firing, plus one button for the Sub Bomb.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game.

**Results:**
Shooting and moving are combined into one stick.

**Expected Results:**
Left stick is for moving. Right stick is for firing.

**Comment by barbudreadmon** [comment]
should be ok after https://github.com/finalburnneo/FBNeo/commit/14090bcf5a3dcb5ee602072a142eba2edb133c0f is merged

**Comment by adelpha** [comment]
Confirmed fixed.
