### ISSUE TITLE
The Tin Star (Set 1) - tinstar - sticks reversed

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#479]
**Summary:**
FBNeo seems to map right stick to movement and left stick to aiming. This is the opposite of what I'd expect, and the opposite of the real cabinet.

The real cabinet uses an 8-way rotary knob for aiming with a fire button on top, but even so it would make sense to swap the controls around.

![67974567_928492967483895_7740161444623973900_n](https://user-images.githubusercontent.com/13021896/89738588-d8b32480-da71-11ea-83e1-94560bf0924f.jpg)

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game.

**Results:**
Left stick aims, right stick moves.

**Expected Results:**
Left stick moves, right stick aims.

**Comment by barbudreadmon** [comment]
should be better with https://github.com/libretro/FBNeo/commit/93aa6372540df670d06d071b007b7f2dc3973466

**Comment by adelpha** [comment]
Confirmed fixed.
