### ISSUE TITLE
Sarge - sarge - joystick missing

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#480]
**Summary:**
This is a dual-stick game. One of the sticks doesn't seem to be present in FBNeo.

![31158303010_9764e7f4c1_o](https://user-images.githubusercontent.com/13021896/89739030-2c733d00-da75-11ea-84dd-5516d91c158c.jpg)

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game.

**Results:**
Only the left stick works.

**Expected Results:**
It's a tank game, so I'm guessing it's both sticks forward to go forward, etc.

**Comment by barbudreadmon** [comment]
should be ok after https://github.com/finalburnneo/FBNeo/commit/c698e52638951c616fcd426cf0ada6f0280bd3ea is merged

**Comment by adelpha** [comment]
Confirmed fixed.
