### ISSUE TITLE
Screw Loose (prototype) [Prototype] - screwloo - right stick missing

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#481]
Summary:
This is a dual-stick game. One of the sticks doesn't seem to be present in FBNeo.

From the descrption: "The left joystick moves Robop, while the right joystick fires. The joystick buttons activate Robop's Super!Charge that both speeds him up and shields him from attack."

Test Device:
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

Steps:
Load the ROM. Start the game.

Results:
Only the left stick works.

Expected Results:
Left stick moves, right stick fires.

**Comment by barbudreadmon** [comment]
should be ok after https://github.com/finalburnneo/FBNeo/commit/41941e276251090a79c9124fec31450bd87f553a is merged

**Comment by adelpha** [comment]
Confirmed fixed.
