### ISSUE TITLE
Star Guards - stargrds - Special weapon button missing

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#482]
**Summary:**
There should be a button to fire the Special Weapon but it's not present in FBNeo.

![stargrds](https://user-images.githubusercontent.com/13021896/89739187-7c063880-da76-11ea-8bd7-5324e00ec797.png)

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 039fcad)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game.

**Results:**
Sadness.

**Expected Results:**
Boom?

**Comment by adelpha** [comment]
Ah, I might be wrong here. The weapon button might also be the Start button.

**Comment by dinkc64** [comment]
thanks for letting us know - I changed the button names to "Px Start / Weapon" :)
