### ISSUE TITLE
B.Rap Boys - brapboys - ANINITARIZED ERROR on startup (RPi only)

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#483]
**Summary:**
Loading the ROM on RPi results in the following screen during POST:

![brapboys-200809-222655](https://user-images.githubusercontent.com/13021896/89742192-bcbe7b80-da8f-11ea-8292-f97d69ab7cae.png)

ANINITARIZED ERROR
SSP: 2419
PC: 00000032

The game will not progress beyond this error screen. This problem applies only to the RPi build. The x64 build starts and plays normally.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 06b8d57)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM.

**Results:**
See screenshot.

**Expected Results:**
Game loads and is playable.

**Comment by barbudreadmon** [comment]
most likely fixed by https://github.com/finalburnneo/FBNeo/commit/6118a173e414d91e9e8e16c4917c4be9a22cd447

**Comment by adelpha** [comment]
Confirmed fixed.
