### ISSUE TITLE
Bells and Whistles - blswhstl - Colours of non-ui elements too dark

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#484]
**Summary:**
The colours of everything that isn't on the UI layer - i.e. all backgrounds and sprites - are too dark.

![bells1bad](https://user-images.githubusercontent.com/13021896/89742522-9d751d80-da92-11ea-9cd0-79c300e68ce0.png)FBNeo  ![bells1good](https://user-images.githubusercontent.com/13021896/89742526-a5cd5880-da92-11ea-8784-7241d86291ac.png)MAME

![bells2bad](https://user-images.githubusercontent.com/13021896/89742535-aebe2a00-da92-11ea-8725-bc74d9241683.png)FBNeo  ![bells2good](https://user-images.githubusercontent.com/13021896/89742539-b4b40b00-da92-11ea-87db-31a24ee77c52.png)MAME

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 06b8d57)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Play the game.

**Results:**
See FBNeo screenshots.

**Expected Results:**
See MAME screenshots.

**Comment by dinkc64** [comment]
thanks for the report, it's fixed :)
