### ISSUE TITLE
Battle Zone (rev 2) [GFX/Sound Issues] - bzone - Juddery video output and other issues

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#485]
**Summary:**
Battle Zone has a few issues, but the most important one is that it just feels slow and jerky compared to MAME. It's running at the same framerate but it's definitely not as smooth.

This line from the MAME WIP log stands out: 

> 0.153: Derive (fake) refresh rate from CPU IRQ frequency to reduce juddering [Alex Jackson]. Changed VSync to 41.015625 Hz.

If this hasn't been implemented in FBNeo, would it be possible?

Apart from that, Battle Zone's vector lines look quite blurry in FBNeo and the sound isn't quite right. On the bright side, it is fully playable.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 06b8d57)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Play the game.

**Results:**
Juddery display draw.

**Expected Results:**
Smoother display draw.

**Comment by barbudreadmon** [comment]
The MAME 0.153 change was about changing refresh rate from 40 to 41.015625 (those are fake values, afaik vector games don't have a refresh rate), FBNeo has a refresh rate of 60 for this game so porting this 41.015625 change would only make the game slower.

Comparing with this [pcb video](https://www.youtube.com/watch?v=zdfKy4c7yuc), i can tell there is an issue with the hiscore screen in FBNeo, but i'm not convinced about the slow and jerky part. Maybe the problem here is that you are enforcing this game at 60Hz in MAME ?

**Comment by barbudreadmon** [comment]
Oh, it seems the issue was actually fixed by https://github.com/finalburnneo/FBNeo/commit/e8918b4565ed7dbbef3690330bedd3a0387d0054, which explains why i don't see it.

**Comment by adelpha** [comment]
Dink, in there with the sneaky fix. It's definitely smoother.

However, I see there's a DIP switch for "Hires Mode" but enabling it crashes the core. Is that a work-in-progress?

**Comment by dinkc64** [comment]
barbudreadmon, I fixed the jerkiness by setting it to 60fps, it was at 40.

**Comment by adelpha** [comment]
Enabling Hires Mode while it's running crashes the core. Disabling Hires Mode while it's running is fine though; it drops back to low res mode no problem.

Enabling Hires Mode in the config file and then running the game with it enabled works, but it's unplayably slow (around 25fps) on the Pi3B, which is probably to be expected.

**Comment by barbudreadmon** [comment]
> Enabling Hires Mode while the game is running crashes the core.

It doesn't happen on my desktop, do you have a crash too when enabling the widescreen mode through service menu in sfiii2 ?

**Comment by adelpha** [comment]
I'm not seeing that option in the service menu. I've looked through all the options and it doesn't seem to be there.

**Comment by dinkc64** [comment]
also try the hires mode of Tempest to help us find the problem. (or any other vector game)

best regards,
- dink

**Comment by adelpha** [comment]
Hires Mode in Tempest is fine. Can switch it on and off at will, no problems.

**Comment by barbudreadmon** [comment]
I did some tests on my pi3 and finally figured it out : `video_threaded` is set to `true` by default on retropie, this setting is unsafe and known for causing weird crashes, it's better to not use it if not required.

**Comment by dinkc64** [comment]
adelpha, thanks for doing these tests :)

**Comment by adelpha** [comment]
@barbudreadmon You're right about Threaded Video causing crashes, but even with it off, enabling Hires Mode in Star Wars results in a partially garbage screen. If you start the game from cold it's fine, but switching it while it's running just messes up the screen.

![starwars-200819-172758](https://user-images.githubusercontent.com/13021896/90663917-30a41500-e242-11ea-9278-d837ae052646.png)  Thread off, Lores  ![starwars-200819-172813](https://user-images.githubusercontent.com/13021896/90663958-40bbf480-e242-11ea-87b7-2d56e40c8bdc.png)  Thread off, Hires

@dinkc64  No problem. Thanks to both of you guys for fixing so many problems so quickly!

**Comment by barbudreadmon** [comment]
Hmm i think different devices are reacting differently to the same libretro api call (this garbage doesn't happen on my desktop), which looks like a RA issue, but i might have a fix in mind.

**Comment by barbudreadmon** [comment]
Not really an ideal solution since i have to make a libretro api call which is not recommended (it reinitialize video output), but https://github.com/libretro/FBNeo/commit/c9d53c4806dd6773663f3bab34eab7c985baf505 seems to do the trick, it also seems to prevent the crash with threaded video.

**Comment by adelpha** [comment]
If there are no adverse side-effects from using RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO, it's preferable to a crash. I'm just rebuilding to try it out now.
