### ISSUE TITLE
Complex X - complexx - Right stick missing

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#487]
**Summary:**
This is a dual-stick game. One of the sticks doesn't seem to be present in FBNeo.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 8ce2cd9)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game.

**Results:**
Only the left stick works.

**Expected Results:**
Left stick moves, right stick shoots.

**Comment by dinkc64** [comment]
notes: this is a ra/lr problem, works in fbneo

**Comment by barbudreadmon** [comment]
Right stick was mapped to p2, it should be better with https://github.com/finalburnneo/FBNeo/commit/e6686bdc445594b00765460c8cb6a40f89847b67

**Comment by adelpha** [comment]
Confirmed fixed. Thanks!
