### ISSUE TITLE
Wild Western (Set 1) -  wwestern - Right and left sticks swapped

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#488]
**Summary:**
FBNeo seems to map right stick to movement and left stick to aiming. This is the opposite of what I'd expect, and the opposite of the real cabinet.

The real cabinet uses an 8-way rotary knob for aiming with a Fire button on top, plus another button for Jump, but even so it would make sense to swap the controls around.

![wild_western_cabinet](https://user-images.githubusercontent.com/13021896/89795932-ebd0fd80-db20-11ea-9a46-1208aa2cab8d.jpg)

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 8ce2cd9)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game.

**Results:**
Left stick aims, right stick moves.

**Expected Results:**
Left stick moves, right stick aims.

**Comment by dinkc64** [comment]
Thanks for letting us know, a fix has been made.

best regards,
- dink
