### ISSUE TITLE
Calipso - calipso - Sounds loop and get cut off

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#489]
**Summary:**
The music at the end of a round continues to play over the next round, preventing any other sounds from playing.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 8ce2cd9)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game. Finish the level, allow the short musical jingle to play before firing again.

**Results:**
The last note played just continues.

**Expected Results:**
The music should stop and allow other sounds to play in the second level.

**Comment by dinkc64** [comment]
should be OK now, thank you :)
