### ISSUE TITLE
Scud Hammer - scudhamm - error at startup, unplayable

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#490]
**Summary:**
This is a weird one.

This is a Japanese rock-paper-scissors game.

On the real cabinet, when you win, a puppet head springs out of the cab, and you have to hit it with a plastic hammer as hard and as many times as you can.

In MAME that is simulated via an analog port (e.g. mouse position) that reports the effect of the hit on the accelerometer. With a 360 controller in MAME, the hammer is controlled by moving the left analog stick up and down.

The mechanical part of the machine doesn't seem to be emulated in FBNeo, so the game is unplayable.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 8ce2cd9)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM.

**Results:**
In FBNeo, the game doesn't start. The "MOTOR INITIALIZE" message is normal, but the Japanese warning text along with the constant "laser" firing sound is not normal, and with the magic of Google Translate I can tell it says something about "Danger!" and "Do not touch me!", so I guess this is what happens when the mechanical part of the machine fails.

![scudhamm-200810-1911062](https://user-images.githubusercontent.com/13021896/89817260-c43d5d80-db3f-11ea-80cb-7c5cf0d1863a.png)

**Expected Results:**
The game should start and be playable. See MAME 0.222 for reference.

**Comment by dinkc64** [comment]
@barbudreadmon, this game works in fbneo, can you check to see why its not working on your side?

**Comment by barbudreadmon** [comment]
Maybe the O3 optimization ? I'll take a look monday when i'll be back

**Comment by dinkc64** [comment]
From experience I learned that -O3 will only cause a problem:
if its a bug in the program w/heap/stack/memory overflow
-or- ancient compiler (gcc 3.x or earlier) with buggy O3

Since it's a new driver, it might need an asan/ubsan check :)
I'll also hand-review the code to see if anything can be spotted.

best regards,
- dink

**Comment by barbudreadmon** [comment]
I think the dips offset is wrong, shouldn't it be `0x0b` and `0x0c` ? Everything seems ok after i change those 2.

**Comment by dinkc64** [comment]
good catch!  and the bug is entirely my fault :) sorry guys :P

**Comment by adelpha** [comment]
Confirmed fixed! Weird Japanese guys everywhere rejoice.

**Comment by dinkc64** [comment]
It's a funny game, I just like hitting the people :)

**Comment by crystalct** [comment]
Recently i test Boong-Ga Boong-Ga... what damn of games is it?
I can't be able to understand if it works.....

**Comment by dinkc64** [comment]
boonga is stupid :)
it works :) it's just completely random if you win or not.  the shit has to match between 2 lines when it walks.
