### ISSUE TITLE
T.N.K III (US) - tnk3 - Control scheme is weird

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#492]
**Summary:**
The real cabinet uses a rotary joystick for aiming. The way it's mapped to a 360 controller means you have to move with the left stick and to aim you need to hold button 3 to rotate, then release it to move again.

I understand this makes sense for single-stick controllers, but for controllers with 2 sticks available, it would be more comfortable to have a more modern layout where left stick moves, right stick aims and maybe R1 = Fire 1 and L1 = Fire 2?

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 8ce2cd9)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game.

**Results:**
Feel the awkwardness.

**Expected Results:**
Less instant death in game.

**Notes:**
See [this Twitter thread](https://twitter.com/frankcifaldi/status/1009910215498579968) about this exact issue when this game was ported to the Switch as part of the https://snk40th.com/

**Comment by barbudreadmon** [comment]
@dinkc64 same as timesold

**Comment by barbudreadmon** [comment]
i mapped rotate left/right to L/R

**Comment by adelpha** [comment]
Thanks!
