### ISSUE TITLE
SAR - Search and Rescue - searchar - Control scheme is weird

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#494]
**Summary:**
The real cabinet uses a rotary joystick for aiming. The way it's mapped to a 360 controller means you have to move with the left stick and to aim you need to hold button 3 to rotate, then release it to move again.

I understand this makes sense for single-stick controllers, but for controllers with 2 sticks available, it would be more comfortable to have a more modern layout where left stick moves, right stick aims and maybe R1 = Fire 1 and L1 = Fire 2?

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 8ce2cd9)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game.

**Results:**
Feel the awkwardness.

**Expected Results:**
Less instant death in game.

**Notes:**
See [this Twitter thread](https://twitter.com/frankcifaldi/status/1009910215498579968) about this exact issue when this game was ported to the Switch as part of the https://snk40th.com/

**Comment by barbudreadmon** [comment]
@dinkc64 same as timesold

**Comment by barbudreadmon** [comment]
i mapped rotate left/right to L/R

**Comment by adelpha** [comment]
Thanks. That's definitely an improvement, but still clumsier than a real rotary stick. Is mapping 8 directions to a second stick to emulate dual-stick control too complicated?

If RA had macro support I'd try to do it myself, but sadly RA's input configuration leaves a lot to be desired.

**Comment by barbudreadmon** [comment]
> Is mapping 8 directions to a second stick to emulate dual-stick control too complicated?

I don't think it's even possible, because those rotary sticks are relative movements, while analog sticks are absolute movements, those games aren't designed to allow moving from, let's say, top-left to bottom-right in one go. Those rotation shortcuts are the best i can do.

**Comment by adelpha** [comment]
I was thinking that since there are only 8 possible positions, it would just be a case of tracking what direction you **were** facing last frame, what direction the joystick is pointing **this** frame, and determining the number of left or right turns to input based on that.

i.e.: was pointing north, is now pointing south east, so input 3 right turns.

**Comment by barbudreadmon** [comment]
As i said i don't think it's even possible. Tracking how ? Nothing will tell me my current position, and trying to estimate it through all previous inputs is just wishful thinking : what about the times the game will reset my position (death, beginning of stage, ...) or will ignore my input (game not even started, ...) ?
Current controls are fine, that's how this game is played.

**Comment by adelpha** [comment]
Fair enough. Thanks for all your work!
