### ISSUE TITLE
Buggy Challenge - buggychl - Controls are even more weird

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#495]
**Summary:**
Accelerate seems to be set to Down, Up+Right or Up+Left on the right stick? Not sure. Steering seems massively over-sensitive. In general the controls are just not usable.

The original cabinet has an analog pedal and a steering wheel. It doesn't seem to have a brake. Pedal has 16 states, wheel has 255.

It doesn't control particularly well in MAME either, but with the wheel sensitivity turned WAY down, it is at least somewhat playable.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 8ce2cd9)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game.

**Results:**
Frustration.

**Expected Results:**
A little less frustration.

**Notes:**
Any chance my favourite buggy game, Buggy Boy, will make it over to FBNeo?

**Comment by dinkc64** [comment]
in mame (.222) I find this game completely unplayable - especially when the car just randomly turns hard in the opposite direction.  in fbneo it's at least playable.  maybe its an issue with the libretro side of things? (barbudreadmon, any idea? p.s. make sure it's mapped as a regular analog control and not a "slider")

I think the problem here is that the arcade cabinet's steering wheel is a continuous-spin / non-auto centering wheel -- which makes it a little hard to translate to standard game controllers.

**Comment by barbudreadmon** [comment]
I'll take a look monday

**Comment by dinkc64** [comment]
@barbudreadmon what happened to libretro/fbneo - all files are gone?

**Comment by dinkc64** [comment]
@barbudreadmon 
seriously - I thought someone was super mad about me breaking the build the other day, so they wiped your repo.  That's not the case.
I just learned that a hacker actually wiped out the entire libretro organization.  well, hopefully github will restore things to normal...

best regards,
- dink

**Comment by barbudreadmon** [comment]
Ok, it explains why i got an email telling me dual-auth will be required now... Thanks for the info

**Comment by crystalct** [comment]
I had noticed that libretro/FBneo was empty, but I did not imagine an hacking.

**Comment by dinkc64** [comment]
It's unfortunate, I hope they can fix it soon.   I tried to re-populate the files, but it says I don't have access :(

**Comment by dinkc64** [comment]
great, Looks like things are back to normal this morning :)

**Comment by crystalct** [comment]
Just few commits to re-make.

Il lun 17 ago 2020, 15:56 dinkc64 <notifications@github.com> ha scritto:

**Comment by barbudreadmon** [comment]
Files are back but it seems i'll have to wait a few days before being able to commit anything

**Comment by barbudreadmon** [comment]
The only improvement i can do here is to map "Throttle" to the analog R2 button. Apart from the no auto-center awkwardness, the game appears playable to me.

@dinkc64 wheel is already mapped as a GIT_JOYAXIS_FULL

**Comment by adelpha** [comment]
Yep, changing the throttle to R2 makes it more playable, but as Dink said, without a spinner-type control it's not great. Not much you can do about that.

Thanks! Closing.
