### ISSUE TITLE
Silk Worm (World) - silkworm - Swap players at runtime?

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#497]
**Summary:**
This is more of a question than an actual bug report:

On the real cabinet, the left player is Jeep and the right player is Helicopter. A single player can choose either vehicle by just using the left or right control sets.

FBNeo seems to assign Player 1 to the Helicopter, which is fine.

Is there a simple way in FBNeo to swap Player 1 and 2 if you want to play as the Jeep instead? Having to connect a second controller just to play as the Jeep seems cumbersome.

There are a few other games that work this way; with dedicated controls for different vehicles/characters. If there is a solution that works for all of them that would be great.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 7db4876)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game.

**Comment by barbudreadmon** [comment]
By far, the easiest way is to plug a second controller if you want to play as P2.

An alternative might be to go into retroarch's `Settings > Input` and swap `Device Index` between `Port 1 Controls` and `Port 2 Controls`, however i'm not sure what will happen since i don't think retroarch likes having no controller 1 to navigate its menus.

**Comment by adelpha** [comment]
Yeah, swapping Device Index is no good, for the reason you said.

While connecting a second controller is easy enough, this isn't the only game with this issue. All of these games require you to use a specific controller to control a specific character/vehicle:

Silkworm
The Simpsons (4P cab)
TMNT (4P cab)
Super Sprint
Ivan Ironman Stewart's Super Off Road
Lucky & Wild
Star Guards
Relief Pitcher
XMen (6P cab)

For the beat-em-ups you can, of course, just use the 2P version which _does_ allow you to select your character. For the others, there is no solution other than plugging in 2 or 3 controllers.

These are just the games I could think of, I'm sure there are others. It would be really nice if there was a more general solution that doesn't require extra controllers being connected.

**Comment by barbudreadmon** [comment]
Sorry but nothing else can be done here, that's just how those games work. And i'm totally against adding solutions on the core's side to switch controllers, if it needs to be done it needs to be done at the frontend level, same as now but in a way that would still allow to navigate menu.

**Comment by adelpha** [comment]
Fair enough. Closing this one.
