### ISSUE TITLE
Possible new desyncs (netplay)

### ISSUE THREAD

**Issue by furiadeoso** [libretro/FBNeo#5]
@barbudreadmon 
Is it possible that something has changed in the last two weeks that may have affected the savestates? We are playing a league of neoturf (neogeo) and we have had a few desynchronizations.
It has been very few, but we did not remember so many for a long time.

Regards.

**Comment by barbudreadmon** [comment]
Did you determine if the problem exists ?

**Comment by furiadeoso** [comment]
I am changing between a couple of versions and letting my community try.  I think this weekend I'll be able to say something and close this issue if I can not determine anything.  In netplay some things are hard to discover.

**Comment by barbudreadmon** [comment]
So ? :)

**Comment by furiadeoso** [comment]
Ouch! I forgot to write. Sorry. Some members "feels" something strange. But I can't determine what is the cause. Perhaps it is Retroarch. 
Closing by now.

**Comment by barbudreadmon** [comment]
Fixed an issue about arithmetic rounding in https://github.com/libretro/FBNeo/commit/50f946fe6eafb1a43babbe4373dcd367625995b4, previously it would fail counting cycles properly, which could lead to desync.

**Comment by furiadeoso** [comment]
Great! Thanks for remembering this issue.
