### ISSUE TITLE
Deer Hunting USA V4.3 - deerhunt - Emulated crosshair slightly inaccurate

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#500]
**Summary:**
The purple and green crosshairs that are added by the emulator are not accurate. The crosshair is _slightly_ down and to the right of where the actual shots land.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 7db4876)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
Load the ROM. Start the game. On the first screen, just fire anywhere on the screen rapidly multiple times, avoiding two Select Mode boxes.

**Results:**
The location of the shot graphic is slightly above and to the left of the crosshair centre.

**Expected Results:**
The shot should land in the centre of the crosshair.

**Comment by dinkc64** [comment]
most gun games need to be calibrated in service mode before you can play them.  because I like these hunting games, I autocalibrated them for you.
