### ISSUE TITLE
Game options files not written out until RA closed

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#501]
**Summary:**
This might be an RA issue, but I'm posting it here anyway.

**Save Game Options file** in the Options menu supposedly writes out an options file for the running game.

It does this, but it does it when the emulator is shut down, not when you actually select the option, even though the message states "Core options file created successfully.", implying that a file has actually been created at that time.

The problem is it doesn't actually write out the core options _as they were when you chose to create the options file_. It saves them in _whatever state the options are in when you close the emulator_.

This seems counterintuitive.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 7db4876)
XBox 360 controller

Windows 10 x64
1.8.9 - FinalBurn Neo (v0.2.97.44 27dd85f)
XBox 360 controller

**Steps:**
For example:

- Start a game.
- Set **Enable cyclone ON**
- Select **Save Game Options file**
- Set **Enable cyclone OFF**
- Exit RA

**Results:**
In the <gamename>.opt file for that game, Cyclone is disabled.

**Expected Results:**
In the <gamename>.opt file for that game, Cyclone should be enabled.

**Comment by barbudreadmon** [comment]
The core has no mean to change this, it is ra behavior

**Comment by adelpha** [comment]
I suspected that might be the case. Thanks for confirming.
