### ISSUE TITLE
Mobile Suit Gundam EX Revue - gundamex - Tmp68301: error timer 2 duration is 0

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#502]
**Summary:**
The game seems to work fine, but this RA message appears at startup:

**Tmp68301: error timer 2 duration is 0**

I guess there's a problem in the TMP68301 emulation somewhere. Doesn't seem to affect the game in any noticable way.

**Comment by dinkc64** [comment]
thanks, it's just a left-behind debug message - that's all :)
