### ISSUE TITLE
Problems with various CPS games in colors

### ISSUE THREAD

**Issue by ToniBC** [libretro/FBNeo#504]
Recently several games of CPS1 and CPS2 are giving graphic problems in certain areas with colors, something that did not happen before. It also happens in the latest versions of MAME 0.223, something was modified that several games were broken.

For example, in the game Magic Sword: Heroic Fantasy, during the intro, when the sword appears, errors are observed that did not occur before.
![msword-200813-132556](https://user-images.githubusercontent.com/45365478/90197171-290de780-ddce-11ea-98dc-76d30e2e2073.png)
![msword-200813-132604](https://user-images.githubusercontent.com/45365478/90197177-2ca16e80-ddce-11ea-9443-7c43e266f98f.png)

On the scoreboard the game also happens.
![msword-200813-132615](https://user-images.githubusercontent.com/45365478/90197184-2f9c5f00-ddce-11ea-930b-bf417032a244.png)

In the game Mega Twins, in the intro there are also several errors.
![mtwins-200813-132326](https://user-images.githubusercontent.com/45365478/90197228-5195e180-ddce-11ea-9e4f-2b43e1f5f303.png)
![mtwins-200813-132337](https://user-images.githubusercontent.com/45365478/90197229-55296880-ddce-11ea-981b-6069d701d149.png)

And in the game Super Street Fighter II: The New Challengers, the same thing happens on the selection screen.
![ssf2-200813-132424](https://user-images.githubusercontent.com/45365478/90197240-5b1f4980-ddce-11ea-93ff-51e041a1ef03.png)

It happens in several other games, some of the CPS 1 and 2 driver was modified and several things fail.

**Comment by dinkc64** [comment]
Capcom was notorious for using "dark grey" as black in cps 1 & 2.  Also mismatching hue's of blue in ssf2.  These aren't bugs, this is actually how the games were programmed.  Try turning off screen filters, as they make the issue become more apparent.

**Comment by ToniBC** [comment]
Shaders do not affect visually unless you use shaders that modify the contrast or color, such as CRTs and the like, in this case it is only xbrz and it does not vary at all, xD.

What I did not know is that the games originally looked like this, it seemed like a bug, that's why I notified it, but seeing that the originals are like that, then nothing.

Thanks for answering.
