### ISSUE TITLE
Monster Maulers (and its clones) needs  a huge amount of RAM

### ISSUE THREAD

**Issue by crystalct** [libretro/FBNeo#505]
Maybe it isn't an issue, but in DadandrnInit() there is:

`pMystwarrRozBitmap = (UINT16*)BurnMalloc(((512 * 16) * 2) * (512 * 16) * 2);`

about 256 MByte of ram.... machines like PS3 can't alloc that amount of RAM.
Is it really nedded for a game of 1993?

**Comment by crystalct** [comment]
However a check and an eventual error message would be advisable, instead of a segmentation fault.

**Comment by barbudreadmon** [comment]
What is the limit on ps3 ? Maybe something could be done in burnmemalloc

**Comment by crystalct** [comment]
256M of RAM and 256M of video RAM, but a program coyld alloc about 80-100M
of RAM in normal condition.
It seems small, but fbneo on PS3 Is able to play all neogeo games and all
CPS3 games....

Il ven 14 ago 2020, 16:25 barbudreadmon <notifications@github.com> ha
scritto:

**Comment by dinkc64** [comment]
For Gaiapolis, mmaulers, dadandrn
the entire roz bitmap needs to be drawn at once, then bits copied from it by gx gfx engine - and it's really that huge.  
so, let's compare Gaiapolis on:
mame .222 445meg
fbneo git 283meg

best regards,
- dink

**Comment by crystalct** [comment]
I'll consider them unplayable on PS3. 
Is possible call HandleMessage(RETRO_LOG_ERROR, "..... inside d_mystwarr.cpp ?
With #if (defined(__CELLOS_LV2__) || defined(__PSL1GHT__)) we can show a message and avoid the segmentation fault....

**Comment by dinkc64** [comment]
Stuff like that doesn't belong in a driver, imo put it in the front end, or just don't show the games in the game listing on the ps3 hw.

**Comment by crystalct** [comment]
Surely. but once selected a game in the front end, retroarch layer & fbneo start and them work as standard Retroarch, so the user could access to menu e load another game without to back to front end, if he want. I could manage unplayble games directly in my modded retroarch layer....

**Comment by crystalct** [comment]
Or..... 
```
#if (defined(__CELLOS_LV2__) || defined(__PSL1GHT__))
	BDF_GAME_NOT_WORKING | BDF_CLONE, 2, HARDWARE_PREFIX_KONAMI, GBF_SCRFIGHT, 0,
#else
	BDF_GAME_WORKING | BDF_CLONE, 2, HARDWARE_PREFIX_KONAMI, GBF_SCRFIGHT, 0
#endif
```
is it acceptable to you?

**Comment by dinkc64** [comment]
no, sorry!

**Comment by barbudreadmon** [comment]
I can use the value of `mem_allocated` from `burn_memory.cpp` (it represents total memory currently allocated through BurnMalloc) to cancel loading if it goes past some threshold, i just need to know what threshold i should use exactly for ps3

**Comment by crystalct** [comment]
When i will back to home i write to you the code to know the Total amount
of free Memory on PS3.  I'll back in 3 days

Il lun 17 ago 2020, 22:01 barbudreadmon <notifications@github.com> ha
scritto:

**Comment by barbudreadmon** [comment]
I found a better solution with https://github.com/libretro/FBNeo/commit/5f86c833851ed91a664744f22928006e4e359eea and https://github.com/libretro/FBNeo/commit/d5994d8b49897553e367ec634b3babf94c418af4, mmaulers should fail nicely now.

**Comment by crystalct** [comment]
Good! Elegant solution.

Il mar 18 ago 2020, 15:52 barbudreadmon <notifications@github.com> ha
scritto:

**Comment by crystalct** [comment]
Do you remember other games, on other systems, that need a large amount of
memory? I'll check them...

Il mar 18 ago 2020, 15:52 barbudreadmon <notifications@github.com> ha
scritto:

**Comment by barbudreadmon** [comment]
no :/

**Comment by crystalct** [comment]
And we can say that you start a better way of calling init function in
general...checking if return 0 or 1

Il mar 18 ago 2020, 15:52 barbudreadmon <notifications@github.com> ha
scritto:

**Comment by crystalct** [comment]
Hello!
For games that need 256Mbyte di RAM allocated for a part of Bitmaps, i'm testing the use of Virtual Memory on PS3. It can be allocated up to 256 MB, using a variable piece of phycal memory. On RPCS3 it work well. If it work well on real PS3, i will propose a PR, like this:
```
#ifndef __PS3__
      if ((pMystwarrRozBitmap = (UINT16*)BurnMalloc(((512 * 16) * 2) * (512 * 16) * 2)) == NULL) return 1;
#else
      if (cellSysmoduleLoadModule(CELL_SYSMODULE_IO) != CELL_OK) return 1;
      if (sys_vm_memory_map(256*1024*1024, 64*1024*1024,
			SYS_MEMORY_CONTAINER_ID_INVALID,
			SYS_MEMORY_PAGE_SIZE_64K,
			SYS_VM_POLICY_AUTO_RECOMMENDED, (sys_addr_t*)&pMystwarrRozBitmap)) return 1;
#endif
```
only on GaiapolisInit() and DadandrnInit().
![image](https://user-images.githubusercontent.com/1675181/117253397-7728b680-ae47-11eb-9123-600f94fbe161.png)

**Comment by barbudreadmon** [comment]
Sorry but i don't want to see that kind of platform-specific hack in drivers. Maybe if it could be hooked directly to our BurnMalloc function in burn_memory.cpp ? However i'm totally missing the point here, 7fps ?

**Comment by crystalct** [comment]
^_^ Of course no .. not 7fps... just setting wass to start RPCS3 quicly ...
![image](https://user-images.githubusercontent.com/1675181/117260725-a9d6ad00-ae4f-11eb-8f07-ab596bd27258.png)
For fast use of RPCS3, settings must be LLVM Recompiler for PPU, but every first start of ELF/SELF recompiled you have to was 4-5 minuti of recompilation before it start.
Anyway... i have to test VM on PS3.......

**Comment by dinkc64** [comment]
I would recommend making modifications to BurnMalloc as well for this sorta thing, but barbudreadmon already did :)

**Comment by crystalct** [comment]
Unfortunatly, it doesn't work on PS3. RPCS3 is too permissive. Probably, on retroarch layer, opengl driver use directly that piece di memory (VM) and GPU (RSX) can't directly access VM. What a pity.

**Comment by crystalct** [comment]
WOW... thanks.... i will test it.
