### ISSUE TITLE
Macro buttons stopped working

### ISSUE THREAD

**Issue by ji125443** [libretro/FBNeo#51]
As the question ...

**Comment by leoxxx** [comment]
https://github.com/libretro/RetroArch/issues/7467
I've commit the issue here. Just be add a label.

**Comment by barbudreadmon** [comment]
There is already an opened issue about it at https://github.com/libretro/RetroArch/issues/8209

**Comment by barbudreadmon** [comment]
Some update about this : the most i would be able to map for neogeo games with current libretro limitation would be 4 macros (over the 11 possible combinations), if someone is willing to provide a list of the 4 most useful ones, i'll consider implementing them.

On a sidenote, 3xKick & 3xPunch were re-implemented for SF-like games

**Comment by danabnormal9000** [comment]
> Some update about this : the most i would be able to map for neogeo games with current libretro limitation would be 4 macros (over the 11 possible combinations), if someone is willing to provide a list of the 4 most useful ones, i'll consider implementing them.
> 
> On a sidenote, 3xKick & 3xPunch were re-implemented for SF-like games

For neogeo games these are probably the 4 most useful ones, please help implementing them. It's very important for neogeo gamers :
- A+B
- C+D
- A+B+C
- B+C+D

These are honorable mentions :
- A+C
- B+D

**Comment by leoxxx** [comment]
kof 99 02
BC
k9999 need ABCD(01 02) ATHENA&KIM need ABCD,too(02)
RALF need AD(02)

**Comment by barbudreadmon** [comment]
i said a max of 4 combo and i'm already getting 10 different combos... i guess that just mean it won't be possible so i'll leave things as-is until retroarch provide support for this.

**Comment by danabnormal9000** [comment]
Maybe at least the most important and simple combos can be implemented? Only 2 combos :
- A+B
- C+D

**Comment by leoxxx** [comment]
> * A+B
> * C+D
> * A+B+C
> * B+C+D

I agree to this.
But I think ABCD is hard to push on joypad. So suggestion ABCD.(It can cancel skill)

**Comment by danabnormal9000** [comment]
> > * A+B
> > * C+D
> > * A+B+C
> > * B+C+D
> 
> I agree to this.
> But I think ABCD is hard to push on joypad. So suggestion ABCD.(It can cancel skill)

Okay. So maybe these 4 are the most important button combinations:
- A+B
- C+D
- A+B+C
- A+B+C+D

While CPS1/CPS2/CPS3 got 3xPunch and 3xKick setting in the core, I think neogeo deserve at least A+B and C+D.

**Comment by leoxxx** [comment]
I hope retroach add the feature ASAP.

**Comment by danabnormal9000** [comment]
> I hope retroach add the feature ASAP.

I think neogeo A+B and C+D should be implemented on core, not on retroarch. Similar like 3xPunch and 3xKick on CPS games. I gave my hope up on retroarch.

**Comment by barbudreadmon** [comment]
> * A+B
> * C+D
> * A+B+C
> * B+C+D

I went with those 4 macros, implementing B+C+D seemed like a better choice than A+B+C+D since that one can be done by pressing A+B & C+D macros.

**Comment by dare25GH** [comment]
> > * A+B
> > * C+D
> > * A+B+C
> > * B+C+D
> 
> I went with those 4 macros, implementing B+C+D seemed like a better choice than A+B+C+D since that one can be done by pressing A+B & C+D macros.

Thank you for making this @barbudreadmon :)

I am using RetroArch 1.19.1 and cores FinalBurn Neo (v1.0.0.03 e15ffeb) and FB Alpha 2012 Neo Geo (v0.2.97.29 fa3bf50)

I am unable to find these hotkey options in the core settings, it's hotkeys section and the games input settings as well. 
 
I have installed a couple of older versions too, like 1.9.0 etc and have unable to find the options.

Could you please guide me to where I could find these hotkey settings and in which versiosn they are available?

Thank you :)

**Comment by barbudreadmon** [comment]
They are part of retroarch's remapping menu (`Quick Menu > Controls`)

**Comment by dare25GH** [comment]
Thank you for the clarity and direction @barbudreadmon !

I have loaded kof 98 and gone to the Quick Menu > Controls via F1 on the keyboard.

I have tried both the 'modern' and 'classic' menu in Controls > Port 1 controls > Device Type > Modern (and Classsic)
![RA classic](https://github.com/user-attachments/assets/7e2bfddc-2d4e-4c2e-aea6-69772a692b37)
![RA modern](https://github.com/user-attachments/assets/8b7fda93-64ab-430b-aaa0-1428eb13dd99)

This is the entire list of the key mappings available.

Could you please guide me to which one of these buttons could map A+B+C ?

When I try to, I get the following pre-set options:
![key options](https://github.com/user-attachments/assets/ba5a35cf-2ed9-4206-bc79-3705f4396164)

and I am unable to press A+B+C on the keyboard to remap the chosen key.

**Comment by barbudreadmon** [comment]
I repeat : **The FB Alpha 2012 core has nothing to do with us**.

**Comment by dare25GH** [comment]
> I repeat : **The FB Alpha 2012 core has nothing to do with us**.

I understand,  @barbudreadmon. I only loaded a core to access the Quick Menu and I think I had read somewhere that the remapping  keys are game specific, like neo-geo for e.g.

Not loading any core, I have looked into Input > Retropad Binds > Port 1 controls and Input > Hotkeys and couldn't find any setting that would allow me to bind A+B+C.

Could you please guide me to the path to setup the same?

**Comment by barbudreadmon** [comment]
This is the FBNeo repository and this is a feature for the FBNeo core. If you want this feature to be available in another core, don't ask me.

**Comment by dare25GH** [comment]
I see @barbudreadmon . I installed the FBNeo core and accessed Quick Menu > Controls > Port 1 controls >  Device type > Retropad, Modern, Classic,  6- button panel etc controllers and I couldn't find an option to map A+B+C

![FBneo modern controls](https://github.com/user-attachments/assets/d476435a-a3d0-4d4e-bf0f-efc83cab83b2)

Please help

**Comment by barbudreadmon** [comment]
This is not how the default mapping for neogeo games looks like in FBNeo. You don't even have a "Button B" mapped.
I can only suppose you already changed the mapping.
Reset it to default (`Quick Menu > Controls > Manage Remap Files > Reeset Input Mapping`).

**Comment by barbudreadmon** [comment]
Also, for the default mapping for neogeo games to appear, you need a neogeo game to be running.

**Comment by barbudreadmon** [comment]
One last note, this is how the default mapping looks like : 
![kof94a](https://github.com/user-attachments/assets/9127e279-c259-48f0-b2f0-e1c1a6cc22e4)

If you can't figure out how you broke it, i recommend seeking help from the retroarch team or starting from scratch with a fresh retroarch setup. 
Debugging issues with retroarch's remapping is not my speciality.

**Comment by dare25GH** [comment]
Thank you for your insights @barbudreadmon ! I am surprised to see the B button not mapped in t he screenshot...must have been done by accident.

I closed RA and restarted it, loaded the core and the game and found the A+B+C option!
Thank you very much!

![a+b+c found](https://github.com/user-attachments/assets/9ae84102-115c-42da-915d-17346ed2b9cf)


How could I go about mapping the keyboard key 'c' to A+B+C? I have tried editing and saving retroarch.default.cfg and retroarch.cfg by editing 'input_player1_r2 = "nul" ' to ' input_player1_r2 = "c" ' but its not working. 


Also, could you please share why A+B+C is not triggered manually in FBNeo, while A+B and B+C works as expected? Would love to trigger A+B+C without the hotkeys if it did.

**Comment by barbudreadmon** [comment]
As previously said, debugging issues with retroarch's remapping is not my speciality. The core is working as it should, anything else is something you should ask the retroarch team.

**Comment by dare25GH** [comment]
> As previously said, debugging issues with retroarch's remapping is not my speciality. The core is working as it should, anything else is something you should ask the retroarch team.

I understand. Thnak you for your help @barbudreadmon
