### ISSUE TITLE
Twinbee (Bubble System) - twinbeeb - boot.bin duplicated in DAT file

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#512]
Presumably, only the second of these boot.bin entries should be here.

	<game name="twinbeeb" cloneof="twinbee" romof="twinbee">
		<description>TwinBee (Bubble System)</description>
		<year>1985</year>
		<manufacturer>Konami</manufacturer>
		<rom name="boot.bin" size="480" crc="ee6e93d7"/>
		<rom name="twinbee.bin" size="262912" crc="4d396a0a"/>
		<rom name="mcu" merge="mcu" size="4096" status="nodump"/>
		<rom name="400-e03.5l" merge="400-e03.5l" size="8192" crc="a5a8e57d"/>
		<rom name="400-a01.fse" merge="400-a01.fse" size="256" crc="5827b1e8"/>
		<rom name="400-a02.fse" merge="400-a02.fse" size="256" crc="2f44f970"/>
		<rom name="boot.bin" merge="boot.bin" size="480" crc="f0774fc2"/>
		<rom name="mcu" merge="mcu" size="4096" status="nodump"/>
		<rom name="400b03.8g" merge="400b03.8g" size="8192" crc="85c2afc5"/>
		<rom name="400a1.2b" merge="400a1.2b" size="256" crc="5827b1e8"/>
		<rom name="400a2.1b" merge="400a2.1b" size="256" crc="2f44f970"/>
		<driver status="good"/>
	</game>

**Comment by barbudreadmon** [comment]
it's not duplicated, the 2 files have different crc, one is from the bios file, the other is from the romset (it seems the game uses a boot.bin slightly different from the bios). I see no problem here, that's how those romsets/bioses are in MAME too.

**Comment by adelpha** [comment]
Ok. cmpro warns about it but I guess it doesn't matter if the file gets renamed.

```
Set:	TwinBee (Bubble System)
Name:	twinbeeb
ROM:	boot.bin

Issue:	Double ROM with different hashvalues found

Keep ROM but rename it?
Otherwise it'll be removed from the set definition.
```

**Comment by barbudreadmon** [comment]
It'll be renamed only if you don't use split sets, there are lots of other romsets like this, no reason to be worried, especially since the emulator loads files based on their crc, not on their name.
