### ISSUE TITLE
Lucky & Wild - luckywld - Player 1 gun seems to be mapped to steering as well

### ISSUE THREAD

**Issue by adelpha** [libretro/FBNeo#516]
**Summary:**
If you're playing single-player on the original cabinet, you drive with a steering wheel, accelerator and brake pedals and shoot with a physical gun control that behaves like an analog joystick.

![luckywld](https://user-images.githubusercontent.com/13021896/91360757-f1039d00-e7ee-11ea-810f-f8d89d1913e4.png)

On the x360 controller, the game seems to be using **both** the left analog stick **and** the D-pad for steering, while **also** using the D-pad for aiming.

**Test Device:**
Raspberry Pi 3B
1.8.8 - FinalBurn Neo (v0.2.97.44 9f88e44)
XBox 360 controller

**Steps:**
Load the ROM. Start the game.

**Results:**
Aiming while not driving off the track is pretty much impossible.

**Expected Results:**
Aiming should be separate from steering.

**Notes:**
Ideally, as both steering and aiming are analog devices, they should be mapped to the left and right analog sticks. The accelerator and brake are analog as well, so they should be the left and right triggers. Finally, the fire button should probably be LB or RB, since if you're already using the triggers and analog sticks, the 4 face buttons are really awkward to hit.

Really, this cabinet just has too many analog controls 😁

**Comment by barbudreadmon** [comment]
oops, thanks for the report, fixed with https://github.com/libretro/FBNeo/commit/9a243870f41d5dfd9c13ae7b0f6b98690e385f20

**Comment by adelpha** [comment]
Confirmed fixed. Thanks again!
