### ISSUE TITLE
Toaplan driver issue?

### ISSUE THREAD

**Issue by kwyxz** [libretro/FBNeo#529]
Hello FBNeo devs,

There is a possible regression in the Toaplan v2 driver.

When started, _truxton2_ displays a green screen and does not go any further. With earlier versions of FBNeo libretro it used to work (I am attempting to bisect to find what commit broke it). At least _sstriker_ behaves similarly.

However, _tekipaki_ or _kbash_ start succesfully while alledgedly using the same driver.

This was observed and replicated both on x86_64 (Debian stable) and ARM (Pi4 w Raspbian)

Thanks!

**Comment by kwyxz** [comment]
With revision 81eef978f both _truxton2_ and _sstriker_ show the green screen but then proceed to loading up the game, while revision 3cf4879 stops at the green screen.
My attempt to bisect was short-lived :(
```
Some good revs are not ancestors of the bad rev.
git bisect cannot work properly in this case.
Maybe you mistook good and bad revs?
```

**Comment by kwyxz** [comment]
I tried to rebuild while fully deactivating Cyclone, it does not change anything.

**Comment by barbudreadmon** [comment]
@dinkc64 the issue is caused by https://github.com/libretro/FBNeo/commit/4a3e308bc0c3e461f820d5c867c21c49c4622f55

**Comment by dinkc64** [comment]
uhoh, I didn't do a full recompile after doing that, which is why I didn't notice.  my bad.

**Comment by dinkc64** [comment]
all fixed up now :)
