### ISSUE TITLE
X-Men 6-Players (xmen6p) non-working on Wii U (big endian)

### ISSUE THREAD

**Issue by vaguerant** [libretro/FBNeo#536]
Testing on Android, I get a white flash on "both" screens (6-player X-Men is a dual-monitor game), followed by the self-check screen:

![xmen6p-200906-172701](https://user-images.githubusercontent.com/5259025/92320703-ba3b4b80-f066-11ea-9620-ad6b00203584.png)

On Wii U, I get the white flash, but the game never proceeds to the self-check, simply displaying a black screen. There is no video or audio at all and no outward response to coin or other button inputs.

Standard X-Men (xmen) proceeds through the self-check and on to the attract mode and gameplay with no issues on the same setup.

Tested on cab98f6 for Wii U.

**Comment by barbudreadmon** [comment]
fixed by https://github.com/finalburnneo/FBNeo/commit/c4eee6a303bcf39cbffdab5be0a72c5b5a62b974 , however don't expect it to run full speed

**Comment by crystalct** [comment]
@vaguerant a question about WiiU.... is working mame2009 core on WiiU?
If yes... could you see if there are differences with mame2003-plus about CHDs games like, for example, biofreak?
Maybe mips3.c was fixed in later mame versions about big endian issues....

**Comment by vaguerant** [comment]
I just downloaded the MAME 2009 core to test, but it looks like it doesn't work at all on Wii U. The Wii U crashes as soon as I load the core. Sorry.

**Comment by crystalct** [comment]
Ok, thanks

Il dom 20 set 2020, 13:26 vaguerant <notifications@github.com> ha scritto:
