### ISSUE TITLE
Wonder Boy Background Scroll Issues

### ISSUE THREAD

**Issue by OperationWalker** [libretro/FBNeo#60]
Thank you so much for your time the other day. It seems that background scroll in [FBNeo](https://github.com/libretro/FBNeo/tree/143e0b560fb4344432081ffb7b59def0134aee9d) is not smooth compared to Arcade or Mame. It becomes more noticeable when you speed up on the Tom-Tom. When viewing the framerate for RetroArch and RivaTuner Statistics Server, and they both maintained 60 fps. By the way, I tried [d_sys1.cpp's](https://github.com/libretro/FBNeo/blob/master/src/burn/drv/sega/d_sys1.cpp) "My Hero" and "Wonder Boy in Monster Land", and these titles scrolling background smoothly. Thanks

**Comment by dinkc64** [comment]
Thanks, I will look into it :)

**Comment by OperationWalker** [comment]
Thank you for starting the investigation.

**Comment by dinkc64** [comment]
Hi, I made a test-fix for wboy - please give it a try :)

**Comment by OperationWalker** [comment]
When I build and tested [d16c044](https://github.com/libretro/FBNeo/tree/d16c04451b66b201e3ff86dbb4f3d8af57efbdbf), wboy now is scrolls background very smoothly! Thank you very much for devoted to your precious time resources to Wonder Boy.

**Comment by dinkc64** [comment]
You're welcome, thanks for testing and bug report :)

**Comment by OperationWalker** [comment]
I should thank you too!
