### ISSUE TITLE
Add core option for sound channels volume override (WIP, help needed)

### ISSUE THREAD

**Issue by eadmaster** [libretro/FBNeo#605]
[followup to this](https://github.com/finalburnneo/FBNeo/issues/465)

I've started working on this in [my fork](https://github.com/eadmaster/FBNeo).
I've started with the neogeo and i am actually able to scale all the audio channels of that machine (FM, ADPCM and PSG).

However it seems some ADPCMs cannot be disabled for some reason.

If you can help please post here, i'm going to wrap other popular systems soon.

**Comment by barbudreadmon** [comment]
Let's tag @dinkc64 to know what he thinks about this.

I'm not strongly against this but i can't say i'm all for it either, as already said last time i prefer FBNeo having the right channel balance from the start (which is something regularily improved when issues are reported) than expecting the user to mess with those settings.

At the end of the day, your work won't make it into this fork if it doesn't make it into upstream first, so i don't recommend going forward with this before having feedbacks.

**Comment by eadmaster** [comment]
To clarify: this is not meant as a workaround for sound emulation bugs, but rather to ["fix" games that have unbalanced audio by design](http://eadmaster.altervista.org/wordpress/archives/90#more-90).

> Also, one of the concerns i have about this kind of settings, is that i don't want people to report issues because they forgot they messed with those settings for another game, so there is no way i'll accept those if they are applied globally, you'll have to do something similar to what is done for dipswitches and the likes.

In retroarch you can save per-game overrides of the core options, but i will take a look on how dipswitches are saved and see if i can refactor that part.

**Comment by barbudreadmon** [comment]
> but rather to "fix" games that have unbalanced audio by design.

That's irrelevant, this is something we adjust natively in FBNeo when such an issue is reported, as i mentioned several times already.

> In retroarch you can save per-game overrides of the core options

That's irrelevant, what i want is to totally prevent people from setting those globally, because it'll only lead to user mistakes and more debugging work on our side.

Again, i believe this is going against the zeroconf feel i want with this core, but i'm not strongly against it if a certain number of conditions can be met : 
- upstreamed code
- not a source of false bug reports

**Comment by dinkc64** [comment]
Critearia for making it into upstream:
1: needs a ui / slider panel for it in the standalone build
2: support every soundchip, in nice way, with the ability to register which sound channels are active for that game (so we don't have a whole bunch of sliders that may or may not do anything)

"in a nice way", for example, take this code:
/* apply user volume scaling */
if (nBurnFMSoundChannelVolumes[0] < 100) out_fm[1] = (out_fm[1] * nBurnFMSoundChannelVolumes[0]) / 100;
if (nBurnFMSoundChannelVolumes[1] < 100) out_fm[2] = (out_fm[2] * nBurnFMSoundChannelVolumes[1]) / 100;
if (nBurnFMSoundChannelVolumes[2] < 100) out_fm[4] = (out_fm[4] * nBurnFMSoundChannelVolumes[2]) / 100;
if (nBurnFMSoundChannelVolumes[3] < 100) out_fm[5] = (out_fm[5] * nBurnFMSoundChannelVolumes[3]) / 100;

replace with:
BurnBalance(out_fm[1], FM_CHAN0); 
BurnBalance(out_fm[2], FM_CHAN1); 
BurnBalance(out_fm[4], FM_CHAN2); 
BurnBalance(out_fm[5], FM_CHAN3); 

in the init somewhere:
BurnBalanceInit(FM_SYNTH, 4); // init 4 channels

to get you started: (p.s. this message-box makes typed-code look ugly, sorry about that.)
burn_balance.h 
enum {
FM_CHAN0 = 0,
FM_CHAN1,
FM_CHAN2,
FM_CHAN3,
};
enum {
AY8910_CHAN0 = 0,
...
...
}

void BurnBalance(INT32 &sample, INT32 nChannel)
{
switch (nChannel) {
case FM_CHAN0:
case FM_CHAN1:
case FM_CHAN2:
case FM_CHAN3:
 if (nBurnFMSoundChannelVolumes[FM_CHAN0] < 100) sample = (sample * nBurnFMSoundChannelVolumes[FM_CHAN0]) / 100;  
break;
}
}

**Comment by eadmaster** [comment]
> That's irrelevant, this is something we adjust natively in FBNeo when such an issue is reported, as i mentioned several times already.

I think there is no correct way to "fix" these issues since every human has a different perception of the various audio freqencies. So what sounds "unbalanced" to me may sound fine to others.

Besides that, i think emulators should try to reproduce the original machine as close as possible. So if the original game had unbalanced audio, the emulator should reproduce this **by zeroconf default**.
In the end these makes more sense to me as an adjustable user preference rather than hard-coded fixes.

> Critearia for making it into upstream:
1: needs a ui / slider panel for it in the standalone build
2: support every soundchip, in nice way, with the ability to register which sound channels are active for that game 
...

This looks like a lot of work, since there are a lot of audio chips emulated in FBNeo.
I would be happy if this just makes into the libretro port with only some machines supported since it is what i am using atm.

I may simply add some precompiler defines to avoid the volume scaling to affect the other ports, which may omit these new options entirely.

**Comment by barbudreadmon** [comment]
> So if the original game had unbalanced audio, the emulator should reproduce this by zeroconf default.

In FBNeo, we don't care about being accurate if accurate is bad.

> So what sounds "unbalanced" to me may sound fine to others.

Then it's not about fixing issues but more about tuning sound to user's preference.

> I would be happy if this just makes into the libretro port with only some machines supported since it is what i am using atm.

Again, i want libretro and standalone to stay 1:1, and i don't think it would be fine to add several dozens of new settings globally for "only some machines", my belief has always been to leverage as much as possible the user experience with this emulator.

Thinking out loud about what might look like the best case scenario in my mind : 
- having a new member for channels control in the game driver structs
- that new member (which can be NULL if no such channel control exist - yet ?) can be used to provide the list of available channel to the frontend and control their balance.

Yeah, that looks like a massive amount of work, that's why i told you we won't do it in your previous issue, but it doesn't mean we would accept contributions that feel more like hacks instead.

**Comment by eadmaster** [comment]
> Then it's not about fixing issues but more about tuning sound to user's preference.

Yes, definitively. :-)

>  -  having a new member for channels control in the game driver structs
> -   that new member (which can be NULL if no such channel control exist - yet ?) can be used to provide the list of available channel to the frontend and control their balance.

Can you link me some code so i can quickly figure out the changes needed?

> Yeah, that looks like a massive amount of work, that's why i told you we won't do it in your previous issue, but it doesn't mean we would accept contributions that feel more like hacks instead.

I went with the hackish way since i am not sure how many users are interested in these options.

My plan was to start with only a few system supported on the libretro port and then add more with later PRs.
 If this gains some interest other devs may also contribute covering more systems and ports.

**Comment by eadmaster** [comment]
UPDATE: i've added a bunch of new systems sharing the same sound chips and fixed the neogeo.
is it ok for you if these new options are available only in the libretro port for starters?

I've also taken a look at the dipswitches implementation, but they must be defined individually for each driver and it does not look a good to idea to me since many drivers share the same audio chip.

Btw [these `get_supported_*_channels` functions i've made](https://github.com/eadmaster/FBNeo/blob/a8fada1d76451255319c7efa08a5827e98ccfe64/src/burner/libretro/retro_common.cpp#L1256) could be easily reused on other frontends where these options could be enabled dynamically only if supported by the current driver in use.

**Comment by barbudreadmon** [comment]
> is it ok for you if these new options are available only in the libretro port for starters?

No

> but they must be defined individually for each driver

Which was the whole point for me asking, since i don't want those zillions of new core options if a game usually need only a few of them

> Btw these get_supported_*_channels functions i've made could be easily reused on other frontends 

I'll take a look when i've some time, but i'll be honest, i don't think this is going anywhere

**Comment by eadmaster** [comment]
Ok, no problem, i'll add a few binary builds in my fork for those brave souls who want to give it a try. :-)

Side question: do you know if there's a way to check directly if the current loaded driver is using the audio chip "X" (e.g the YM2610).

This way i can avoid hardcoding the actual driver names in my `get_supported_*_channels` functions.

**Comment by barbudreadmon** [comment]
maybe you could use https://github.com/libretro/FBNeo/blob/master/src/burn/burnint.h#L281-L318

**Comment by eadmaster** [comment]
> maybe you could use https://github.com/libretro/FBNeo/blob/master/src/burn/burnint.h#L281-L318

these required the `FBNEO_DEBUG` define which is not enabled by default in the libretro makefile.
Any other alternative based on the `BurnDrvGetHardwareCode()` bitmask?

**Comment by barbudreadmon** [comment]
> these require the FBNEO_DEBUG

No, they don't

**Comment by eadmaster** [comment]
i see... the problem is that `Burn*Init()` is called **after** the core options are initialized, i'll see if i can refactor that...

**Comment by eadmaster** [comment]
I've just found some machines like [CAPCOM SECTION Z](http://system16.com/hardware.php?id=789)  are using multiple audio chips of the same kind, is there a way to detect that?

**Comment by barbudreadmon** [comment]
> i see, the problem is that Burn*Init() is called after the core options are initialized, i'll see if i can refactor that...

core options need to be set before burn init, otherwise any core option that need to be set at init will stop working (meaning almost all of them).

> this particular sound driver the variable is still not set without FBNEO_DEBUG

i don't think there is a real reason for putting this var inside a `FBNEO_DEBUG` in the first place, so that macro could be removed

> is there a way to detect that?

i don't think so, and it's gonna happen a lot, that's why i think my suggestion of including something in game driver struct was the right one, it would also permit to access it before burn init is called... 

anyway your idea is getting farther from what i would have considered acceptable by the minute, so i confirm it's not gonna make it into this repo.

**Comment by eadmaster** [comment]
> core options need to be set before burn init, otherwise any core option that need to be set at init will stop working (meaning almost all of them).

I've fixed that by calling these 2 functions 2 times, before and after `BurnDrvInit()`, and it seems to work fine:
````
		set_environment();
		check_variables();
````

> i don't think there is a real reason for putting this var inside a FBNEO_DEBUG in the first place, so that macro could be removed

Fixed that in my fork, so now i am using these `DebugSnd_*Initted` globals  to reliably detect the sound  chips currently in use and init the core options accordingly.

> i don't think so, and it's gonna happen a lot, that's why i think my suggestion of including "something" in game driver struct was the best case scenario, it would also permit to access it before burn init is called...
> 
> anyway your idea is getting farther from what i would have considered acceptable by the minute, so i confirm it's not gonna make it into this repo.

Nevermind, thank you for your help anyway, i'll definitely check this and other solutions.

**Comment by barbudreadmon** [comment]
> I've fixed that by calling these 2 functions 2 times, before and after BurnDrvInit()

Be careful, you can't change the number of core options sent by `set_environment` between the 2 calls.

**Comment by barbudreadmon** [comment]
can i close this ?

**Comment by eadmaster** [comment]
Sure, no problem, i'll reopen if there are significant news.
