### ISSUE TITLE
Arcade nightlies MISSING files when verified with ClrMamePro

### ISSUE THREAD

**Issue by Dochartaigh** [libretro/FBNeo#611]
I'm trying to use ClrMamePro to verify the FBNeo Arcade 10-31 Nightlies (believe these would be 1.0.0.01, right?), with the .DAT file found in this GitHub (1.0.0.01, updated 3 days ago). Successfully make a non-merged set (for use in RetroPie for lr-fbneo emulator), with "Separate BIOS sets" turned off like the directions say. 

I then use ClrMamePro's Scanner feature to verify the non-merged romset and I still get 10 missing sets, and 266 missing roms (the "merged" romset also verified wrong too, FYI). Even manually moving in different versions of the effected .zip files from any number of sources and they STILL come back wrong. My old Mame2003 set verifies 100% as does my new Mame 0.226 set so I'm (in theory) using ClrMamePro correctly. Any way to fix these missing ones? (or educate me on what I'm doing wrong?). 

Here's the ClrMamePro error log if it helps: https://pastebin.com/bfJAx0Q4

While the experts are here, I have an overall question about romsets for use with Raspberry Pi 3/4 in RetroPie. Plastered all over the net (and the official RetroPie documents) it says to use "FB Neo v0.2.97.44-WIP" with the lr-fbneo emulator. This romset doesn't seem to exist. I assume the "WIP" part means it's a Work In progress with the switch from FBA to FBNeo. is this set I'm chasing the correct one? Sorry if this is a simple question... but I've posted numerous places and asked a bunch of people and nobody knows...

**Comment by barbudreadmon** [comment]
> I assume the "WIP" part means it's a Work In progress with the switch from FBA to FBNeo

It's a WIP in the sense there are updates every day : new games, new fixes, new improvements, etc...
We don't support piracy (i had to moderate your message btw...), so i can't help you completing your set, all i can say is that we don't add fake romsets, they all exist. Good luck. Closing.

**Comment by Dochartaigh** [comment]
> It's a WIP in the sense there are updates every day : new games, new fixes, new improvements, etc...

Thank you barbudreadmon, and thanks for editing too (meant to cause no problems!). I think you were getting at this but couldn't tell 100% – so are these 1.0.0.0 and 1.0.0.1 in fact the "0.2.97.44" "wip" sets? Just want to make sure they'll work with the current lr-fbneo.

**Comment by barbudreadmon** [comment]
Ultimately they are just version numbers, we jumped from 0.2.97.44 to 1.0.0.0 on 1st november to make our first official release as FBNeo (not that there would be many difference between a 0.2.97.44 set from 31 october and a 1.0.0.0 set from the next day). Then we moved to a new development cycle with the 1.0.0.1 version.
Current lr-fbneo expect latest set, if you are using a 2 month old set you'll get a few incompatibilities (not many though)
