### ISSUE TITLE
Smash TV requires dual stick controls

### ISSUE THREAD

**Issue by roslof** [libretro/FBNeo#630]
FinalBurn Neo (v1.0.0.01) 208f02b
Tested on Raspberry Pi 4B (ARM)

**Issue:** Currently, the primary stick controls direction of both movement and firing.
**Expected Results** Two sticks are required for independent movement (left) and firing (right).

**Comment by barbudreadmon** [comment]
it was fixed by https://github.com/libretro/FBNeo/commit/2a5e010fdca7e4d05587746ef7220cdb5e1d5e5b
