### ISSUE TITLE
RaspberryPi 3A+

### ISSUE THREAD

**Issue by sergiopoverony** [libretro/FBNeo#64]
More time  i use other raspberry pi for run RetroPie and play my loved game. NeoGeo games can work on raspberry pi zero and raspberry pi 3B+. Now i use raspberry pi 3A+ and my loved games cant run. i can see no more. after run i select fbneo and launch. flash black screen and i see again game listing. Repeat, Zero and 3B+ work fine. 
I remove and reinstall in retropie, not work.

**Comment by barbudreadmon** [comment]
That's obviously a setup issue, not an emulator issue, ask retropie's forum for help, closing.
