### ISSUE TITLE
Diagnostic Input is not working for PGM boards on aarch64 build(both libnx and Linux).

### ISSUE THREAD

**Issue by SumavisionQ5** [libretro/FBNeo#648]
I found that Diagnostic Input is not working for all PGM boards.
No matter which combo I chose, I just could not enter cabinet service menu. 
It worked in 32bit ARM Linux, but not for aarch64 Linux.
It seems that it's just broken in libretro port with aarch64 Linux.

**Comment by SumavisionQ5** [comment]
I tried Switch version(libnx) which is also an aarch64 build. Same issue.

**Comment by barbudreadmon** [comment]
It turns out there are 2 diag inputs : 
https://github.com/libretro/FBNeo/blob/7dde60395bd91978b5e5494c168a24d4f31ffd28/src/burn/drv/pgm/d_pgm.cpp#L54-L55

I'm not sure why though.

While assigning keys on the libretro port, diag2 is overwriting diag1 (not sure why that would go differently on 32bits, are you sure about this ?), but only diag1 appears to open service on the few games i tried ?

@dinkc64 do you know what's the second diag about ?

**Comment by SumavisionQ5** [comment]
> It turns out there are 2 diag inputs :
> https://github.com/libretro/FBNeo/blob/7dde60395bd91978b5e5494c168a24d4f31ffd28/src/burn/drv/pgm/d_pgm.cpp#L54-L55
> 
> I'm not sure why though.
> 
> While assigning keys on the libretro port, my code is overwriting diag1 with diag2 (not sure why that would go differently on 32bits, are you sure about this ?), but only diag1 appears to open service on the few games i tried ?
> 
> @dinkc64 do you know what's the second diag about ? MAME seems to call this one "test-key 3P+4P", but i don't see many reasons to have a separate test key for 3P+4P, and it doesn't seem to do much anyway.

I checked 32bits again, and it's working. Very weird.

**Comment by barbudreadmon** [comment]
Hmmm, since i can't think of any reason for 32/64 bits to assign those diags differently, i believe this issue might be about that second diag button opening service menu on 32bits while being broken on 64bits

**Comment by SumavisionQ5** [comment]
This is what we have in fba2012.
`{"Diagnostics 1",	BIT_DIGITAL,	PgmBtn1 + 4,	"diag"		},
{"Diagnostics 2",	BIT_DIGITAL,	PgmBtn1 + 6,	""		},
`
I think we can just leave 2nd diag blank to fix it.

**Comment by barbudreadmon** [comment]
blank is to be avoided tbh, we changed it to diag2
