### ISSUE TITLE
[Enhancement] Load subsystem by folder name

### ISSUE THREAD

**Issue by zach-morris** [libretro/FBNeo#66]
This is a request for an enhancement to the existing core:
Instead of requiring the --subsystem argument or loading games via the load subsystem menu in the Retroarch gui, add the possible core option of loading subsystem by parent folder name.  This is similar to how softlists can work with MAME and MESS in Retroarch so there is some precedent. 

Example:
Play burger time colecovision game with the command (and load subsystem by parent folder option enabled):
```
"...\path_to_program\retroarch.exe" -L "...\path_to_cores\cores\fbneo_libretro.dll" "...\path_to_game_files\cv\btime.zip"
```

FBNeo would then detect cv parent folder and load the cv subsystem argument, or default to the standard (no subsystem) loading if the folder name was not valid.

**Comment by thatman84** [comment]
+1 for this enhancement
