### ISSUE TITLE
Punch-Out driver has misaligned/disconnected hard dips

### ISSUE THREAD

**Issue by Sanaki** [libretro/FBNeo#670]
Punch-Out dipswitches in FBNeo are hooked up wrong it seems.

Rev B, Rev A, and Japan:
* Copyright - Test menu
* Coinage - Difficulty and Time dips
* Difficulty - Coinage A and B dips
* Time - Coinage C and D dips
* Music and Discount - disconnected

The Italian bootleg seems to not have a test menu or not have it hooked up, so I'm not sure if those ones align the same way.

Super Punch-Out appeared to line up approximately with Punch-Out, but I didn't test extensively beyond glancing to make sure it was misaligned as well.

Arm Wrestling appears misaligned (Coinage 1 dips affect slot 2 value and vice versa), but since I'm not clear how the dips should function in the first place, I'm not able to say much with confidence here. Service menu for Arm Wrestling does not function.

I didn't test if this affects upstream because I honestly have no idea how to even modify dips in the SDL2 Standalone.

**Comment by barbudreadmon** [comment]
it should be ok now, thanks for the report :)

**Comment by Sanaki** [comment]
Looks good to me. Thanks for the quick fix!
