### ISSUE TITLE
Incorrect CRC error on hacked roms and homebrews

### ISSUE THREAD

**Issue by neowitchy** [libretro/FBNeo#673]
I'm unable to play hacked and homebrew games in Retroarch, fails with incorrect CRC using FBNeo core, original FBNeo works perfectly and has a disable CRC checking option. https://github.com/finalburnneo/FBNeo/pull/721
![CRC_ERRIR_MESSAGE](https://user-images.githubusercontent.com/80604719/111088826-d7fed700-8507-11eb-8c6e-7f51e92b3437.png)

Original FBNeo don't have this problem and even without using this option, it just throw an error message and loads the game, in Retroarch it don't load.

Edit: Got the roms working by running the original roms and using the "Allow patched romsets option" + putting the homebrews/hacked games on system/fbneo/patched folder. Still, it's a lot of trouble for just loading a rom, and for loading homebrews, it needs you to have an original neogeo rom. (Without any reason)

RetroArch Version: 1.9.0
OS: Windows 10

**Comment by barbudreadmon** [comment]
Read doc https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#i-patched-game-xxx-and-cant-run-it-why-

**Comment by neowitchy** [comment]
> 
> 
> > Still, it's a lot of trouble for just loading a rom, and for loading homebrews, it needs you to have an original neogeo rom. (Without any reason)
> 
> Avoiding zillions of bug reports from ppl who have bad romsets is a good enough reason to enforce strict crc compliance, anyway this is documented : https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#i-patched-game-xxx-and-cant-run-it-why-
> **Making it more complex than simply enabling a core option is intentional**, since ppl would just enable this option, forget about it, use random bad romsets, then report issues. Just hearing it's too troublesome to have the good romsets give me the chills and reminds me that enforcing that strict crc compliance is the best decision i ever made about this core.

Got it, but when developing a game one would need to copy files to system/fbneo/patched after each compilation in order to test it in Retroarch. It also would make it harder for testing multiple versions of the same rom. A bash script can automate it, but don't seems to be a good fix.

Can you point me the part of the core in source that enforces CRC checking, so i can fork it with that option disabled?

**Comment by barbudreadmon** [comment]
You should be able to play around with this behavior by editing https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/libretro.cpp#L854

However, i'm wondering why it's more troublesome to place the hack/homebrew you are developping in system/fbneo/patched than in your normal romset folder, it should be about the same. Tbh, i'm even more surprised someone would want to use this libretro port for development purpose, since i would expect various debugging tools like a memory inspector would be recommended for that activity.
