### ISSUE TITLE
Raiden DX (US) "raidendxu" Dipswitch settings inaccurate 

### ISSUE THREAD

**Issue by Redemp** [libretro/FBNeo#686]
Dipswitch settings for Raiden DX (US) "raidendxu" are inaccurate 

Dipswitch settings for Difficulty in Retroarch compared to Diagnostic mode

Retroarch --> Diagnostic
Normal =  Normal 
Easy      =  Hard
Hard     =  Easy
Very Hard = Very Hard

**Comment by barbudreadmon** [comment]
Thanks for the report, it appears raidendxk & raidendxch had the same issue. It should be ok now.
