### ISSUE TITLE
Is there a way to split horizontal/vertical games ?

### ISSUE THREAD

**Issue by zzedmore** [libretro/FBNeo#689]
Hi, I know of the program RomLister and want to split the Arcade roms by orientation. Unfortunately there is no information of this in the datfile. Is there any way of doing this ? I checked the Mame2003plus datfile and that has information on what's horizontal/vertical but the romset is very old (and has some wrong/old names etc.)

The reason I would like this is -
1. So I can batch setup correct shaders for vertical/horizontal games.
2. A lot of the screenshots/previews are squashed/stretched so would like to correct them to 4:3 and 3:4 (like the FBNeo frontend does) except for the dual monitor games.

**Comment by barbudreadmon** [comment]
> So I can batch setup correct shaders for vertical/horizontal games.

FYI, the issue where slang shaders would incorrectly apply on vertical games was fixed in recent retroarch nightlies, afaik nowaday there should be no reason to use "special" shaders for vertical games.

Anyway i'm not against adding more information in the dat file, so i'll look into this.

**Comment by zzedmore** [comment]
At the moment i'm using Retropie, which is still using an older version of Retroarch (v1.8.8 I think ?!).

Regarding all the screenshot packs that are out there and the ArcadeDB, they all use the original resolution of the games before the monitor sizes them so some look very squashed or stretched when using them as a preview in Retropie. I thought of resizing them to mostly 4:3 / 3:4. I just tried the Mame 229 datfile with RomLister and it seemed to get most of them seperated as horizontal and vertical. I'm hoping all the rom names are the same as 229 (like for like) ?

**Comment by barbudreadmon** [comment]
No need to bother with mame's dat file, that information is available starting with https://github.com/libretro/FBNeo/commit/c51f30abe6fa45bc20d6675ac6e25dbd2287de33

> I'm hoping all the rom names are the same as 229

There is a number of hacks/homebrews we support and they don't.

**Comment by zzedmore** [comment]
> No need to bother with mame's dat file, that information is available starting with [c51f30a](https://github.com/libretro/FBNeo/commit/c51f30abe6fa45bc20d6675ac6e25dbd2287de33)
> 
> > I'm hoping all the rom names are the same as 229
> 
> There is a number of hacks/homebrews we support and they don't.

Nice one fella !! I'll check this out tomorrow. Cheers.
