### ISSUE TITLE
Metamorphic Force slowdown issue

### ISSUE THREAD

**Issue by pedralon** [libretro/FBNeo#694]
I''m using the core on a Genesis Mini with default settings. The game runs pretty fine until you reach stage 2 or any part of the game with that weaver effect in the background (stage 4, stage 5...).

**Comment by barbudreadmon** [comment]
That's expected, this game requires a decent device because of the raster effects. I'm surprised you can even launch the game since it requires a fair amount of memory too, and your device only has 256MB.
