### ISSUE TITLE
Donpachi samples do not work in 7z format

### ISSUE THREAD

**Issue by Sanaki** [libretro/FBNeo#699]
When playing `donpachi`, samples will not load if stored in 7z format. This seems to be related to samples being enabled by dipswitch, since 7z samples work in other games. I've ensured the archive is non-solid and repacked it a few times at different levels, but I've had no luck getting them to work. The same samples load fine in zip format.

Since I'm uncertain how to manipulate dipswitches in the SDL2 Linux standalone, I'm unable to test if this is an upstream issue.
EDIT: Found the dipswitches in SDL2 standalone, but the menu seems broken. Reported that in finalburnneo#742.

**Comment by barbudreadmon** [comment]
fails on https://github.com/libretro/FBNeo/blob/master/src/burner/zipfn.cpp#L356 , i'll look further into this tomorrow

**Comment by barbudreadmon** [comment]
it should be ok now

**Comment by Sanaki** [comment]
Confirmed fixed, thanks.
