### ISSUE TITLE
A way to change gamelist.xml rom names to FBNeo datfile description names ?

### ISSUE THREAD

**Issue by zzedmore** [libretro/FBNeo#701]
This is probably a silly question, but is there a way to do this ? For example, if I make a basic gamelist from my romset -

```
<?xml version="1.0"?>
<gameList>
	<game>
		<path>./3countb.zip</path>
		<name>3countb</name>
		<image>./images/3countb.png</image>
		<marquee>./flyers/3countb.png</marquee>
	</game>
	<game>
		<path>./64street.zip</path>
		<name>64street</name>
		<image>./images/64street.png</image>
		<marquee>./flyers/64street.png</marquee>
	</game>
</gameList>
```

Is there anyway to change the `<name>` section to what the FBNeo datfile description says ? I realise I could do this with a scraper but sometimes the names are slightly different to what you have in the datfile and it doesn't add the tags like [Homebrew] or [Wrong colours] etc. I'm thinking i'll probably have to add this manually ?

**Comment by barbudreadmon** [comment]
Sure, you would need to create a script that parse both xml files and replace the name in gamelist.xml by the one found in our dat file. Actually there might be 3rd party tools that already does that, anyway nothing unfeasible.
Also, please only open issues for FBNeo related issues. This is not a helper forum about emulationstation or scripting...

**Comment by zzedmore** [comment]
Yeah sorry. I don't suppose you know the name of these 3rd party tools ?
