### ISSUE TITLE
[KOF 2003] - FBNeo breaks.

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/FBNeo#709]
- KOF2003 breaks the core FBNeo. The same rom works perfectly with FBA2012/FBA2012_Neo.

- The rom version is correct.

- I tried the FBNeo core with other games like garou, kof2000, kof2001 and matrimelee and them work perfectly.

- Core version used: Last one (04/04/2021) and one from 03/23/2021. 

Logs
[retroarch__2021_04_04__12_59_03.log](https://github.com/libretro/FBNeo/files/6254932/retroarch__2021_04_04__12_59_03.log)
 attached.
[retroarch__2021_04_04__12_59_53.log](https://github.com/libretro/FBNeo/files/6254931/retroarch__2021_04_04__12_59_53.log)

**Comment by barbudreadmon** [comment]
https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#on-my-android-device-game-xxx-is-closing-my-app-at-launch-why-
