### ISSUE TITLE
FBNeo doesnt detect bios' in system directory

### ISSUE THREAD

**Issue by klepp0906** [libretro/FBNeo#72]
While it does "detect" it as far as it working properly, the core information doesnt correlate.

I confirmed by running a rom with the bios in the system directory, and then attempting to run it without.

![image](https://user-images.githubusercontent.com/10392920/59936668-99b1b200-941e-11e9-88b2-592c8fb4b3c6.png)

![image](https://user-images.githubusercontent.com/10392920/59936725-b948da80-941e-11e9-8355-37133a04cf39.png)

its very helpful to be able to actually "see" that you have the bios installed in the proper directory and working.  I use core information to confirm that being the case for all other cores.

I did try other versions of the bios, as well as some of the other requested bios.  Same result.  Detection appears to be broken in the GUI.

Thank you

**Comment by barbudreadmon** [comment]
It's not broken, expected path for bioses is `system_dir/fbneo/`, but the core will tolerate using the bioses at the root of `system_dir` as a fallback.
Basically the core search for parents/bioses through 3 paths in this order : 
1. rom_dir
2. system_dir/fbneo
3. system_dir

Yeah, you can also store parents in the system_dir folders, that's especially interesting for games with working clones but non-working parents (there are a few).

**Comment by klepp0906** [comment]
ah.  so if moved to fbneo/neogeo.zip it should detect correctly?

apologies, the core info simply indicated (with roms or in system directory) so I assumed it was the root of the system directory

**Comment by barbudreadmon** [comment]
No problem, it's kinda unclear with the way RA is displaying core informations, maybe i should improve the notes.
