### ISSUE TITLE
A question about cheat support

### ISSUE THREAD

**Issue by MarcoBorrini99** [libretro/FBNeo#725]
On my Pi400 with an up2dated RetroPie official image,

i'm trying to understand how non RetroArch cheats work.

Reading README.md i see: "[...] Otherwise if you put native FBNeo cheat .ini files (there is a pack available here) into SYSTEM_DIRECTORY/fbneo/cheats, they will be translated to core options, using a MAME cheat.dat file should also work"

So:

a) I've tried, for example, Armed Police Batrider cheat (batrider.ini) in 

- "/opt/retropie/configs/all/retroarch/cheats/FinalBurn Neo/"
- "/home/pi/RetroPie/BIOS/fbneo/cheats/" 

but nothing seems to happen. In which RetroArch menu do I need to look at?

b) the same for MAME cheat.dat file, after putting in the same dirs , what I have to do?

Regards.

**Comment by barbudreadmon** [comment]
Hmmm i'm not a retropie expert but the `/home/pi/RetroPie/BIOS/fbneo/cheats/` path sounds about right.

When you say "up2dated RetroPie official image", does that mean you updated the core from sources ? I have absolutely no idea what version retropie's pre-packaged FBNeo binary is based on, it could be several years old as far as i know, and i added that `.ini` cheats support only around a year ago (and last week for `cheat.dat`).

**Comment by MarcoBorrini99** [comment]
> Hmmm i'm not a retropie expert but the `/home/pi/RetroPie/BIOS/fbneo/cheats/` path sounds about right.
> 
> When you say "up2dated RetroPie official image", does that mean you updated the core from sources ? I have absolutely no idea what version retropie's pre-packaged FBNeo binary is based on, it could be several years old as far as i know, and i added that `.ini` cheats support only around a year ago (and last week for `cheat.dat`).

I mean later updated from source (**Revert "(libretro) avoid filestream on android"** commit is the last one)

Anyway my fault, my SD was corrupted and with a recompiled lr-fbneo on my external SSD I confirm that cheat in *.ini format works.

**About mame cheat.dat:** just noticed that 
mame2003plus version is not working but https://www.mamechannel.it/files_support/cheat126.zip is instead functional.
for a game it's not possibile to have FBNeo and MAME cheat listed at the same time, FBNeo always wins; only exception a game not listed in FBNeo cheat

I close this issue...

**Comment by barbudreadmon** [comment]
I don't know much about cheat.dat and its different revisions, but i'm guessing mame2003plus is using an older one ?
You might want to use the cheat.dat from https://neo-source.com/index.php?topic=3617.0 (this one is maintained by one of our developpers), and yeah `.ini` is taking priority since it's our own format.

**Comment by MarcoBorrini99** [comment]
> I don't know much about cheat.dat and its different revisions, but i'm guessing mame2003plus is using an older one ?
> You might want to use the cheat.dat from https://neo-source.com/index.php?topic=3617.0 (this one is maintained by one of our developpers), and yeah `.ini` is taking priority since it's our own format.

Indeed this one is much more complete, could I only suggest to include it and ini files directly in lr-fbneo official repo?

Regards

**Comment by barbudreadmon** [comment]
i guess we could add that cheat.dat to https://github.com/finalburnneo/FBNeo-cheats, i've no intention to copy those files over to the emulator repo, that's a bad idea.
