### ISSUE TITLE
DAT.files for The Capcom Play System Series of Games (and also Neo Geo AES only DAT)

### ISSUE THREAD

**Issue by neongo** [libretro/FBNeo#726]
Hello there FBNeo,

I want to put out a recommendation to the dat.files for RetroArch. I like the dat.files you guys made to help track the games that are listed in that file, Especially for the Neo Geo games, Thanks for that, But here's one thing, I'm a person that likes to also get the AES Versions of Neo Geo games, But it hard to track how many AES games are there, so can you please make a dat.file for the Neo Geo AES versions. And also, I really want dat.files for all 3 Capcom Play System Arcade Games.

Thanks for listening.

(And Yes, I know this isn't a issue, but I just was a idiot and didn't put it on the Pull Requests section.

**Comment by barbudreadmon** [comment]
No, i don't even understand what you mean by a neogeo aes dat file, there is no difference between an aes & a mvs cartridge, only the bios. I won't do add cps only dat files either : i heard there are tools to filter dat files by system/genre/whatever, search on google and use them.
