### ISSUE TITLE
hate to bother you guys again but BIOS choice not saving globally?

### ISSUE THREAD

**Issue by klepp0906** [libretro/FBNeo#73]
Ok, this is not behaving like other cores im used to (and i can understand why to a degree) but let me explain what im trying to do - and the issue im running up against.

I am in the process of creating an SNK neo geo (aes only) playlist.   I want to use FBA neo as the core, however for it to function properly I need to set it as dipswitch, and chose the AES asia bios.

otherwise if i choose AES mode, it defaults to japanese language bios for some reason.  This leaves me either having to delete the neo-po.bin (i believe it is) all together from the neogeo.zip at which point it uses the neo-epo.bin, or using dipswitch mode and selecting it manually.

So I expected to be able to select DIPSWITCH, and choose AES Asia bios and have that be my global setting for my games.  (that or find a way to make it choose the english bios in AES mode without deleting the other)

Every time i start a new game, it asks me to "insert coin" again.  So i checked the settings, and while it was saving the Force neo geo mode - DIPSWITCH setting, it would continually Reset BIOS to (Default) MVS Asia/Europe.

Now checking the core options, it would save this on a per game basis, but id very much like to NOT have to set this for every game independently.

Is this a bug, intended, or am i doing something incorrectly?  Usually core options are saved globally unless set otherwise via overrides and such. 

Thank you for your time.

**Comment by barbudreadmon** [comment]
dipswitches are per-game, deleting `neo-po.bin` might be your best bet.

**Comment by klepp0906** [comment]
yea, it looks like its the only option i have.  I even tried an override but i think those only apply to non core options.

Any chance we can get a global region select option in the core options?   auto/japan/europe/usa perhaps?

**Comment by klepp0906** [comment]
also, where does unibios save its config?  That seems to be per game as well?

**Comment by barbudreadmon** [comment]
> Any chance we can get a global region select option in the core options? auto/japan/europe/usa perhaps?

In the first place, i really want to remove current MVS|AES|UNIBIOS|DIPSWITCHES option and only use the dipswitch for the following reasons :  
- there is a lot of confusion about this because of the real core option
- this code is a mess
- main reason for this mess is that some game support only specific bioses
- i prefer being 1:1 with upstream, it makes debugging easier, and upstream only has the dispswitch

Having a third core option to turn this into a bigger mess is definitely not something i want.

> also, where does unibios save its config? That seems to be per game as well?

unibios settings are stored into the game eeprom, so yes it's per-game.

**Comment by klepp0906** [comment]
ah, didnt realize this wasnt tied into upstream.  Never used the standalone.

I totally understand your stance on the third option.  It would be redundant more or less, if you had things your way with dipswitch only.  

would implementing it dipswitch only afford the option to have global settings for core options?  If some games need specific bios i imagine changing it for a choice game here or there is the lesser evil, depending on how few and far between those are.

either way, you'd know better than I.   Certainly appreciate your having replied and clarified some of that :)

**Comment by barbudreadmon** [comment]
> would implementing it dipswitch only afford the option to have global settings for core options?

No, the dipswitches are per-game, that's why i kept the old core option, this old core option is actually a remnant from the era when dips weren't implemented in this core.
