### ISSUE TITLE
 "This romset is known but yours doesn't match this emulator..etc"

### ISSUE THREAD

**Issue by mantheman** [libretro/FBNeo#758]
I used Retroarch 1.9.2 with the latest FBNEO and got this screen up. "This romset is known but yours doesn't match this emulator..etc". That is all and well, but it after this I cant get back to retroarch. I have to restart Retroarch. Wouldn't the expected behavior be just display the information bubbles with the errors and go straight back to retroarch instead of displaying a Win 3.11 dialog box :)
![unnamed (2)](https://user-images.githubusercontent.com/8033918/117385398-5020c200-aee5-11eb-8b27-832a977cf60c.jpg)

**Comment by barbudreadmon** [comment]
> Wouldn't the expected behavior be just display the information bubbles with the errors and go straight back to retroarch instead of displaying a Win 3.11 dialog box :)

In an ideal world where retroarch wouldn't close without showing those bubbles, and users would look at their logs, yes, even better, in an ideal world where people would read documentation about FBNeo without me having to insist about it.
Too bad we don't live in that ideal world and that i end up having to write that kind of message in full screen.

**Comment by barbudreadmon** [comment]
>I am not sure if that is the right thing to do

As i said, in a better world, it would not, we don't live in that world though. In the world we live in, people don't understand when retroarch is closing, and for whatever reason those information bubbles are invisible to their eyes.

**Comment by mantheman** [comment]
But Retroarch isn't closing..it's that the you can't press the dialog away to get back to the Retroarch GUI. 

I am even OK with that big dialog box, but give me an OK button so I can confirm that I understand and get back to the Retroarch GUI, or simply let me press the "back" button to get to the GUI. Now I actually have to restart Retroarch because FBNeo pop up an informational dialog  that I can't escape. (But tbh the info bubbles are enough).

Even though I'll make a new romset that is 100% compatible, sometime I have a folder with different roms that I sometimes try with different emulators. I shouldn't have to restart Retroarch each time FBNeo is incompatible with a ROM.

**Comment by barbudreadmon** [comment]
>But Retroarch isn't closing.

It did in the past, and that's why i replaced that behavior. People are happy with that change since now they don't have to read logs, sorry you don't, in the first place you wouldn't get that message if you followed documentation...

I'll copy this message from the FAQ and lock this topic : 

> Use clrmamepro (which runs fine on linux with wine and on mac with crossover) to build valid romsets with dats from the dats directory. Don't report issues if you didn't build a valid romset. Also, i don't provide a "parent-only" dat file, because i don't recommend using only parent roms (some don't work, and some clones are really different from their parent)
