### ISSUE TITLE
ladybug: black screen only

### ISSUE THREAD

**Issue by toccata10** [libretro/FBNeo#76]
ladybug, ladybugb, ladybugb2: all display just a black screen.
ladybugg (based on galaxian hardware) works fine.
I'm on Archlinux, r9 fury, mesa 19.1.
It doesn't work on fba neither. On the console, I see "[libretro INFO] [FBNEO] Using ROM with good CRC and name...", so the rom is probably fine.

**Comment by barbudreadmon** [comment]
I can't reproduce this issue, i'll need full logs to make sure you aren't doing something unusual.

**Comment by toccata10** [comment]
It's a problem with my shader: when I use crt-geom.glsl, the screen is black.
If I remove it or change to crt-calligari.glsl: it works fine.
So, I'm closing this as it's not directly related to fbneo.
