### ISSUE TITLE
No inputs on buttons A,B,C for Metal Slug 4 (console mode Uni Bios)(Lakka OS) (RPI 4)

### ISSUE THREAD

**Issue by Rstation4** [libretro/FBNeo#777]
Raspberry Pi 4 2GB
Lakka version: Lakka-RPi4.arm-nightly-20210518-2bbd8bb

Rom: Metal Slug 4
Bios used: Uni Bios 4.0 and Uni Bios 3.2
When Using Uni Bios 4.0 and even 3.2 there are no input responses for the A,B and C buttons. I can move my character but thats it. When switching to either Japanese, USA and Europe regions this still occurs only with the console version, switching to the arcade version it works as normal.

logs
[FBNeo MS4.log](https://github.com/libretro/FBNeo/files/6520561/FBNeo.MS4.log)

I did a run with the default mvs bios then exited before switching to the Uni Bios 4.0 as you will see on the log

**Comment by barbudreadmon** [comment]
Unibios has [lots of known issues in console mode](http://unibios.free.fr/knownissues.html), it looks like one of them : 
> Later games in the Metal Slug and Samurai Shodown series (MS X,3,4,5 and SS 4,5,5Sp) may not work correctly in console mode until after you have set up the game settings and controller config in the options menu (after starting a game). This problem is due to the games not setting up the initial backup ram data correctly for console mode if the game is first run on the system while it is in ARCADE mode (you must experience a 'GAME OVER' before the new settings are permanently saved).

Anyway, that's not a FBNeo issue, the inputs are properly sent to the hardware.

**Comment by Rstation4** [comment]
It looks like it was fixed with the latest stable 3.0 release for the Raspberry Pi 4.
