### ISSUE TITLE
Forced 60hz framerate, but no option to disable it in UI

### ISSUE THREAD

**Issue by SZYM0NEK** [libretro/FBNeo#796]
Hi,

Today I've noticed that latest nightly build of this core in retroarch forces vide output to 60 fps instead of native game's framerate.

All Mortal Kombat arcade games run now in 60 fps, but they should run in 55 fps.

Core from 31.05.2021 runs fine, with 55 fps in MK games.

I wonder if this is a bug, or are you just implementing "Force 60hz" video output feature, but there is no UI option to disable it yet.

I'm on Windows 10 21H1 
RetroArch x64 v1.9.4

**Comment by barbudreadmon** [comment]
yeah, i did a mistake yesterday and pushed a fix 1 hour ago : https://github.com/libretro/FBNeo/commit/bca9175efcd78601f4f1dc997b11c7cc73536e74
