### ISSUE TITLE
Compile fails on latest ~head

### ISSUE THREAD

**Issue by Ntemis** [libretro/FBNeo#804]
<command-line>: warning: "_LARGEFILE64_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_FILE_OFFSET_BITS" redefined
<command-line>: note: this is the location of the previous definition
../../cpu/c68000_intf.cpp:641:13: error: ‘void SekCPUPush(INT32)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
  641 | static void SekCPUPush(INT32 nCPU)
      |             ^~~~~~~~~~
In file included from ../../cpu/c68000_intf.cpp:4:
../../cpu/m68000_intf.h:140:6: note: previous declaration of ‘void SekCPUPush(INT32)’
  140 | void SekCPUPush(INT32 nCPU);
      |      ^~~~~~~~~~
../../cpu/c68000_intf.cpp:659:13: error: ‘void SekCPUPop()’ was declared ‘extern’ and later ‘static’ [-fpermissive]
  659 | static void SekCPUPop()
      |             ^~~~~~~~~
In file included from ../../cpu/c68000_intf.cpp:4:
../../cpu/m68000_intf.h:141:6: note: previous declaration of ‘void SekCPUPop()’
  141 | void SekCPUPop();
      |      ^~~~~~~~~
../../cpu/c68000_intf.cpp:39:15: warning: ‘UINT32 c68k_get_virq(UINT32)’ defined but not used [-Wunused-function]
   39 | static UINT32 c68k_get_virq(UINT32 level)
      |               ^~~~~~~~~~~~~
make[2]: *** [Makefile:710: ../../cpu/c68000_intf.o] Error 1
make[2]: *** Waiting for unfinished jobs....
<command-line>: warning: "_LARGEFILE64_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_FILE_OFFSET_BITS" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_LARGEFILE64_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_FILE_OFFSET_BITS" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_LARGEFILE64_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_FILE_OFFSET_BITS" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_LARGEFILE64_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_FILE_OFFSET_BITS" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_LARGEFILE64_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_FILE_OFFSET_BITS" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_LARGEFILE64_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_FILE_OFFSET_BITS" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_LARGEFILE64_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_FILE_OFFSET_BITS" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_LARGEFILE64_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "_FILE_OFFSET_BITS" redefined
<command-line>: note: this is the location of the previous definition

**Comment by barbudreadmon** [comment]
Oops, i forgot to backport m68000_intf.cpp changes to c68000_intf.cpp, fixed with https://github.com/libretro/FBNeo/commit/41bfd578dda019fb649c34a3653b89aaf75cabe9, thanks for the report.
