### ISSUE TITLE
Highscores are not saving for System 32 arcade board games

### ISSUE THREAD

**Issue by FeRcHuLeS** [libretro/FBNeo#808]
The newly supported System 32 games don't save highscores
tested Air Rescue, Alien 3 The gun. 
- The latest highscore.dat file from this repository was used
- Run-ahead and Rewind are off
- Another arcade board games are working
- There is no Overrides config related

**Comment by barbudreadmon** [comment]
Support is now added, some clarification though : lots of sega s32 games don't exist in hiscore.dat, but it might be that they are saving hiscores in their eeproms instead.

**Comment by FeRcHuLeS** [comment]
It's working now, there are 2 files related .hi and .nv before there was .nv only, just wondering whether .hi, .nv, .fs files are compatible with MAME 2003 plus at least?

**Comment by barbudreadmon** [comment]
no idea, you'll have to try

**Comment by FeRcHuLeS** [comment]
I tried highscoress files compability between FBNeo and MAME 2003 Plus for the following games:

- Ghouls'n Ghosts (.hi)
- Alien 3 The Gun (.hi, .nv) 

The highscores are compatible as result, not sure whether .fs files are compatible with MAME 2003 Plus, good to know there's compatibility between cores.
