### ISSUE TITLE
3Punch / 3Kick

### ISSUE THREAD

**Issue by derekfcc** [libretro/FBNeo#813]
Building a Pi4 and I didn't see an option for 3xPunch or 3xKick on the Capcom fighters.  Did this option get removed from the FBA lineup?  I also didn't see options for things like "A+B" or any of the various button combos that were present in FBA.  Is there a way to bring this back?

**Comment by leoxxx** [comment]
https://github.com/libretro/FBNeo/issues/51
https://github.com/libretro/RetroArch/issues/8209
It should be in retroarch.

**Comment by barbudreadmon** [comment]
> Did this option get removed from the FBA lineup?

This is the FBNeo core repository, i don't know nor care about the old FBA forks, 3xKick & 3xPunch buttons are available for capcom fighters in the latest versions of our core, same for AB/CD/ABC/BCD for neogeo games.
