### ISSUE TITLE
WEC Le Mans 24 - Missing P1 Accelerator key mapping

### ISSUE THREAD

**Issue by ner00** [libretro/FBNeo#822]
Game works fine in standalone emulator, has P1 Accelerator activated and mapped by default, but the core is missing the mapping for the acceleration input.  These are the current existing mappings provided by the core:

- Steering (Fake Digital Left)
- Steering (Fake Digital Right)
- Brake
- Gear Shift
- Coin
- Start
- Steering -
- Steering +

It's missing the accelerator for some reason.

**Comment by barbudreadmon** [comment]
Oops, thanks for the report, fix is on git
