### ISSUE TITLE
AES / Console Mode for Magician Lord not working

### ISSUE THREAD

**Issue by HoJo215** [libretro/FBNeo#828]
I'm running on Ubuntu 18.04.
Retroarch and FBNeo core are updated to the latest.
I have the full neogeo.zip

So I can't for the life of me get this game running in console mode.
I tried AES mode in the bios and Universe Bios set to Console Mode.
No matter what it plays in MVS mode.

Is AES / Console Mode broken for this game?

**Comment by barbudreadmon** [comment]
It's working here : 

![maglord-210708-160620](https://user-images.githubusercontent.com/10391265/124936337-ba99cf80-e006-11eb-98b9-bbc544d7127e.png)

Maybe with logs i would be able to help

**Comment by HoJo215** [comment]
I get that screen with the memory card too but the AES exclusive cut scenes don't play..
So I thought it was still in MVS mode. Here is what I'm talking about:

[https://youtu.be/7mTaYFgTlGE?t=37](url)

Its supposed to happen after you press start and don't skip the tutorial right after showing the different powers.
I'm out right now. Ill post a log later today.

**Comment by barbudreadmon** [comment]
Those cut scenes are from the `maglordh` romset.
