### ISSUE TITLE
Service / Reset buttons are mapped over regular inputs

### ISSUE THREAD

**Issue by ckeisc** [libretro/FBNeo#833]
I start seeing this issue after upgrading to 1.9.4, I upgrade infrequently, so not sure when it was introduced, but looking at related code path, I wonder if this change in 1.9.2 might be related (- INPUT: Ensure that 'retro_set_controller_port_device' is called when updating 'Max Users'). Here is what I see:

I have many input devices map connected to the PC, 1 USB wireless keyboard, 1 USB keyboard encoder, 2 generic USB joystick encoder and a MayFlash Dolphin bar in mode 2 (which emulates a keyboard + a mouse). Retroarch is set to have max users = 5. 4 User's input mappings are set up, 2 users map to keyboard and another 2 map to joysticks.

The problem typically does not happen for the first game loaded. But after closing content and loading a second game, the service or reset button would be mapped to a player's button. Such as player 2's directional input, or player 3's button 1 or 2.

I enabled logging and compared the working and bugged runs, and noticed something in the log. I am attaching the 2 logs below for reference. When the issue repros, I can see that SetInputDescriptors() in retro_input.cpp was called 4 times, each time with one more port than the previous call. And I think when that happens, GameInpOtherOne() would somehow map service and reset button over one of the input for player 2 or 3 or 4. I am seeing this after loading TMNT 2 - Turtles In Time or Sunset Rider (same driver).

> Log 1 - working
[libretro INFO] [FBNeo] Unknown device type for port 0, forcing "Classic" instead
[libretro INFO] [FBNeo] Unknown device type for port 1, forcing "Classic" instead
[libretro INFO] [FBNeo] Unknown device type for port 2, forcing "Classic" instead
[libretro INFO] [FBNeo] Unknown device type for port 3, forcing "Classic" instead
[INFO] [Shaders]:  Finding Parameters in Shader Passes (#pragma parameter)
[INFO] [Shaders]:    Loading base parameter values
[INFO] [Shaders]:      Load parameter value:   MASK = 0.000000.
[INFO] [Shaders]:      Load parameter value:   MASK_INTENSITY = 0.500000.
[INFO] [Shaders]:      Load parameter value:   SCANLINE_THINNESS = 0.500000.
[INFO] [Shaders]:      Load parameter value:   SCAN_BLUR = 2.500000.
[INFO] [Shaders]:      Load parameter value:   CURVATURE = 0.020000.
[INFO] [Shaders]:      Load parameter value:   TRINITRON_CURVE = 0.000000.
[INFO] [Shaders]:      Load parameter value:   CORNER = 3.000000.
[INFO] [Shaders]:      Load parameter value:   CRT_GAMMA = 2.400000.
[INFO] [Playlist]: Loading history file: [C:\Users\arcad\OneDrive\Emulator Classics\RetroArch_TMNT\content_history.lpl].
[INFO] [Playlist]: Loading history file: [C:\Users\arcad\OneDrive\Emulator Classics\RetroArch_TMNT\content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [C:\Users\arcad\OneDrive\Emulator Classics\RetroArch_TMNT\content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [C:\Users\arcad\OneDrive\Emulator Classics\RetroArch_TMNT\content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [C:\Users\arcad\OneDrive\Emulator Classics\RetroArch_TMNT\content_favorites.lpl].
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, Port 1, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 1, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 1, Button "A (right)" => "Fire 2"
[INFO] 	RetroPad, Port 2, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 2, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 2, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 2, Button "A (right)" => "Fire 2"
[INFO] 	RetroPad, Port 3, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 3, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 3, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 3, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 3, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 3, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 3, Button "A (right)" => "Fire 2"
[INFO] 	RetroPad, Port 4, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 4, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 4, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 4, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 4, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 4, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 4, Button "A (right)" => "Fire 2"
>
> Log 2 - reset / service mapped over player input
[libretro INFO] [FBNeo] Unknown device type for port 0, forcing "Classic" instead
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, Port 1, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 1, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 1, Button "A (right)" => "Fire 2"
[libretro INFO] [FBNeo] Unknown device type for port 1, forcing "Classic" instead
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, Port 1, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 1, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 1, Button "A (right)" => "Fire 2"
[INFO] 	RetroPad, Port 2, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 2, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 2, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 2, Button "A (right)" => "Fire 2"
[libretro INFO] [FBNeo] Unknown device type for port 2, forcing "Classic" instead
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, Port 1, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 1, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 1, Button "A (right)" => "Fire 2"
[INFO] 	RetroPad, Port 2, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 2, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 2, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 2, Button "A (right)" => "Fire 2"
[INFO] 	RetroPad, Port 3, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 3, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 3, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 3, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 3, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 3, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 3, Button "A (right)" => "Fire 2"
[libretro INFO] [FBNeo] Unknown device type for port 3, forcing "Classic" instead
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, Port 1, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 1, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 1, Button "A (right)" => "Fire 2"
[INFO] 	RetroPad, Port 2, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 2, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 2, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 2, Button "A (right)" => "Fire 2"
[INFO] 	RetroPad, Port 3, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 3, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 3, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 3, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 3, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 3, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 3, Button "A (right)" => "Fire 2"
[INFO] 	RetroPad, Port 4, Button "B (bottom)" => "Fire 1"
[INFO] 	RetroPad, Port 4, Button "Select" => "Coin"
[INFO] 	RetroPad, Port 4, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 4, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 4, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 4, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 4, Button "A (right)" => "Fire 2"
>

**Comment by ckeisc** [comment]
The problem goes away if I rename the folder containing Retroarch.exe. No idea why. I renamed the folder back and forth a few times. It only repros with original folder name.

**Comment by barbudreadmon** [comment]
Thanks for letting me know, i've a feeling it might be related to some weird reports i saw lately, i'll try to figure out what could be causing this

**Comment by barbudreadmon** [comment]
I can't reproduce this at all, but i tried to take care of the only scenario i could imagine in my last commit, let me know if it solved the issue after it's available from the buildbot

**Comment by barbudreadmon** [comment]
@ckeisc are you still able to reproduce this issue with latest nightly ?

**Comment by ckeisc** [comment]
@barbudreadmon tested latest nightly and the issue no longer repro!
