### ISSUE TITLE
Express Raider Sound Problem

### ISSUE THREAD

**Issue by ToniBC** [libretro/FBNeo#838]
Hello, I recently detected that the sound of the explosions in this game sounds bad, like distorted. It only happens with the explosions of the bottles that the enemies throw, the rest sounds good.

The same Rom in MAME goes without problems.

I have deactivated the Interpolation and the LowPass Filter and the same thing happens, only that sound effect goes wrong.

In the attached video I show the problem.

https://user-images.githubusercontent.com/45365478/125532193-773ec9d6-7a71-4465-95eb-ef462f57e83d.mp4

All tested with the latest nightly and updated core on Windows x64.

Thanks.

**Comment by barbudreadmon** [comment]
This one is beyond my skills, let's ask @dinkc64 for help :)

**Comment by ToniBC** [comment]
It's a strange bug for that, it only affects explosions, and when running it through MAME within Retroarch, it doesn't pass, so it seems like it's some of the volume, going over 100% and distorting. If the filters are removed, it diffuses a bit, but it still shows.

By the way, it is the second level of the game.

**Comment by barbudreadmon** [comment]
>By the way, it is the second level of the game.

A savestate would help

**Comment by dinkc64** [comment]
barbudreadmon, for your fbneo notebook:
Some fm chips like the ym2203 have an ay8910-compatible chip onboard, it's actually a ym2149, which is yamaha's version of the 8910.  For whatever reason, the ay8910-type chips usually sound good under 0.15 (volume), and anything above distorts.
If ya notice the ym2203 sets all routes to .30, which is way too high for the psg part of the chip.  
So basically, if the game only has fm chips and one of the sounds distort, look to see if it has a psg attached to it and lower the volume.

best regards,
- dink

**Comment by ToniBC** [comment]
I attach the savestate to make it easier.

[exprraid save sound bug.zip](https://github.com/libretro/FBNeo/files/6816753/exprraid.save.sound.bug.zip)

**Comment by barbudreadmon** [comment]
@dinkc64 thanks for the heads up !

**Comment by ToniBC** [comment]
Sounds good, thank you very much.
