### ISSUE TITLE
Super Sidekicks 2 (Neo-Geo) error in the field

### ISSUE THREAD

**Issue by ToniBC** [libretro/FBNeo#84]
The game has errors in the field of play, in the lower part and on the sides the screen is not drawn as the image is shown.

![ssideki2-190702-014128](https://user-images.githubusercontent.com/45365478/60472968-5dc2ec00-9c6b-11e9-9628-02a08eee5f94.png)

**Comment by barbudreadmon** [comment]
I confirm, there is some kind of "clipping" on the tiles, let's tag @dinkc64 about this

**Comment by dinkc64** [comment]
it's really a timing issue, game is very sensitive :(  At least, the cd version is good I think.  I will debug it tonight.

**Comment by barbudreadmon** [comment]
The issue was fixed a few days ago, closing

**Comment by dinkc64** [comment]
oops, sorry - forgot to mention that it was fixed! :)
