### ISSUE TITLE
Mortal Kombat II Sound

### ISSUE THREAD

**Issue by blisstik** [libretro/FBNeo#841]
Hi there,

I adjust the volume via dip switch, then I exit. It gives me some message. I hold the button for dip switch again, then I exit one more time, the message is gone. I close the content then go back to check if the volume setting is sticking. It is.

The issue is when I play the game, the volume is still low.

This does NOT happen to the rest of the Midway games (UMK3, NBA Maximum Hangtime, Open Ice). All have loud sounds.

**Comment by barbudreadmon** [comment]
Hmm the default volume sounds pretty normal to me, i wouldn't call it "low". Are you sure you are using the latest version of the core ?

**Comment by blisstik** [comment]
I could not find an eeprom file. I did find an `.fs` file.

Anyways, the point being is if you turn up the volume via Service Menu (hold start), it doesn't seem to have an effect while the other games do.

This is on the latest master RA and 2021-07-11 romset.

**Comment by blisstik** [comment]
I don't think I mentioned my device. It's NVIDIA Shield TV tube style so its 32bit OS.

**Comment by barbudreadmon** [comment]
> I did find an .fs file.

That's an eeprom file

>This is on the latest master RA

Core is latest too ?

>Anyways, the point being is if you turn up the volume via Service Menu (hold start), it doesn't seem to have an effect while the other games do.

It might be the case, however i want to first figure out why the sound would be too low on your setup, because expecting users to go into service menu and upping the volume was never a proper solution as far as we are concerned.

**Comment by dinkc64** [comment]
The problem has been fixed, thanks for the bug report!
barbudreadmon will probably respond here when the fix makes it into the libretro side for you to try.

best regards,
- dink

**Comment by barbudreadmon** [comment]
merged :)

**Comment by blisstik** [comment]
Thank you! I can confirm it's fixed.
