### ISSUE TITLE
Something wrong with heatbrl dipswitches and 3 and 4 players credit and start keys

### ISSUE THREAD

**Issue by furiadeoso** [libretro/FBNeo#862]
Hi @barbudreadmon ! How are you? 

I've been away for a while. First of all, congratulations to the FBNeo team for all the new games added in the last year.

Something weird is happening with Heated Barrel (heatbrl). We were using a 2021 may version of FBneo core and 3 and 4 players START key were not working.

A moment ago, I tried to update to the latest version of the core to see if it was fixed. In the options I change to a 4 players , but now it is not changed in the game and I only see two players at the top of the screen.

Opening the service menu (at the same time I reset), START button of the third player still don't work:
![image](https://user-images.githubusercontent.com/34688502/128605183-6e77356f-d388-44dc-a8e4-05836e2f70bf.png)

Could you take a look? Thanks!

**Comment by barbudreadmon** [comment]
Thanks for the report, the fix is on git, i've been wondering how you reached that "TEST SWITCHES" screen though ?

**Comment by furiadeoso** [comment]
> Thanks for the report, the fix is on git, i've been wondering how you reached that "TEST SWITCHES" screen though ?

Press reset key and immediately (or simultaneously) press service combination (in my case start + a + b)

**Comment by barbudreadmon** [comment]
Thanks, it allowed me to confirm everything was fine now, closing !

**Comment by furiadeoso** [comment]
> Thanks, it allowed me to confirm everything was fine now, closing !

Thanks! I will test it on Netplay ASAP.

**Comment by furiadeoso** [comment]
@barbudreadmon In my community they tell me that it works.  But they tell me there is a small issue.  Players 3 and 4, when they press credit key, they give it one credit to all players.  I do not know if perhaps it is a machine issue.

**Comment by barbudreadmon** [comment]
Well, that's probably related to some dipswitch settings, which are very confusing. They are matching [MAME's](https://github.com/mamedev/mame/blob/47e91b2686d17be12635852ba32cce766ab15c83/src/mame/drivers/legionna.cpp#L578-L638) so i believe it's ok.

**Comment by furiadeoso** [comment]
Ok. The main thing is that now we can play with 4 players! Thank you very much.
