### ISSUE TITLE
Super Street Fighter II Turbo Speed Problem?

### ISSUE THREAD

**Issue by ToniBC** [libretro/FBNeo#886]
Hi, I was recently told that this game works really fast, so I gave it a try, but I see different things on FBNeo regarding MAME.
That is, the game is the Turn version that is obviously faster, even entering the service menu and setting the Turbo speed to 0 or any other value, the game indicates it on the presentation screen before the fight, it shows that These turbo, but it seems that this speed value is not applied, it seems to always work at the same speed.

Something similar happens in MAME, that is, if we put the same game in MAME 0.235, the game goes faster than in FBNeo, which is rare, but it seems to have the same problem that the selected speed is not applied well.

I don't know, I notice that the game in FBNeo is always at speed 1 and in MAME always at 3 or 2, but something is wrong.

See if someone else can do tests and if they notice the same.

Thanks.

**Comment by barbudreadmon** [comment]
The speed should be right, see https://github.com/finalburnneo/FBNeo/commit/6eaad09d968d2d71fe17cc51657f804b511aecba

**Comment by ToniBC** [comment]
That is to say, that in FBNeo the speed that is seen is correct or we have to adjust the overclock for that game. I think it is the correct one, that it has already been adjusted to correct that, but it is not clear to me.

We don't have to touch anything, right?

**Comment by barbudreadmon** [comment]
>We don't have to touch anything, right?

Yes, the speed was apparently already corrected using pcb video.
