### ISSUE TITLE
[FunKey S] "LIGHT = 1" makes the compilation fail.

### ISSUE THREAD

**Issue by DrUm78** [libretro/FBNeo#900]
Platform: FunKey S ARMv7a 32-bit cpu.

"LIGHT = 1" makes the compilation fail with the FunKey S toolchain (see the compilation error below, only a sample as there are 3,000+ lines). Please note that it works without it and runs on the FK device so it's not useful here. This parameter was originally here to fix a bug whose root cause was in fact a bug in Street Fighter layout: https://github.com/libretro/FBNeo/issues/818#issuecomment-876346849

```
/opt/FunKey-sdk/bin/../lib/gcc/arm-funkey-linux-musleabihf/10.2.0/../../../../arm-funkey-linux-musleabihf/bin/ld: /tmp/fbneo_libretro.so.JUItkX.ltrans9.ltrans.o:(.data.rel.ro+0x10e74): undefined reference to `BurnDrvnes_zoomisec'
/opt/FunKey-sdk/bin/../lib/gcc/arm-funkey-linux-musleabihf/10.2.0/../../../../arm-funkey-linux-musleabihf/bin/ld: /tmp/fbneo_libretro.so.JUItkX.ltrans9.ltrans.o:(.data.rel.ro+0x10e94): undefined reference to `BurnDrvnes_zunousengal'
collect2: error: ld returned 1 exit status
make: *** [Makefile:749: fbneo_libretro.so] Error 1
```

Steps to reproduce:
1. Launch "make pkatform=funkey" in "src/burner/libretro" folder
2. Wait for the compilation error

**Comment by barbudreadmon** [comment]
https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#how-to-build

The first command is not skippable if you are using one of those platforms requiring `LIGHT`

**Comment by DrUm78** [comment]
I think you did not get what I said. "LIGHT = 1" makes the compilation fail for the FunKey S, that's it. So you should remove it or fix it as it works anyway without it. Feel free to not do it though. :p

**Comment by barbudreadmon** [comment]
@DrUm78 i repeat, you need to follow the full build instructions, meaning you need to build the core like this : 
```
make -j5 -C src/burner/libretro platform=funkey generate-files
make -j5 -C src/burner/libretro platform=funkey
```
Otherwise the build will fail with the error you are mentioning.

I don't know if the `LIGHT` flag is required for sure, but it would make sense since this device has memory limitation similar to 3DS, did you actually try running games with higher memory requirements ? 2 games you should test : `metamrph` and `kof2003`.

**Comment by DrUm78** [comment]
Ok nice, but where do you see those specific build instructions?
Anyway, what I said is that "LIGHT = 1" does not work for the FunKey S, do whatever you want with it...

**Comment by barbudreadmon** [comment]
>"LIGHT = 1" does not work

For the 3rd time, running the `generate-files` command is a pre-requisite if you are building with `LIGHT`...

**Comment by DrUm78** [comment]
I have no problem with that, it's just that it's not in the doc so we cannot guess it. ;)

**Comment by barbudreadmon** [comment]
Well, adding the same additional make parameters to both commands seemed pretty natural to me, is it clearer with https://github.com/libretro/FBNeo/commit/deb95458887f4cf2b95e357fc0cfba368c708a75 ?

**Comment by DrUm78** [comment]
Nope at all sorry, but thanks.
