### ISSUE TITLE
Release a 1.1.0?

### ISSUE THREAD

**Issue by WhyNotHugo** [libretro/FBNeo#911]
Hi! I maintain [a package](https://aur.archlinux.org/packages/libretro-fbneo/) for this program in the Arch User Repos.

However, in recent months, 1.0.0 has failed to build, and the latest release fails to build too:

```
../../burn/snd/samples.cpp: In function ‘void BurnSampleInit(INT32)’:
../../burn/snd/samples.cpp:433:16: error: format not a string literal and no format arguments [-Werror=format-security]
  433 |         sprintf(szTempPath, _TtoA(SAMPLE_DIRECTORY));
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../burn/snd/samples.cpp: In function ‘void BurnSampleInitOne(INT32)’:
../../burn/snd/samples.cpp:559:16: error: format not a string literal and no format arguments [-Werror=format-security]
  559 |         sprintf(szTempPath, _TtoA(SAMPLE_DIRECTORY));
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
make: *** [Makefile:707: ../../burn/snd/samples.o] Error 1
```

There's been over 900 commits to `master` since the last release, and the latest version seems to work [and build!] fine.

Can you consider pushing a new 1.1.0 (or 1.0.1) release? This package tracks the latest stable, but I haven't been able to get any of the latest stable versions to build.)

**Comment by barbudreadmon** [comment]
1. maybe stop treating warnings as errors
2. last "release" is 1.0.0.2, next will be 1.0.0.4, basically odd numbers are wip and even numbers are snapshots we do from time to time, meaning current version is 1.0.0.3
3. "releases" aren't "stables", so you should always be building from last commit anyway

**Comment by WhyNotHugo** [comment]
> "releases" aren't "stables", so you should always be building from last commit anyway

Thanks, I'll do this.

**Comment by barbudreadmon** [comment]
FBAlpha used 4 numbers for its versioning (ex. `0.2.97.44`), so we kept that, there is no deeper meaning.
