### ISSUE TITLE
Some PGM games need macro

### ISSUE THREAD

**Issue by leoxxx** [libretro/FBNeo#927]
killbld&killbldp:AB,BC,AC,ABC,BCD
kov,kovplus,kovsh:AB,ABC
kovshp&kovytzy:AB,ABC,BCD
kov2&kov2p:AB,BC; for kov2p secret:BD,CD,BCD
theglad:AB,BC,AC,CD
svg:AD,BD,CD,BC,BCD
orlegend:AB,ABC
olds&oldsplus:AB,BC,AC,ABC
martmast:AB,BC,AD,BD,CD

**Comment by barbudreadmon** [comment]
1. i won't add per-game macros
2. pgm buttons are numbered from 1 to 4

decide on 4 combos and i *might* consider adding them

**Comment by leoxxx** [comment]
AB,BC,ABC,BCD.
Can add custom macro which player can customize combinative buttons?
