### ISSUE TITLE
Lunar Lander (llander) inputs are combined

### ISSUE THREAD

**Issue by Tybis** [libretro/FBNeo#955]
In Lunar Lander, the Start, Select, and Abort actions all seem to be mapped to a single input, instead of being individually mappable. Start and Abort being shared does not cause any issues, but Select causes the game to cycle between 4 different modes, altering physics and difficulty. The end result is that the game's physics change any time the Abort input is pressed.

**Comment by barbudreadmon** [comment]
Thanks for the report ! Fixed with https://github.com/libretro/FBNeo/commit/a19058e5c34115b882d42ed4fd1e2b631b474c18 (i moved those actions to L3/R3)
