### ISSUE TITLE
Xybots: Twist control profile is reversed.

### ISSUE THREAD

**Issue by IdiotBlueMage** [libretro/FBNeo#957]
I'm only bringing this one up because it's pretty counterintuitive.  When the controller is set to Modern, the left (Y) button twists right and the right (A) button twists left.  The arcade joystick setup and the Lynx port both have this reversed (twisting right goes right and twisting left goes left).

This is of course easily fixed with a remap, but I feel like the default should be fixed.

**Comment by barbudreadmon** [comment]
I'm totally fine with changing counterintuitive mappings, however i'm thinking a L/R mapping would make even more sense here, what do you think ?

**Comment by IdiotBlueMage** [comment]
Sounds pretty great to me!

**Comment by barbudreadmon** [comment]
The change is on git, thanks for the report !
