### ISSUE TITLE
Is working AVSP for you?

### ISSUE THREAD

**Issue by furiadeoso** [libretro/FBNeo#963]
Hi!

I've updated fbneo core some days ago and I'm getting romset match error with Alien vs Predator (avsp) and its clones. Maybe it have changed but I don't see the commit. Is it working for you? Thanks.

**Comment by LodanZark** [comment]
The older avsp set container an overdump rom that got fixed in this commit: https://github.com/finalburnneo/FBNeo/commit/46d8db8693a94d592be3bde2c1adee56614b70a3

**Comment by furiadeoso** [comment]
You are right! Thanks!
