### ISSUE TITLE
Rambo III: possible lightgun mode?

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/FBNeo#965]
Hello,

I am a Raspberry Pi (RetroPie) user with Sinden Lightguns, and this core has great support for lightgun games. Thank you!

My question involves a feature request: **can Rambo III have "lightgun" added to its control options?** 

As far as I am aware, the game only used joysticks for control. While there is a trackball dipswitch, I haven't seen any photos showing that a cabinet did use a trackball. My lightguns are able to control the action with that dipswitch set to trackball and the controller type set to mouse (full). However, it is not ideal. Tracking is pretty inconsistent with this setup. I only bring this up because other stick games like Terminator 2, Rail Chase, and Jurassic Park do have lightgun control options.

**Comment by barbudreadmon** [comment]
>Terminator 2, Rail Chase, and Jurassic Park do have lightgun control options

I'll investigate in the next few days, but i'm not sure it's gonna be possible : those 3 games originally used a gun, while rambo3 didn't

**Comment by StormedBubbles** [comment]
Thanks so much! I hope that things work out. 😃

I always seem to get confused about what is and isn't a "lightgun" game in emulation. To my eye, there isn't much difference between Rambo III and Terminator 2. Their cabinets both use a joystick mechanism of some kind to move around a set of crosshairs on screen. Terminator 2 just had a gun shell mounted to its mechanism for visual effect. 

I was worried about the character movement in Rambo III, but that appears to be tied 100% with the cursor movement (i.e., moving the crosshairs always moves the character).

**Comment by barbudreadmon** [comment]
Rambo 3 reads a "movement", while the other games read an absolute position.
I gave it a try without success, but maybe @dinkc64 will have a good idea ?

**Comment by dinkc64** [comment]
rambo3 only has trackball and joystick inputs, unfortunately neither will work properly with a lightgun.
But, that's not where the story ends.  stay tuned

**Comment by barbudreadmon** [comment]
I believe the main issue here is that the movement/position relation isn't linear (sometimes the cursor will keep moving even if you stopped the movement). I can't see many solutions aside from extracting or injecting the cursor position in the game, but i don't know if that's something possible.

**Comment by StormedBubbles** [comment]
I noticed that non-gun games "Star Wars" (starwars) and "The Empire Strikes Back" (esb) actually function very well with my Sinden gun if I change port 1 to "lightgun" and set the Y axis to "Normal" in the dip-switch settings within the core options. 

The cursor does start to get offset if the gun faces away from the screen and comes back, but the tracking is generally very solid. This is sort of a chicken/egg thing here. I'm not sure if info from these two Star Wars games may help with investigating Rambo III or if anything gleaned from Rambo III could help get more exact coordinates for the Star Wars games (or neither 😆).

**Comment by barbudreadmon** [comment]
>non-gun games "Star Wars" (starwars) and "The Empire Strikes Back" (esb)

Well, what we refer as "gun games" are games that read an absolute position to locate something on a screen : starwars and esb are actually gun games.

**Comment by dinkc64** [comment]
The other day I came up with a hack to make the  game use absolute input values, problem is, I didn't have time to fully finish it.
Hang in there..

**Comment by StormedBubbles** [comment]
Thank you both for the explanations and efforts! I look forward to that hack!

Is there an indicator amongst the documentation that points out the games that use absolute position?

**Comment by dinkc64** [comment]
I finally got the hack to work without *hopefully* unwanted side effects, it will be a dip option at the bottom of the list:
"Lightgun mode for Trackball (Hack)"... stay tuned :)

best regards,
- dink

**Comment by dinkc64** [comment]
It's in, just needs to make its way to the libretro version!
p.s. it's only available for the europe and u.s. versions of rambo3, not the prototype

best regards,
- dink

**Comment by barbudreadmon** [comment]
>Is there an indicator amongst the documentation that points out the games that use absolute position?

No, aside from launching the game and seeing if it responds to pointer/lightgun device types, there is no way to guess (except ofc reading our driver code : they use the `BurnGun` functions).
The hack made its way to the libretro port.

**Comment by dinkc64** [comment]
To find lightgun games, use google or youtube and search for: arcade lightgun games

**Comment by StormedBubbles** [comment]
Thanks for the info and for the update!

I updated and see that option within the dipswitches. I deleted all traces of rambo3 (nvram, high scores) in the ROM folder but can't seem to get either player to function with the lightgun. I have the dipswitch set to trackball and also have the new hack on. Ports 1 and 2 are set to lightgun. I don't get any cursor movement or functioning buttons. Do I have that set up correctly?

Also, I noticed that player 2's gun no longer tracks for me in other games. I tested Point Blank and Rail Chase. The P2 cursor seems stuck in a corner of the screen. Was there some recent update that affected lightguns for every game?

**Comment by barbudreadmon** [comment]
@dinkc64 Is it safe to remove the second condition in `BurnGunIsActive` ?

**Comment by dinkc64** [comment]
"dinkc64 linked a pull request that will close this issue 24 minutes ago" - what's this about?   maybe I hit a wrong button while I was sleeping? :)  What ever that means, it was unintentional, hopefully it didn't break anything.

**Comment by barbudreadmon** [comment]
@dinkc64 apparently you can link issues and PR from the right column of a github web page, i suppose you miss-clicked there or something :)

@StormedBubbles an improved version of the hack is on git, it should now work as expected

**Comment by dinkc64** [comment]
thanks for fixing that :)

**Comment by StormedBubbles** [comment]
Thanks so much! It is all good now. Both players appear to work great! 

I only use the libretro port of FBNeo on a Raspberry Pi. For future reference, is it better to put a request like this here or on the main GitHub page? I suppose this wasn't a libretro-only request.

**Comment by barbudreadmon** [comment]
You can use either repo, you can also use our forum (https://neo-source.com/)
