### ISSUE TITLE
Likely endian issue on Liquid Kids (liquidk, Taito F2)

### ISSUE THREAD

**Issue by vaguerant** [libretro/FBNeo#966]
Some stuff be upside down. Some other stuff don't, though.

Issue does not occur on upstream Windows build, but does occur on libretro Wii U build.

| Wii U (PPC32 big-endian) | Windows (x86 little-endian) |
|:-:|:-:|
| ![liquidk-211222-031759](https://user-images.githubusercontent.com/5259025/146963472-a79c5dce-a4e2-47fc-a8ae-326c7989cd91.png) | ![liquidk-12-21-162343](https://user-images.githubusercontent.com/5259025/146964274-ea01d0e7-64df-4c4f-b64b-d2ac76ed5bdb.png) |
| ![liquidk-211222-031808](https://user-images.githubusercontent.com/5259025/146963486-6fce1f36-cd6b-4d9b-8216-4a8abe58866e.png) | ![liquidk-12-21-162347](https://user-images.githubusercontent.com/5259025/146964359-350780ff-2f4d-43f8-be1c-ceacb36e20a9.png) |
| ![liquidk-211222-031814](https://user-images.githubusercontent.com/5259025/146963493-83aeb864-2e1c-4f06-8d5c-1b1934cd328d.png) | ![liquidk-12-21-162438](https://user-images.githubusercontent.com/5259025/146964439-3917f18d-428c-4736-8e8d-a6ef6747b814.png) |
| ![liquidk-211222-031828](https://user-images.githubusercontent.com/5259025/146963512-4d345eb6-1052-4d75-8d3f-d540d2698074.png) | ![liquidk-12-21-162707](https://user-images.githubusercontent.com/5259025/146964557-bcca6a7f-8501-42c5-b786-4ee3ca4c0730.png) |

**Comment by barbudreadmon** [comment]
let's tag @crystalct about this

**Comment by crystalct** [comment]
I will look it

**Comment by barbudreadmon** [comment]
it should have been fixed by https://github.com/libretro/FBNeo/commit/4e6d8ca879eb312e22548b11acbc1cbd36427f23

**Comment by vaguerant** [comment]
Can confirm, game works correctly on Wii U now. Great job, crystalct!
