### ISSUE TITLE
There isn't Multi Keys Button for Neogeo CD Games

### ISSUE THREAD

**Issue by yudhiyou** [libretro/FBNeo#967]
Please, can you add multi keys button on Neogeo CD games like on regular Neogeo games? I meant like AB, CD, ABC, and BCD buttons.
Because those buttons are very crucial for neogeo games.

Thank you very much...

**Comment by barbudreadmon** [comment]
>Because those buttons are very crucial for neogeo games.

I love how people abuse the terms "crucial" or "unacceptable" when it comes to missing macros, while those games were never meant to be played with any macro...

Anyway, it's an overlook from me, so i'll be adding this and another feature (classic/modern layouts) to neocd games later today

**Comment by yudhiyou** [comment]
Thanks...

**Comment by barbudreadmon** [comment]
Btw, it's on git and probably available from buildbot already. Closing.
