### ISSUE TITLE
Cannot Save Game Remap Control on Neogeo CD Subsystem

### ISSUE THREAD

**Issue by yudhiyou** [libretro/FBNeo#968]
Help... When using Neogeo CD Subsystem on FBNeo cannot save game remap control. I am not sure if this happen on other subsystem too.
Is it Retroarch limitation? If yes, is there other solution for saving remap control?

**Comment by barbudreadmon** [comment]
FWIW, i believe a RA bug related to game remapping was fixed just the other day, your issue might be related or not so you might want to update RA to latest nightly.

Either way, this is a RA feature, so please don't report that kind of issues here. Closing.
