### ISSUE TITLE
Gauntlet and Gaunt2 crash with runahead enabled

### ISSUE THREAD

**Issue by snaphat** [libretro/FBNeo#971]
Loading gauntlet or gaunt2 both crash retroarch on Windows x64 (latest release build of retroarch with core version - 243074b) if runahead is enabled.

**Comment by barbudreadmon** [comment]
FYI, single instance is the officially supported (and recommended) runahead mode for FBNeo. 
Your issue seems to happen because you enabled second instance, i'll see if i can fix it, yet again second instance runahead is not a priority as far as we are concerned.

**Comment by dinkc64** [comment]
IMO: if there is a crash it's always our fault, and should be fixed.  We can't always make second instance perfect but it should never crash.

**Comment by barbudreadmon** [comment]
Fixed, closing.
