### ISSUE TITLE
Renegade not saving high scores even though it’s listed in the hiscore.dat file

### ISSUE THREAD

**Issue by Phill2cb** [libretro/FBNeo#973]
I can’t get the High Scores to save on Renegade which is using FB Neo on a RetroPie. I’ve noticed a few other games I’ve played through FbNeo have the High Score option under Quick Menu - Options, however Renegade does not have this option.
![164EF4CF-82D3-423E-A437-A991AFBB2BA8](https://user-images.githubusercontent.com/98924246/152254626-a63627c7-0b54-4389-a628-ca90f8e697b2.jpeg)

• My Directory is set up to RetroPie/BIOS
![BB348D8C-74D8-4716-A77B-FFB65CEE372E](https://user-images.githubusercontent.com/98924246/152254772-75e3119c-7c14-4477-b655-1a8d66a4a136.jpeg)

• I see Renegade listed in the hiscore.dat file which is in RetroPie/BIOS/fbneo
![0E65EBB6-ED1E-4380-9D93-5DB6FD6E9F35](https://user-images.githubusercontent.com/98924246/152254978-34dbf212-cd5b-4f6e-88c1-817567dad687.jpeg)

• Renegade is under RetroPie/ROMS/Arcade
![A0D9895E-F5E7-48DB-AB86-91A5249AB2CF](https://user-images.githubusercontent.com/98924246/152255024-045af042-c6be-442c-bdd3-76774098d562.jpeg)

• I see .hi files under RetroPie/ROMS/Arcade/fbneo but no .hi files for Renegade
![8F037A66-5789-48A6-90B1-1D260837A9D8](https://user-images.githubusercontent.com/98924246/152255082-33ded589-32ed-4bab-a78f-b95b792ca3bd.jpeg)

**Comment by barbudreadmon** [comment]
Thanks for the report !
No need for the many screenshots, as said at https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#hiscore-wont-save-why- it's a pretty common thing and you just need to let me know.
The fix is on git, closing.

**Comment by Phill2cb** [comment]
@barbudreadmon i appreciate the help. As this is all very new to me, I’m not sure where to go to on Git and what to do from there. Do I need to update the high score file or the game file?

**Comment by barbudreadmon** [comment]
you need to update your core from sources, using retropie-setup script

**Comment by Phill2cb** [comment]
@barbudreadmon Thanks, confirmed working on my side. 

The only thing I noticed is that each time I load up the game, the first time I save a high score does not save the Initials I put in and shows as 3 blank spots. Every new score after that maintains the inputted initials.

**Comment by barbudreadmon** [comment]
I'm not sure, some games have weird behavior and require extra steps before hiscores save properly. 
Games that didn't save hiscores in some kind of nvram/eeprom were meant to lose hiscores when powering them off, this method of extracting/injecting hiscore by using addresses from hiscore.dat is a hack, and shouldn't be considered failsafe imho.
