### ISSUE TITLE
Lightgun support for gijoe

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/FBNeo#974]
Hi,

Thanks again for all your help! I tried out gijoe today and noticed that lr-fbneo allows all 4 players to choose "lightgun" as an input method. It seems that the controls for this are not hooked up, though, as mice/lightguns do not seem to move the crosshairs. The way the character moves with respect to the crosshairs is similar to rambo3, so I'm hoping this one is a candidate for lightgun usage. The only issue I noticed is that you need to use joystick up/down to select your character, which may be a little awkward with a mouse/gun input.

**Comment by barbudreadmon** [comment]
>I tried out gijoe today and noticed that lr-fbneo allows all 4 players to choose "lightgun" as an input method

The same applies to pacman and street fighter, but it doesn't mean they can be played with a lightgun, that list of device type isn't dynamic.

Last time it was somehow possible to hack this because of the trackball support, but gijoe doesn't have that kind of support, it's a 100% digital game.

**Comment by StormedBubbles** [comment]
I understand. Sorry, I hadn't played a non-gun game in a while had forgotten that the list of possible input choices was the same across the board in the RetroArch GUI.
