### ISSUE TITLE
Add Pentagon (ZX Spectrum) games

### ISSUE THREAD

**Issue by AngelofMe** [libretro/FBNeo#976]
I downloaded from retrosouls official website
three files
yazzie48.tap crc b4b55b08
yazzie128.tap crc 68d21e49
yazziePentagon.tap crc 2756b875
I use unreal speccy portable android version 0.0.86.19 to load three tap files but only pentagon success

**Comment by barbudreadmon** [comment]
The correct place for console/computer game requests is at https://neo-source.com/index.php?topic=3656.750
