### ISSUE TITLE
Alpine Ski (alpine) game-reported Dipswitch bug

### ISSUE THREAD

**Issue by roslof** [libretro/FBNeo#982]
When launching **Alpine Ski** (romname ```alpine```) the following libretro notifications (actually, the same notif twice) from lr-fbneo appear:

1. ```Default value for '[Dipswitch] Extended Time Every' not found, it's a bug, please report it```
2. ```Default value for '[Dipswitch] Extended Time Every' not found, it's a bug, please report it```

Cheers!

**Comment by barbudreadmon** [comment]
thanks for the report, the fix is in !

**Comment by roslof** [comment]
Fix confirmed working. Cheers @barbudreadmon
