### ISSUE TITLE
Make Trax (maketrax), North America clone of Crush Roller partially renders upside-down

### ISSUE THREAD

**Issue by roslof** [libretro/FBNeo#983]
Tested with Raspberry Pi 4B (commit 51719e5, but has existed for at least many releases)

**Game:** Make Trax (maketrax)
**Parent:** Crush Roller (crush)

**Bug Description:**
While playing Make Trax, the player character (paintbrush) renders correctly at the bottom center of the screen, but the rest of the gameboard, including enemies, scores and 'paint' from the paintbrush renders rotated 180-degrees.

Note 1: This is not a new issue, and has appeared for at least many releases over the months.
Note 2: The parent game "Crush Roller" (crush) renders correctly.

**Comment by barbudreadmon** [comment]
thanks for the report, the fix is on git :)

**Comment by roslof** [comment]
Fix works perfectly. Cheers, @barbudreadmon
