### ISSUE TITLE
Incorrect refresh rate in Vigilante

### ISSUE THREAD

**Issue by rtomasa** [libretro/FBNeo#985]
Currently Vigilante runs at 55Hz but it seems that the correct refresh should be 56.34Hz

**Comment by barbudreadmon** [comment]
Thanks for the heads-up and sorry for the late answer, i'd recommend opening issues directly upstream as i can be forgetful about checking this repo's issue tracker.
Fixed upstream (https://github.com/finalburnneo/FBNeo/commit/8994e9f04ea67a2fd44559fbf4db7a821329b716), the fix will made it to the libretro port after my next sync (later today).
