### ISSUE TITLE
The dip switch of Double Dragon 2 cannot adjust the difficulty.

### ISSUE THREAD

**Issue by evoqoo** [libretro/FBNeo#986]
The dip switch of [Double Dragon 2] ddragon2.zip cannot adjust the difficulty.
![註解 2022-05-18 114541](https://user-images.githubusercontent.com/105764193/168953009-a1c7d69b-c6bd-4893-8c8f-2f8bc88c1a03.png)

**Comment by barbudreadmon** [comment]
Thanks for the report, the fix is on git.
Btw, next time i recommend reporting issues directly upstream at https://github.com/finalburnneo/FBNeo .

**Comment by evoqoo** [comment]
thank you very much!
Next time I will report directly to upstream.
