### ISSUE TITLE
Pleiades (pleiads) is missing "Warp" (Button 2) Input

### ISSUE THREAD

**Issue by roslof** [libretro/FBNeo#988]
The arcade game Pleiades features a "Warp" button that moves the player ship to a new location on-screen. Behavior is similar to hyperspace for other games.

I noticed MAME and FBNeo both are missing functionality for the second button. Not sure if this was ever implemented in any emulator.

Best
-Ros

**Comment by barbudreadmon** [comment]
Thanks for the heads-up, added in https://github.com/finalburnneo/FBNeo/commit/102e6c0d795dafec061867f58e85cee0c3634a01

I don't think this button actually exists in `pleiads` though: as far as i can tell from search engines, there are 1-button and 2-buttons variant of this cabinet, and i could only find evidence of Centuri's version (`pleiadce`) having that additional Warp button.

**Comment by roslof** [comment]
It appears you're correct as typical. I checked other cabinet control panels (eg. Tekhan) and they only have one button. Great to know about this difference. I'm recompiling lr-fbneo now and will close upon confirmation.
Cheers @barbudreadmon
