### ISSUE TITLE
zx spectrum keyboard overlay

### ISSUE THREAD

**Issue by AngelofMe** [libretro/FBNeo#990]
Android arm64-v8a
A Very Sheepy Christmas (128K)
verysheepyxmas
![verysheepyxmas-220622-105011](https://user-images.githubusercontent.com/26894447/174933838-9dbfab9c-dd21-4568-8b17-c31620bd076e.png)
![verysheepyxmas-220622-105114](https://user-images.githubusercontent.com/26894447/174933849-4472b13d-7f48-4cbd-93bd-cdd40b2ee7f8.png)

**Comment by AngelofMe** [comment]
FBN how to play this game?

**Comment by AngelofMe** [comment]
FBN how to play this game?

**Comment by AngelofMe** [comment]
i think msx and zx spectrum games need a virtual keyboard to be played

**Comment by AngelofMe** [comment]
2 msx games
black onyx 1 & 2
blckonyx
blckony2
![blckony2-220622-111118](https://user-images.githubusercontent.com/26894447/174935517-efcf1432-afc9-4db7-a21f-158f8edacf64.png)
![blckonyx-220622-111057](https://user-images.githubusercontent.com/26894447/174935522-4c2a86f9-9aa6-46cf-ab11-cbea851c8c67.png)
My Suggestion: Select Button - Keyboard Overly

**Comment by AngelofMe** [comment]
![monkeyj-220622-112233](https://user-images.githubusercontent.com/26894447/174936863-c3a89a75-7b14-4cdc-9c46-302e93db962d.png)

**Comment by AngelofMe** [comment]
On-Screen Virtual Keyboard Overly
![Chez Maxime (France)-220622-124006](https://user-images.githubusercontent.com/26894447/174945501-8318a175-30d6-4474-9b2c-b2ae41c17285.png)
![Activision Decathlon, The (USA, Europe)-220622-123733](https://user-images.githubusercontent.com/26894447/174945506-074ac852-7b64-4090-ad42-8fd4a003d50b.png)

**Comment by barbudreadmon** [comment]
virtual keyboards and overlays are retroarch features, not core features, closing.
