### ISSUE TITLE
RetroArch msx pause button and others

### ISSUE THREAD

**Issue by AngelofMe** [libretro/FBNeo#992]
![Contra (Japan)-220630-140245](https://user-images.githubusercontent.com/26894447/176606658-8eee341c-f7a1-467b-a0b1-6196d3d06acf.png)
Contra (Japan)
It's a MSX 2 game actually
pause button - F1
![Moai no Hibou (Japan)-220630-140443](https://user-images.githubusercontent.com/26894447/176606672-df33adbd-21c6-42a0-933d-d1723ce81f24.png)
Moai no Hibou (Japan)
a MSX 1 game
retry button - F1
![Moai no Hibou (Japan)-220630-140623](https://user-images.githubusercontent.com/26894447/176606677-cd1dc0b3-5702-4cfe-acc4-4a0da628b8e5.png)
show me the face - F5
![Moai no Hibou (Japan)-220630-140457](https://user-images.githubusercontent.com/26894447/176606681-fc9371fa-4675-46a7-b77c-bd2b68be37b1.png)

Joystick + emulated keyboard
{
// first 6: joystick
{ RETRO_DEVICE_ID_JOYPAD_UP,       JST_UP },
{ RETRO_DEVICE_ID_JOYPAD_DOWN,   JST_DOWN },
{ RETRO_DEVICE_ID_JOYPAD_LEFT,   JST_LEFT },
{ RETRO_DEVICE_ID_JOYPAD_RIGHT, JST_RIGHT },
{ RETRO_DEVICE_ID_JOYPAD_A,     JST_FIREA },
{ RETRO_DEVICE_ID_JOYPAD_B,     JST_FIREB },
// rest: keyboard
{ RETRO_DEVICE_ID_JOYPAD_X,        KBD_F3 },
{ RETRO_DEVICE_ID_JOYPAD_Y,     KBD_SPACE },
{ RETRO_DEVICE_ID_JOYPAD_START,    KBD_F1 },
{ RETRO_DEVICE_ID_JOYPAD_SELECT,   KBD_F2 },
{ RETRO_DEVICE_ID_JOYPAD_L,        KBD_F4 },
{ RETRO_DEVICE_ID_JOYPAD_R,        KBD_F5 },
{ RETRO_DEVICE_ID_JOYPAD_L2,    KBD_GRAPH },
{ RETRO_DEVICE_ID_JOYPAD_R2,  KBD_CONTROL },
{ RETRO_DEVICE_ID_JOYPAD_L3,    KBD_ENTER },
{ RETRO_DEVICE_ID_JOYPAD_R3,   KBD_ESCAPE },
};

Emulated keyboard with a fixed mapping
{
{ RETRO_DEVICE_ID_JOYPAD_UP,       KBD_UP },
{ RETRO_DEVICE_ID_JOYPAD_DOWN,   KBD_DOWN },
{ RETRO_DEVICE_ID_JOYPAD_LEFT,   KBD_LEFT },
{ RETRO_DEVICE_ID_JOYPAD_RIGHT, KBD_RIGHT },
{ RETRO_DEVICE_ID_JOYPAD_B,     KBD_ENTER },
{ RETRO_DEVICE_ID_JOYPAD_A,     KBD_SPACE },
{ RETRO_DEVICE_ID_JOYPAD_X,           'n' },
{ RETRO_DEVICE_ID_JOYPAD_Y,           'm' },
{ RETRO_DEVICE_ID_JOYPAD_SELECT,   KBD_F4 },
{ RETRO_DEVICE_ID_JOYPAD_START,    KBD_F1 },
{ RETRO_DEVICE_ID_JOYPAD_L,        KBD_F2 },
{ RETRO_DEVICE_ID_JOYPAD_R,        KBD_F3 },
{ RETRO_DEVICE_ID_JOYPAD_L2,    KBD_GRAPH },
{ RETRO_DEVICE_ID_JOYPAD_R2,  KBD_CONTROL },
{ RETRO_DEVICE_ID_JOYPAD_L3,       KBD_F5 },
{ RETRO_DEVICE_ID_JOYPAD_R3,   KBD_ESCAPE },
};

I don't know which is better

**Comment by barbudreadmon** [comment]
I'm seriously starting to get sick of having to decrypt the issues you are opening, you don't even mention what you want here.

**Comment by barbudreadmon** [comment]
F1 is start button
