### ISSUE TITLE
Forgive my stupidity and carelessness, this time I'm serious

### ISSUE THREAD

**Issue by AngelofMe** [libretro/FBNeo#997]
I'm sorry, I really didn't mean to piss you off
 You guys are busy every day, I really don't want to make trouble
 But I sent an issue before and didn't clarify the idea
 Please add a bunch of buttons that are not commonly used, I regret it very much
 I don't want to keep that wrong change forever
 I know sometimes my issues are really stupid
 But that doesn't matter what, but I'm serious about MSX's F1 and Stop
 I know a lot of people who are having trouble with the keys when using FBN libretro, so they don't know what to do when they get stuck, so I tested all MSX keys, F1 is often used for Konami games, and Stop is often used  For other games, some games use both F1 and Stop
 At that time, F5 was just a coincidence, not a button effect. I forgot Stop when submitting.
 This is the first time I've been on Github for so many years to pull a request for my mistake
 Sorry, it's all my fault, hope don't ignore me, this time it's completely sincere and heartfelt
 Since I am worried about changing the content making more bugs, so I sent it to issue

FBNeo/src/burner/libretro/retro_input.cpp

	// Handle MSX
	if ((nHardwareCode & HARDWARE_PUBLIC_MASK) == HARDWARE_MSX) {
		if (strcmp("Button 1", description) == 0) {
			GameInpDigital2RetroInpKey(pgi, nPlayer, RETRO_DEVICE_ID_JOYPAD_B, description);
		}
		if (strcmp("Button 2", description) == 0) {
			GameInpDigital2RetroInpKey(pgi, nPlayer, RETRO_DEVICE_ID_JOYPAD_A, description);
		}
		if (strcmp("Key STOP", description) == 0) {
			GameInpDigital2RetroInpKey(pgi, nPlayer, RETRO_DEVICE_ID_JOYPAD_START, description);
		}
		if (strcmp("Key F1", description) == 0) {
			GameInpDigital2RetroInpKey(pgi, nPlayer, RETRO_DEVICE_ID_JOYPAD_SELECT, description);
		}
		if (strcmp("Key UP", description) == 0) {
			GameInpDigital2RetroInpAnalogRight(pgi, nPlayer, RETRO_DEVICE_ID_ANALOG_Y, JOY_NEG, "Key UP / Key DOWN");
		}
		if (strcmp("Key DOWN", description) == 0) {
			GameInpDigital2RetroInpAnalogRight(pgi, nPlayer, RETRO_DEVICE_ID_ANALOG_Y, JOY_POS, "Key UP / Key DOWN");
		}
		if (strcmp("Key LEFT", description) == 0) {
			GameInpDigital2RetroInpAnalogRight(pgi, nPlayer, RETRO_DEVICE_ID_ANALOG_X, JOY_NEG, "Key LEFT / Key RIGHT");
		}
		if (strcmp("Key RIGHT", description) == 0) {
			GameInpDigital2RetroInpAnalogRight(pgi, nPlayer, RETRO_DEVICE_ID_ANALOG_X, JOY_POS, "Key LEFT / Key RIGHT");
		}
	}

**Comment by AngelofMe** [comment]
@barbudreadmon 
I wasted your precious time, I don't want you to be anxious because of me

**Comment by barbudreadmon** [comment]
Your english is very hard to understand. What you are asking is for the STOP key to be added, and for the F1/STOP keys to be mapped by default on select/start because they are somehow more important than F2/F3/F4/F5/F6 ?

**Comment by AngelofMe** [comment]
Namcot, Compile(a few), Konami, Casio, Capcom, Taito, Sega, Jaleco, ASCII(i didn't test)••• games
@barbudreadmon 
I'm tired
all namcot games stop is pause
![Screenshot_20220708-110411_Trebuchet](https://user-images.githubusercontent.com/26894447/177909361-768f4c90-aca3-43a0-b690-128d00a5781a.png)
![Screenshot_20220708-110425_Trebuchet](https://user-images.githubusercontent.com/26894447/177909367-122c705a-f9ca-4fee-8365-1c2e2a749275.png)
![Screenshot_20220708-110433_Trebuchet](https://user-images.githubusercontent.com/26894447/177909369-d40c5e72-2604-4abc-a547-7d460aa7480c.png)


![10-Yard Fight (Japan)-Stop(pause)](https://user-images.githubusercontent.com/26894447/177909407-aec56e24-976a-435f-9515-fb45a954a34a.png)
![1942 (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909410-25542c13-687d-4ec4-a5a7-866ec44b3f81.png)
![A E  (Japan)-F1(play)Stop(pause)](https://user-images.githubusercontent.com/26894447/177909413-75183162-6301-41ec-a91e-3e676acf9536.png)
![Arkanoid (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909416-a24bddf5-040e-4fd2-9c4b-7664ac46bcd5.png)
![Bosconian (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909418-a2729142-9157-4c43-9bb4-d0e730bb472d.png)
![Break In (Japan)-Stop(pause)](https://user-images.githubusercontent.com/26894447/177909421-06862b14-b344-41e5-bef7-be0d74199fe2.png)
![Bubble Bobble (Korea) (Unl)-stop(restart system)](https://user-images.githubusercontent.com/26894447/177909424-08a36026-8cfa-4ac6-8eba-4d4fe67afd6e.png)
![Buru To Marty Kikiippatsu - Inspecteur Z (Japan)-F1(retry)](https://user-images.githubusercontent.com/26894447/177909426-38db7313-1517-4626-b57b-db0d5cd0e27b.png)
![Buru To Marty Kikiippatsu - Inspecteur Z (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909427-c3139713-73f2-4ea0-9de5-0c5134de2fdd.png)
![C-So! (Japan)-stop(pause) same as sg1000](https://user-images.githubusercontent.com/26894447/177909430-c35ea677-9cbb-4acb-83a9-79a77041cb7e.png)
![Choplifter (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909433-a4f926f1-c75a-4512-b2f4-ebd2e26ed8b2.png)
![Dig Dug (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909436-abc7ce40-194c-4a91-9355-1ea1679b4d21.png)
![Doki Doki Penguin Land (Japan)-Stop(pause)](https://user-images.githubusercontent.com/26894447/177909437-f6d08d6f-cdb4-4dd4-b696-613d8ed3be80.png)
![Druaga no Tou (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909438-c79b9206-1523-4a02-a88f-d685294e8988.png)
![Eggerland Mystery (Japan)-Stop(retry)](https://user-images.githubusercontent.com/26894447/177909440-67caad19-d659-46b3-b499-54d63d961fc4.png)
![Exerion II - Zorni (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909442-40d0f742-cabf-4d42-a6c4-d58461979ef6.png)
![Fairy Land Story, The (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909444-b84a88de-9eda-4ddb-8a69-ebb12fc9f6f1.png)
![Final Justice (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909445-c88a4544-4d20-4df5-b0db-f7ca00bd8423.png)
![Galaga (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909446-841f06b1-80a7-46e8-b6cb-ec7aab7ca0c2.png)
![Galaxian (Japan) (Alt)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909450-b2744075-0500-436d-b67f-4db6c2893d0b.png)
![Gojira-kun (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909453-a525f09a-eba8-4920-a37d-30c7b9a890db.png)
![Golvellius (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909456-e4949356-c4e5-4893-897b-dd538d69d093.png)
![Goonies, The (Japan)-F1(Pause)](https://user-images.githubusercontent.com/26894447/177909457-bbab99e8-fa4d-4bb8-a12d-2325749f16d8.png)
![Green Beret (Europe)-F1(retry)](https://user-images.githubusercontent.com/26894447/177909463-d7a570b0-2ad4-434c-a8f7-21f0d030af16.png)
![Green Beret (Europe)-Stop(Pause)](https://user-images.githubusercontent.com/26894447/177909464-b0a8e4d0-7d27-4e28-adc5-24d6749650d6.png)
![Guardic (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909467-cb9d3c08-36d5-4745-8679-771722869d5e.png)
![King   Balloon (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909470-7a1e3adc-f601-442a-bc27-69ac8dd0e2e7.png)
![Mappy (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909472-b3c6d112-d309-4b43-b03f-39110ab1e63f.png)
![Meikyuu Shinwa (Japan) (Alt)-stop(retry)](https://user-images.githubusercontent.com/26894447/177909474-241a3ee2-091a-424e-8fef-77de7956d288.png)
![Moai no Hibou (Japan)-F1(retry)](https://user-images.githubusercontent.com/26894447/177909476-e57cc0ed-617f-4711-9c92-6d3d73b42754.png)
![Moai no Hibou (Japan)-Stop(Pause)](https://user-images.githubusercontent.com/26894447/177909478-092509a8-aa18-4205-87ac-6d29dd56c29f.png)
![Nemesis (Japan, Europe)-F1(pause)](https://user-images.githubusercontent.com/26894447/177909480-c428a0a8-4cf4-4900-acab-6c18968932c9.png)
![Nemesis 2 (Japan, Europe)-F1(Pause)](https://user-images.githubusercontent.com/26894447/177909483-5f8fb86f-e67d-47c3-b4ea-d076a0df3ae8.png)
![Nemesis 3 - The Eve of Destruction (Japan, Europe)-F1(Pause)](https://user-images.githubusercontent.com/26894447/177909484-7188d6f9-9ad2-4717-bb97-5984ac069661.png)
![Pooyan (Japan)-F1(retry)](https://user-images.githubusercontent.com/26894447/177909485-7864e459-ad0d-4411-93f3-ac63344b7c3a.png)
![Q-bert (Japan)-F1(Pause)](https://user-images.githubusercontent.com/26894447/177909488-8d6471b7-075c-46c5-b1ca-ea33d65cd680.png)
![Rally-X (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909492-340661d3-05df-4ebe-b471-2885c4aeb8ca.png)
![Senjo no Ookami (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909494-aae09a9a-dd8c-47d0-973e-5d92b4119843.png)
![Super Bubble Bobble (Korea) (Unl)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909497-5411a854-b651-4094-bc1b-25de4aa8d838.png)
![Tank Battalion (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909499-0f8ef178-54d2-47ff-be5a-1f811fde52a1.png)
![Warp   Warp (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177909502-510ed51f-fb5f-4cb3-ae11-4723e09501b8.png)
![Zaxxon (Japan)-Stop(Pause)](https://user-images.githubusercontent.com/26894447/177909504-5dc28c2e-62db-44b0-bb93-da723f7fd808.png)
![Zoom 909 (Japan)-Stop(pause)](https://user-images.githubusercontent.com/26894447/177909506-8766f0d5-6f78-4181-8eff-b07f516928c6.png)

**Comment by AngelofMe** [comment]
that's why stop=start, f1=select

**Comment by AngelofMe** [comment]
It is more convenient to map F1 and Stop to these joypads
[Arvel M1868-1](https://www.msx.org/wiki/Arvel_M1868-1)

[Fujitsu FMT-PD103](https://www.msx.org/wiki/Fujitsu_FMT-PD103)

[Fujitsu FMT-PD104](https://www.msx.org/wiki/Fujitsu_FMT-PD104)

[Popolon NES Joypad For MSX](https://www.msx.org/wiki/Popolon_NES_Joypad_For_MSX)

[Quickshot QS-127](https://www.msx.org/wiki/Quickshot_QS-127)

[Spital Sangyo JOY-CONT Limited Edition](https://www.msx.org/wiki/Spital_Sangyo_JOY-CONT_Limited_Edition)

[Spital Sangyo JOY-CONT Turbo 4](https://www.msx.org/wiki/Spital_Sangyo_JOY-CONT_Turbo_4)

[Spital Sangyo JOY-CONT Turbo CT-5](https://www.msx.org/wiki/Spital_Sangyo_JOY-CONT_Turbo_CT-5)

[Spital Sangyo JOY-CONT Turbo CT-6](https://www.msx.org/wiki/Spital_Sangyo_JOY-CONT_Turbo_CT-6)

**Comment by AngelofMe** [comment]
![Screenshot_20220708-182939_Trebuchet](https://user-images.githubusercontent.com/26894447/177975608-c0cd2ea8-0a55-4a7c-8f6c-beaf67da9548.png)
![Aliens - Alien 2 (Japan)-stop(retry)](https://user-images.githubusercontent.com/26894447/177975683-b75befab-d354-4d60-9c6c-b5dce9edb4ee.png)
![Aliens - Alien 2 (Japan)-stop(you are dead)](https://user-images.githubusercontent.com/26894447/177975689-9f798fcb-f0c7-4016-9f82-f0c56d77b1f2.png)
![Aquattack (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177975694-86344743-1a08-4e10-b1a7-77370154527b.png)
![Bruce Lee (Japan)-F1(restart game)](https://user-images.githubusercontent.com/26894447/177975700-de3094e6-b262-4dae-baf5-b023057e3c10.png)
![Drainer (Japan)-F1(explosion)](https://user-images.githubusercontent.com/26894447/177975704-2a5ca714-dcb7-44e6-8a87-3a8f8278438f.png)
![Jagur (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177975709-b4351e8b-a445-480b-ac16-8d3ab197024a.png)
![Laptick 2 (Japan)-stop(retry)](https://user-images.githubusercontent.com/26894447/177975712-390332dc-5a65-4696-a383-c0638557e705.png)
![Shout Match (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177975716-10e3c5fc-bf6f-4fa7-aa2a-cfd74cbb63d4.png)
![Volguard (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177975719-32c75fe8-55e3-4f51-ade6-85570618c58b.png)
![Zanac (Japan)-stop(pause)](https://user-images.githubusercontent.com/26894447/177975722-927918fe-80cd-4053-8865-670af7bc4087.png)

**Comment by AngelofMe** [comment]
For instance, all most all Konami games use F1 to pause the game.
https://openmsx.org/manual/user.html

**Comment by AngelofMe** [comment]
For instance, all most all Konami games use F1 to pause the game.
https://openmsx.org/manual/user.html

**Comment by AngelofMe** [comment]
did you know 3 NES games Adventures of Lolo 1/2/3?
it's from Eggerland series
puzzle games
2 Eggerland MSX version games
When you do something wrong, you have to restart (die) from this level
Stop is necessary for these games

**Comment by AngelofMe** [comment]
did you know 3 NES games Adventures of Lolo 1/2/3?
it's from Eggerland series
puzzle games
2 Eggerland MSX version games
When you do something wrong, you have to restart (die) from this level
Stop is necessary for these games

**Comment by barbudreadmon** [comment]
We'll add that "STOP" button soon, thanks for the informations.

Some warning though, your issues are way too hard to read, you need to stop with the walls of images & text, **be concise**.

**Comment by AngelofMe** [comment]
thamks

**Comment by AngelofMe** [comment]
thamks

**Comment by AngelofMe** [comment]
???
![Screenshot_20220709-152926_Trebuchet](https://user-images.githubusercontent.com/26894447/178096377-84392bcb-b971-479b-bc31-e83de87cef4f.png)

**Comment by barbudreadmon** [comment]
It's on git and should be available from the online updater later today.
