### ISSUE TITLE
What's Light .dat missing?

### ISSUE THREAD

**Issue by AngelofMe** [libretro/FBNeo#999]
what's the difference between them?
FinalBurn Neo (ClrMame Pro XML, Arcade only).dat 10.38MB
FinalBurn Neo Light (ClrMame Pro XML, Arcade only).dat 8.38MB
I can't find any readme explaining so that's why I ask

**Comment by AngelofMe** [comment]
md5
FinalBurn Neo Light (ClrMame Pro XML, ColecoVision only).dat
Size: 276.89KB (283538B)
MD5: 7ed6e2318f2048089425818e4b2091b4
FinalBurn Neo (ClrMame Pro XML, ColecoVision only).dat
Size: 276.89KB (283538B)
MD5: 7ed6e2318f2048089425818e4b2091b4
FinalBurn Neo Light (ClrMame Pro XML, Fairchild Channel F Games only).dat
Size: 28.85KB (29547B)
MD5: 3a9ee904740d5be3653f3930937f17b2
FinalBurn Neo (ClrMame Pro XML, Fairchild Channel F Games only).dat
Size: 28.85KB (29547B)
MD5: 3a9ee904740d5be3653f3930937f17b2
FinalBurn Neo Light (ClrMame Pro XML, Game Gear only).dat
Size: 297.96KB (305112B)
MD5: 172627b6236a8e4cb097c8bc8c4c3e7d
FinalBurn Neo (ClrMame Pro XML, Game Gear only).dat
Size: 297.96KB (305112B)
MD5: 172627b6236a8e4cb097c8bc8c4c3e7d
FinalBurn Neo Light (ClrMame Pro XML, Master System only).dat
Size: 260.54KB (266794B)
MD5: 20b785e37a97f6c163195f88950f5993
FinalBurn Neo (ClrMame Pro XML, Master System only).dat
Size: 260.54KB (266794B)
MD5: 20b785e37a97f6c163195f88950f5993
FinalBurn Neo Light (ClrMame Pro XML, Megadrive only).dat
Size: 1.10MB (1158957B)
MD5: 6103b5e7d52f44a2ecbd5d88dfa687c9
FinalBurn Neo (ClrMame Pro XML, Megadrive only).dat
Size: 1.10MB (1158957B)
MD5: 6103b5e7d52f44a2ecbd5d88dfa687c9
FinalBurn Neo Light (ClrMame Pro XML, Neogeo only).dat
Size: 1.82MB (1910287B)
MD5: 68489fd489b8ab6a040f94ccf3d93e86
FinalBurn Neo (ClrMame Pro XML, Neogeo only).dat
Size: 1.82MB (1910287B)
MD5: 68489fd489b8ab6a040f94ccf3d93e86
FinalBurn Neo Light (ClrMame Pro XML, NeoGeo Pocket Games only).dat
Size: 88.33KB (90453B)
MD5: 224c66dc81adcd7123ab91ff6e144616
FinalBurn Neo (ClrMame Pro XML, NeoGeo Pocket Games only).dat
Size: 88.33KB (90453B)
MD5: 224c66dc81adcd7123ab91ff6e144616
FinalBurn Neo Light (ClrMame Pro XML, Sega SG-1000 only).dat
Size: 73.54KB (75306B)
MD5: 69696017f38620e7245133ac4813c45a
FinalBurn Neo (ClrMame Pro XML, Sega SG-1000 only).dat
Size: 73.54KB (75306B)
MD5: 69696017f38620e7245133ac4813c45a

**Comment by barbudreadmon** [comment]
https://docs.libretro.com/library/fbneo/#step-1-obtaining-an-xml-dat
